DMTF/libspdm

library/spdm_requester_lib/get_measurements.c
library/spdm_responder_lib/measurements.c
unit_test/test_spdm_requester/get_measurements.c
unit_test/test_spdm_responder/measurements.c

Be tested at spdm-emu & spdm-dump

Add Nonce field in the non-GENERATE_SIGNATURE case

---

library/spdm_requester_lib/get_measurements.c
library/spdm_responder_lib/measurements.c

Signed-off-by: yi1.li <yi1.li@intel.com>

Fix measurement block index hardcode

---

include/hal/library/cryptlib.h
os_stub/cryptlib_mbedtls/pk/dh.c
os_stub/cryptlib_mbedtls/pk/ec.c
os_stub/cryptlib_mbedtls/pk/sm2.c
os_stub/cryptlib_openssl/pk/dh.c
os_stub/cryptlib_openssl/pk/ec.c
os_stub/cryptlib_openssl/pk/sm2.c
unit_test/test_crypt/dh_verify.c
unit_test/test_crypt/ec_verify.c
unit_test/test_crypt/sm2_verify.c

Fix https://github.com/DMTF/libspdm/issues/16

enforce zero padding for shared key.

---

unit_test/test_spdm_responder/respond_if_ready.c

Signed-off-by: yi1.li <yi1.li@intel.com>

Add Nonce field to test8 of rsp_if_ready

---

include/library/spdm_common_lib.h
library/spdm_common_lib/context_data.c
library/spdm_requester_lib/get_version.c
library/spdm_responder_lib/version.c

Clear up for GET_VERSION/VERSION

---

.github/workflows/cmake.yml

Updated cmocka to the latest version and enabled simple build process.

Enable basic build

---

library/spdm_requester_lib/get_capabilities.c
library/spdm_responder_lib/capabilities.c

refer to issue https://github.com/DMTF/libspdm/issues/37
Signed-off-by: Yonghong Zhu <yonghong.zhu@intel.com>

Remove the dead code in flag_compability function

---

library/spdm_responder_lib/key_exchange.c
library/spdm_responder_lib/measurements.c

Revise inappropriate UNEXPECTED_REQUEST and UNSUPPORTED_REQUEST return.

Fit responder error return value 2

---

include/hal/library/cryptlib.h
library/spdm_crypt_lib/crypt.c
os_stub/cryptlib_mbedtls/pk/x509.c
os_stub/cryptlib_openssl/pk/x509.c
unit_test/test_size/cryptlib_dummy/pk/x509.c

spdm_x509_certificate_check return value bug

---

include/library/spdm_crypt_lib.h
library/spdm_crypt_lib/crypt.c

Part 1 of #22
Add init() and duplicate() and update() and final()

Add spdm_hash and spdm_hmac API

---

library/spdm_common_lib/context_data.c
library/spdm_common_lib/spdm_common_lib_internal.h
library/spdm_requester_lib/get_version.c
library/spdm_responder_lib/capabilities.c
library/spdm_responder_lib/version.c
unit_test/test_spdm_requester/challenge.c
unit_test/test_spdm_requester/get_capabilities.c
unit_test/test_spdm_requester/get_measurements.c
unit_test/test_spdm_requester/get_version.c
unit_test/test_spdm_requester/negotiate_algorithms.c
unit_test/test_spdm_responder/algorithms.c
unit_test/test_spdm_responder/capabilities.c
unit_test/test_spdm_responder/challenge_auth.c
unit_test/test_spdm_responder/measurements.c
unit_test/test_spdm_responder/respond_if_ready.c

Add version negotiation feature

---

include/library/spdm_secured_message_lib.h
library/spdm_secured_message_lib/context_data.c
library/spdm_secured_message_lib/session.c

Fix88 zeroized handshake key

---

library/spdm_requester_lib/get_version.c

REF: https://github.com/DMTF/libspdm/issues/125

Fix version sort issue in version negotiation in get_version request.

---

include/library/spdm_common_lib.h
library/spdm_common_lib/context_data.c
library/spdm_common_lib/spdm_common_lib_internal.h
library/spdm_common_lib/support.c
library/spdm_requester_lib/finish.c
library/spdm_requester_lib/handle_error_response.c
library/spdm_responder_lib/encap_response.c

This is preparation for https://github.com/DMTF/libspdm/issues/22

Remove shrink_message() API.

---

include/library/spdm_common_lib.h
library/spdm_common_lib/crypto_service_session.c
unit_test/test_spdm_requester/finish.c
unit_test/test_spdm_requester/key_exchange.c
unit_test/test_spdm_responder/finish.c
unit_test/test_spdm_responder/respond_if_ready.c

REF: https://github.com/DMTF/libspdm/issues/92

Include CERT_CHAIN header in the transcript hash.

---

unit_test/test_spdm_requester/get_certificate.c

Causes compile error on linux build.

Fix for set but unused variable "count".

---

README.md

Update README.md to be more descriptive on windows/linux setup/build/ults. Clarifies items I ran into as a new contributor.

Update README.md to be more descriptive on various items.

---

library/spdm_responder_lib/challenge_auth.c
library/spdm_responder_lib/key_exchange.c
library/spdm_responder_lib/psk_exchange.c

Fix100: Issues of handling Measurement Summary Hash

---

library/spdm_responder_lib/key_update.c

https://github.com/DMTF/libspdm/issues/162

Fix #162 typo.

---

include/library/spdm_common_lib.h
library/spdm_common_lib/spdm_common_lib_internal.h
library/spdm_requester_lib/get_certificate.c
library/spdm_responder_lib/encap_get_certificate.c

REF: https://github.com/DMTF/libspdm/issues/148

Add hook to verify the peer certiticate.

---

include/industry_standard/spdm.h
include/library/spdm_lib_config.h
library/spdm_common_lib/context_data.c
library/spdm_requester_lib/challenge.c
library/spdm_requester_lib/encap_certificate.c
library/spdm_requester_lib/encap_challenge_auth.c
library/spdm_requester_lib/encap_digests.c
library/spdm_requester_lib/encap_request.c
library/spdm_requester_lib/get_certificate.c
library/spdm_requester_lib/get_digests.c
library/spdm_requester_lib/spdm_requester_lib_internal.h
library/spdm_responder_lib/certificate.c
library/spdm_responder_lib/challenge_auth.c
library/spdm_responder_lib/digests.c
library/spdm_responder_lib/encap_challenge.c
library/spdm_responder_lib/encap_get_certificate.c
library/spdm_responder_lib/encap_get_digests.c
library/spdm_responder_lib/encap_response.c
library/spdm_responder_lib/receive_send.c
library/spdm_responder_lib/spdm_responder_lib_internal.h
unit_test/test_size/test_size_of_spdm_requester/spdm_requester_authentication.c
unit_test/test_spdm_requester/challenge.c
unit_test/test_spdm_requester/get_certificate.c
unit_test/test_spdm_requester/get_digests.c
unit_test/test_spdm_requester/test_spdm_requester.c
unit_test/test_spdm_responder/certificate.c
unit_test/test_spdm_responder/challenge_auth.c
unit_test/test_spdm_responder/digests.c
unit_test/test_spdm_responder/respond_if_ready.c
unit_test/test_spdm_responder/test_spdm_responder.c

Add conditional compile switches for CERT and CHAL capabilities.

---

library/spdm_requester_lib/get_digests.c

This is intended to fix https://github.com/DMTF/spdm-emu/issues/12.

Fix extra tokens at end of #endif

---

include/library/spdm_requester_lib.h
library/spdm_requester_lib/challenge.c
library/spdm_requester_lib/communication.c
library/spdm_requester_lib/get_measurements.c
library/spdm_requester_lib/key_exchange.c
library/spdm_requester_lib/psk_exchange.c
library/spdm_requester_lib/spdm_requester_lib_internal.h

The caller may need evaluate the nonce to see if there is any duplication.
REF: https://github.com/DMTF/libspdm/issues/137

need return nonce in GetMeasurement and Challenge to the caller

---

include/library/spdm_common_lib.h
library/spdm_common_lib/spdm_common_lib_internal.h

Move spdm_reset_message_buffer_via_request_code() to internal.

---

include/library/spdm_crypt_lib.h
include/library/spdm_device_secret_lib.h
include/library/spdm_secured_message_lib.h
library/spdm_common_lib/context_data.c
library/spdm_common_lib/context_data_session.c
library/spdm_common_lib/crypto_service.c
library/spdm_common_lib/crypto_service_session.c
library/spdm_common_lib/spdm_common_lib_internal.h
library/spdm_crypt_lib/crypt.c
library/spdm_responder_lib/measurements.c
library/spdm_secured_message_lib/context_data.c
library/spdm_secured_message_lib/encode_decode.c
library/spdm_secured_message_lib/session.c
library/spdm_secured_message_lib/spdm_secured_message_lib_internal.h
os_stub/spdm_device_secret_lib/lib.c
os_stub/spdm_device_secret_lib_null/lib.c
unit_test/test_spdm_requester/challenge.c
unit_test/test_spdm_requester/get_measurements.c
unit_test/test_spdm_requester/key_exchange.c
unit_test/test_spdm_requester/psk_exchange.c
unit_test/test_spdm_responder/finish.c

This is to fix issue https://github.com/DMTF/libspdm/issues/134 - prepare for 1.2 script.

Transcript hash prepare1.2

---

include/industry_standard/spdm.h
library/spdm_common_lib/context_data.c
library/spdm_common_lib/crypto_service.c
library/spdm_crypt_lib/crypt.c

This is to fix https://github.com/DMTF/libspdm/issues/133.

1.2 transcript hash

---

library/spdm_responder_lib/challenge_auth.c
library/spdm_responder_lib/key_exchange.c
library/spdm_responder_lib/psk_exchange.c

REF: #185
To avoid the duplicated code.

Optimize check of invalid measurement hash type

---

library/spdm_common_lib/context_data.c

FIX: https://github.com/DMTF/libspdm/issues/212
We will discuss formal solution in https://github.com/DMTF/libspdm/issues/205

revert assert check in context data, which causes spdm-emu fail.

---

unit_test/test_size/cryptlib_dummy/CMakeLists.txt
unit_test/test_size/cryptlib_dummy/cipher/aead_sm4_gcm.c
unit_test/test_size/cryptlib_dummy/hash/sha3.c
unit_test/test_size/cryptlib_dummy/hash/sm3.c
unit_test/test_size/cryptlib_dummy/hmac/hmac_sha3.c
unit_test/test_size/cryptlib_dummy/hmac/hmac_sm3.c
unit_test/test_size/cryptlib_dummy/kdf/hkdf_sha3.c
unit_test/test_size/cryptlib_dummy/kdf/hkdf_sm3.c
unit_test/test_size/cryptlib_dummy/pem/pem.c
unit_test/test_size/cryptlib_dummy/pk/ecd.c
unit_test/test_size/cryptlib_dummy/pk/ecx.c
unit_test/test_size/cryptlib_dummy/pk/sm2.c
unit_test/test_size/cryptlib_dummy/pk/x509.c

enable dummy crypto for new algorithm.

---

include/library/spdm_crypt_lib.h
include/library/spdm_secured_message_lib.h
library/spdm_crypt_lib/crypt.c
library/spdm_requester_lib/key_exchange.c
library/spdm_responder_lib/key_exchange.c
library/spdm_secured_message_lib/key_exchange.c
unit_test/test_spdm_requester/key_exchange.c
unit_test/test_spdm_responder/key_exchange.c
unit_test/test_spdm_responder/respond_if_ready.c

add SPDM1.2 sm2 key exchange.

---

library/spdm_secured_message_lib/encode_decode.c
library/spdm_secured_message_lib/session.c
library/spdm_secured_message_lib/spdm_secured_message_lib_internal.h
unit_test/test_spdm_requester/key_update.c

Fix https://github.com/DMTF/libspdm/issues/165

Key exchange

---

library/spdm_responder_lib/receive_send.c

Exclude more commands which have session dependency.

Save more size by excluding session dependent message.

---

include/library/spdm_common_lib.h
include/library/spdm_crypt_lib.h
include/library/spdm_device_secret_lib.h
include/library/spdm_secured_message_lib.h

Fix https://github.com/DMTF/libspdm/issues/19

Enable user configurable sdpm_lib_config.

---

unit_test/test_spdm_requester/get_certificate.c

Fix unused variables generated by conditional compilation directives.

Fix unused code

---

doc/test.md

Some steps still use old makefile.
We need change it to CMAKE.

Correct the incorrect info about build.

---

library/spdm_responder_lib/challenge_auth.c

Always initialize the auth_attribute.

---

library/spdm_responder_lib/encap_get_digests.c

Align encap_digest digest_count calculation.

---

unit_test/fuzzing/test_spdm_responder_algorithms/CMakeLists.txt
unit_test/fuzzing/test_spdm_responder_algorithms/algorithms.c
unit_test/fuzzing/test_spdm_responder_capabilities/CMakeLists.txt
unit_test/fuzzing/test_spdm_responder_capabilities/capabilities.c
unit_test/fuzzing/test_spdm_responder_get_capabilities/CMakeLists.txt
unit_test/fuzzing/test_spdm_responder_get_capabilities/get_capabilities.c

Add add algorithms.c get_capabilities.c and capabilities.c fuzzing test cases.

Add fuzz test case

---

os_stub/cryptlib_openssl/pk/dh.c

fix memory leak in dh_compute_key.

---

os_stub/cryptlib_openssl/pk/rsa_basic.c

fix memory leak in rsa_set_key.

---

library/spdm_common_lib/libspdm_com_context_data.c

Add appropriate assert for capabbility in spdm_set_data()

---

doc/test.md
unit_test/fuzzing/fuzzing.sh

Add fuzzing automation test script

Add fuzzing automation test script

---

README.md

Correct version info in readme.

---

unit_test/fuzzing/test_spdm_responder_challenge_auth/challenge_auth.c

Fix responder_challenge Fuzzing test ASSERT and hang

---

library/spdm_requester_lib/libspdm_req_get_capabilities.c
os_stub/cryptlib_mbedtls/sys_call/crt_wrapper_host.c
os_stub/cryptlib_mbedtls/sys_call/mem_allocation.c

Fixes https://github.com/DMTF/libspdm/issues/98

Remove or rename unwanted include files

---

unit_test/fuzzing/test_spdm_responder_algorithms/algorithms.c

Fix responder_algorithms Fuzzing test ASSERT and hang

---

unit_test/fuzzing/spdm_unit_fuzzing_common/spdm_unit_fuzzing.h
unit_test/fuzzing/spdm_unit_fuzzing_common/toolchain_harness.c
unit_test/fuzzing/test_spdm_requester_finish/CMakeLists.txt
unit_test/fuzzing/test_spdm_requester_finish/finish.c
unit_test/fuzzing/test_spdm_requester_get_measurements/CMakeLists.txt
unit_test/fuzzing/test_spdm_requester_get_measurements/get_measurements.c
unit_test/fuzzing/test_spdm_requester_psk_exchange/psk_exchange.c
unit_test/fuzzing/test_spdm_responder_algorithms/algorithms.c
unit_test/fuzzing/test_spdm_responder_encap_challenge/encap_challenge.c
unit_test/fuzzing/test_spdm_responder_encap_get_certificate/encap_get_certificate.c
unit_test/fuzzing/test_spdm_responder_encap_get_digests/encap_get_digests.c
unit_test/fuzzing/test_spdm_responder_encap_key_update/encap_key_update.c
unit_test/fuzzing/test_spdm_responder_finish_rsp/CMakeLists.txt
unit_test/fuzzing/test_spdm_responder_finish_rsp/finish_rsp.c
unit_test/fuzzing/test_spdm_responder_key_exchange/CMakeLists.txt
unit_test/fuzzing/test_spdm_responder_key_exchange/key_exchange.c
unit_test/fuzzing/test_spdm_responder_measurements/CMakeLists.txt
unit_test/fuzzing/test_spdm_responder_measurements/measurements.c
unit_test/fuzzing/test_spdm_responder_psk_exchange_rsp/psk_exchange_rsp.c
unit_test/fuzzing/test_spdm_responder_psk_finish_rsp/psk_finish_rsp.c

 Windows environment build error

---

include/library/spdm_crypt_lib.h
library/spdm_crypt_lib/libspdm_crypt_crypt.c
library/spdm_requester_lib/libspdm_req_challenge.c
library/spdm_requester_lib/libspdm_req_encap_challenge_auth.c
library/spdm_requester_lib/libspdm_req_get_measurements.c
library/spdm_requester_lib/libspdm_req_key_exchange.c
library/spdm_requester_lib/libspdm_req_key_update.c
library/spdm_requester_lib/libspdm_req_psk_exchange.c
library/spdm_responder_lib/libspdm_rsp_challenge_auth.c
library/spdm_responder_lib/libspdm_rsp_encap_challenge.c
library/spdm_responder_lib/libspdm_rsp_encap_key_update.c
library/spdm_responder_lib/libspdm_rsp_key_exchange.c
library/spdm_responder_lib/libspdm_rsp_measurements.c
library/spdm_responder_lib/libspdm_rsp_psk_exchange.c

Add check for return value of spdm_get_random_number().

---

library/spdm_secured_message_lib/libspdm_secmes_key_exchange.c

clean final_key after memcpy.

---

unit_test/fuzzing/test_spdm_requester_get_certificate/get_certificate.c

Fix build error

---

library/spdm_responder_lib/libspdm_rsp_encap_response.c

Fix unreachable code error introduced by new error handling. Fixes #386
Signed-off-by: Timothy <tandrewprinz@nvidia.com>

Fix VS2019 build error

---

doc/test.md

Fix #314
Signed-by: Jiewen Yao <jiewen.yao@intel.com>

Add document for spdm size collection.

---

library/spdm_requester_lib/libspdm_req_send_receive.c

return DecryptError ERROR response rather than generic error

---

.github/workflows/cmake.yml
README.md
library/spdm_responder_lib/libspdm_rsp_psk_exchange.c

Make the tab check consistent for *.c/*.h/*.md

---

library/spdm_requester_lib/libspdm_req_handle_error_response.c

handle reponse size error instead of ASSERT.

---

README.md

Fix: #370 
Update clang Linux build readme.md.
Update readme.md format.

Update clang Linux build readme.md

---

README.md

Upate README to fix windows clang build error

---

library/spdm_responder_lib/libspdm_rsp_receive_send.c

Fix https://github.com/DMTF/libspdm/issues/405

Add size check for non-APP message.

---

.github/workflows/cmake.yml

Add x64 openssl windows CI build test

---

include/hal/base.h
include/hal/library/cryptlib.h
os_stub/cryptlib_openssl/sys_call/crt_wrapper_host.c
os_stub/openssllib/ossl_store.c
os_stub/openssllib/rand_pool.c
unit_test/test_crypt/test_crypt.c
unit_test/test_crypt/test_crypt.h
unit_test/test_crypt/x509_verify.c
unit_test/test_spdm_responder/respond_if_ready.c

Clean up UEFI keyword.

---

include/library/spdm_requester_lib.h
library/spdm_requester_lib/libspdm_req_challenge.c
library/spdm_responder_lib/libspdm_rsp_encap_challenge.c
unit_test/fuzzing/test_requester/test_spdm_requester_challenge/challenge.c
unit_test/test_size/test_size_of_spdm_requester/spdm_requester_authentication.c
unit_test/test_spdm_requester/challenge.c

Add slot_mask in libspdm_challenge

---

include/industry_standard/spdm.h
include/library/spdm_lib_config.h
library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_requester_lib/libspdm_req_get_version.c
unit_test/test_spdm_requester/get_version.c
unit_test/test_spdm_responder/version.c

Move SPDM_MAX_VERSION_COUNT to config.h

---

library/spdm_transport_mctp_lib/libspdm_mctp_common.c
library/spdm_transport_pcidoe_lib/libspdm_doe_common.c
unit_test/spdm_transport_test_lib/common.c

fix coding style issue.

---

unit_test/fuzzing/test_requester/test_spdm_requester_challenge/challenge.c
unit_test/fuzzing/test_requester/test_spdm_requester_end_session/end_session.c
unit_test/fuzzing/test_requester/test_spdm_requester_finish/finish.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_capabilities/get_capabilities.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_certificate/get_certificate.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_digests/get_digests.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_measurements/get_measurements.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_version/get_version.c
unit_test/fuzzing/test_requester/test_spdm_requester_heartbeat/heartbeat.c
unit_test/fuzzing/test_requester/test_spdm_requester_key_exchange/key_exchange.c
unit_test/fuzzing/test_requester/test_spdm_requester_key_update/key_update.c
unit_test/fuzzing/test_requester/test_spdm_requester_negotiate_algorithms/negotiate_algorithms.c
unit_test/fuzzing/test_requester/test_spdm_requester_psk_exchange/psk_exchange.c
unit_test/fuzzing/test_requester/test_spdm_requester_psk_finish/psk_finish.c
unit_test/fuzzing/test_responder/test_spdm_responder_algorithms/algorithms.c
unit_test/fuzzing/test_responder/test_spdm_responder_capabilities/capabilities.c
unit_test/fuzzing/test_responder/test_spdm_responder_certificate/certificate.c
unit_test/fuzzing/test_responder/test_spdm_responder_challenge_auth/challenge_auth.c
unit_test/fuzzing/test_responder/test_spdm_responder_digests/digests.c
unit_test/fuzzing/test_responder/test_spdm_responder_end_session/end_session.c
unit_test/fuzzing/test_responder/test_spdm_responder_finish_rsp/finish_rsp.c
unit_test/fuzzing/test_responder/test_spdm_responder_heartbeat_ack/heartbeat_ack.c
unit_test/fuzzing/test_responder/test_spdm_responder_if_ready/respond_if_ready.c
unit_test/fuzzing/test_responder/test_spdm_responder_key_exchange/key_exchange.c
unit_test/fuzzing/test_responder/test_spdm_responder_key_update/key_update.c
unit_test/fuzzing/test_responder/test_spdm_responder_measurements/measurements.c
unit_test/fuzzing/test_responder/test_spdm_responder_psk_exchange_rsp/psk_exchange_rsp.c
unit_test/fuzzing/test_responder/test_spdm_responder_psk_finish_rsp/psk_finish_rsp.c
unit_test/fuzzing/test_responder/test_spdm_responder_version/version.c

Add scenario description for fuzzy test case

---

include/internal/libspdm_responder_lib.h
library/spdm_responder_lib/libspdm_rsp_challenge_auth.c
library/spdm_responder_lib/libspdm_rsp_encap_response.c

Clean up unused function parameters.

---

library/spdm_common_lib/libspdm_com_crypto_service.c
unit_test/test_spdm_requester/get_digests.c
unit_test/test_spdm_requester/get_measurements.c
unit_test/test_spdm_responder/digests.c
unit_test/test_spdm_responder/measurements.c

Fix: https://github.com/DMTF/libspdm/issues/461

Fix build failure with LIBSPDM_RECORD_TRANSCRIPT_DATA_SUPPORT 1

---

doc/user_guide.md

Rename the "spdm" to "libspdm" in user_guide.md

---

doc/test.md
unit_test/fuzzing/fuzzing_AFL.sh
unit_test/fuzzing/fuzzing_LibFuzzer.sh

Add the fuzzing automation test script for libfuzzer.
Fix: #445

Add the fuzzing automation test script for libfuzzer.

---

library/spdm_requester_lib/libspdm_req_end_session.c
library/spdm_requester_lib/libspdm_req_finish.c
library/spdm_requester_lib/libspdm_req_get_capabilities.c
library/spdm_requester_lib/libspdm_req_get_certificate.c
library/spdm_requester_lib/libspdm_req_get_digests.c
library/spdm_requester_lib/libspdm_req_get_measurements.c
library/spdm_requester_lib/libspdm_req_heartbeat.c
library/spdm_requester_lib/libspdm_req_key_exchange.c
library/spdm_requester_lib/libspdm_req_key_update.c
library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c
library/spdm_requester_lib/libspdm_req_psk_exchange.c
library/spdm_requester_lib/libspdm_req_psk_finish.c
unit_test/test_spdm_requester/end_session.c
unit_test/test_spdm_requester/finish.c
unit_test/test_spdm_requester/get_certificate.c
unit_test/test_spdm_requester/get_digests.c
unit_test/test_spdm_requester/get_measurements.c
unit_test/test_spdm_requester/heartbeat.c
unit_test/test_spdm_requester/key_exchange.c
unit_test/test_spdm_requester/key_update.c
unit_test/test_spdm_requester/psk_exchange.c
unit_test/test_spdm_requester/psk_finish.c

Add check the SPDMVersion filed of response message

---

library/spdm_crypt_lib/libspdm_crypt_crypt.c

Fix https://github.com/DMTF/libspdm/issues/470

Fix wrong return status.

---

README.md

Update readme for latest 1.2 status.

---

include/internal/libspdm_common_lib.h
include/library/spdm_responder_lib.h
library/spdm_responder_lib/libspdm_rsp_communication.c

optimize stack in the responder dispatch code path.

---

include/industry_standard/pci_idekm.h
include/industry_standard/pcidoe.h
include/industry_standard/pldm.h

clean up DOE and MCTP header file definition

---

library/spdm_requester_lib/libspdm_req_get_certificate.c

Fix: #478 
Add total cert chain buffer length check and add remainder length check.

Add check for try_spdm_get_certificate to make sure get cert correctly

---

library/spdm_responder_lib/libspdm_rsp_digests.c
unit_test/test_spdm_responder/digests.c

Fixes https://github.com/DMTF/libspdm/issues/95

Change error code from unsupported to unspecified

---

include/industry_standard/pcidoe.h

Refine the pci_vendor_defined_struct to avoid duplication.

---

library/spdm_requester_lib/libspdm_req_encap_certificate.c
library/spdm_requester_lib/libspdm_req_encap_challenge_auth.c
library/spdm_requester_lib/libspdm_req_encap_digests.c
library/spdm_requester_lib/libspdm_req_encap_key_update.c
library/spdm_responder_lib/libspdm_rsp_algorithms.c
library/spdm_responder_lib/libspdm_rsp_certificate.c
library/spdm_responder_lib/libspdm_rsp_challenge_auth.c
library/spdm_responder_lib/libspdm_rsp_digests.c
library/spdm_responder_lib/libspdm_rsp_end_session.c
library/spdm_responder_lib/libspdm_rsp_finish.c
library/spdm_responder_lib/libspdm_rsp_heartbeat.c
library/spdm_responder_lib/libspdm_rsp_key_exchange.c
library/spdm_responder_lib/libspdm_rsp_key_update.c
library/spdm_responder_lib/libspdm_rsp_measurements.c
library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
library/spdm_responder_lib/libspdm_rsp_psk_finish.c
library/spdm_responder_lib/libspdm_rsp_respond_if_ready.c

Update the error code for messages with mismatched version

---

unit_test/test_spdm_requester/get_certificate.c

Add GET_CERTIFIACATE unit tests to cover wrong CERTIFICATE response

---

include/internal/libspdm_common_lib.h
library/spdm_responder_lib/libspdm_rsp_encap_get_certificate.c

Add encap get cert check to avoid infinite loop

---

library/spdm_requester_lib/libspdm_req_challenge.c
library/spdm_requester_lib/libspdm_req_get_certificate.c
library/spdm_requester_lib/libspdm_req_key_exchange.c
unit_test/test_spdm_requester/challenge.c

Fixes https://github.com/DMTF/libspdm/issues/493

Change runtime checks to asserts

---

library/spdm_requester_lib/libspdm_req_finish.c
library/spdm_requester_lib/libspdm_req_key_exchange.c
library/spdm_requester_lib/libspdm_req_psk_exchange.c
library/spdm_requester_lib/libspdm_req_psk_finish.c

Fix: #476
1) free session_id
2) free dhe_context if key is not established
3) zero negotiated keys

Free session_ID, dhe_context and keys for: key exchange and finish

---

library/spdm_common_lib/libspdm_com_opaque_data.c

Fix the spdm_process_opaque_data_version_selection_data() logic error

---

include/industry_standard/spdm.h
library/spdm_common_lib/libspdm_com_opaque_data.c

Define spdm_general_opaque_data_table_header_t correctly

---

doc/test.md
unit_test/fuzzing/oss-fuzz_conf/Dockerfile
unit_test/fuzzing/oss-fuzz_conf/build.sh
unit_test/fuzzing/oss-fuzz_conf/project.yaml
unit_test/fuzzing/oss_fuzz.sh

Enable fuzzing in Linux with OSS-Fuzz locally

---

unit_test/test_spdm_requester/key_exchange.c
unit_test/test_spdm_responder/key_exchange.c

fix build issue with new test cases.

---

include/hal/aarch64/processor_bind.h

Fix #584
Signed-off-by: Alok Prasad <alok.prasad7@gmail.com>

fix compilation on aarch64 with clang

---

library/spdm_responder_lib/libspdm_rsp_capabilities.c

Fix error code version mismatch in capabilities_rsp.

---

library/spdm_crypt_lib/libspdm_crypt_crypt.c

It is to fix SPDM 1.2 assert issue.

Need pass thru the non-1.2 new algorithm.

---

unit_test/fuzzing/test_requester/test_spdm_requester_challenge/challenge.c
unit_test/fuzzing/test_requester/test_spdm_requester_encap_certificate/encap_certificate.c
unit_test/fuzzing/test_requester/test_spdm_requester_encap_challenge_auth/encap_challenge_auth.c
unit_test/fuzzing/test_requester/test_spdm_requester_encap_digests/encap_digests.c
unit_test/fuzzing/test_requester/test_spdm_requester_encap_request/encap_request.c
unit_test/fuzzing/test_requester/test_spdm_requester_finish/finish.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_certificate/get_certificate.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_digests/get_digests.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_measurements/get_measurements.c
unit_test/fuzzing/test_requester/test_spdm_requester_key_exchange/key_exchange.c
unit_test/fuzzing/test_requester/test_spdm_requester_psk_exchange/psk_exchange.c
unit_test/fuzzing/test_requester/test_spdm_requester_psk_finish/psk_finish.c
unit_test/fuzzing/test_responder/test_spdm_responder_certificate/certificate.c
unit_test/fuzzing/test_responder/test_spdm_responder_challenge_auth/challenge_auth.c
unit_test/fuzzing/test_responder/test_spdm_responder_digests/digests.c
unit_test/fuzzing/test_responder/test_spdm_responder_encap_challenge/encap_challenge.c
unit_test/fuzzing/test_responder/test_spdm_responder_encap_get_certificate/encap_get_certificate.c
unit_test/fuzzing/test_responder/test_spdm_responder_encap_get_digests/encap_get_digests.c
unit_test/fuzzing/test_responder/test_spdm_responder_encap_response/encap_response.c
unit_test/fuzzing/test_responder/test_spdm_responder_finish_rsp/finish_rsp.c
unit_test/fuzzing/test_responder/test_spdm_responder_key_exchange/key_exchange.c
unit_test/fuzzing/test_responder/test_spdm_responder_measurements/measurements.c
unit_test/fuzzing/test_responder/test_spdm_responder_psk_exchange_rsp/psk_exchange_rsp.c
unit_test/test_spdm_responder/respond_if_ready.c
unit_test/test_spdm_responder/test_spdm_responder.c

Fix LIBSPDM_ENABLE_CAPABILITY_*_CAP changes, then build fails

---

library/spdm_responder_lib/libspdm_rsp_receive_send.c

correct session id for watchdog.

---

include/internal/libspdm_requester_lib.h
library/spdm_requester_lib/libspdm_req_end_session.c
library/spdm_requester_lib/libspdm_req_handle_error_response.c
library/spdm_requester_lib/libspdm_req_heartbeat.c
library/spdm_requester_lib/libspdm_req_key_update.c

Add a generic place to handle SPDM_ERROR_CODE_DECRYPT_ERROR

---

include/hal/library/memlib.h
os_stub/memlib/copy_mem.c

Zero copy_mem_s dst_buf on some errors. Fix copy_mem return value bug..

---

unit_test/fuzzing/spdm_unit_fuzzing_common/toolchain_harness.c
unit_test/fuzzing/test_requester/test_spdm_requester_challenge/challenge.c
unit_test/fuzzing/test_requester/test_spdm_requester_encap_key_update/encap_key_update.c
unit_test/fuzzing/test_requester/test_spdm_requester_encap_request/encap_request.c
unit_test/fuzzing/test_requester/test_spdm_requester_end_session/end_session.c
unit_test/fuzzing/test_requester/test_spdm_requester_finish/finish.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_capabilities/get_capabilities.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_certificate/get_certificate.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_digests/get_digests.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_measurements/get_measurements.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_version/get_version.c
unit_test/fuzzing/test_requester/test_spdm_requester_heartbeat/heartbeat.c
unit_test/fuzzing/test_requester/test_spdm_requester_key_exchange/key_exchange.c
unit_test/fuzzing/test_requester/test_spdm_requester_key_update/key_update.c
unit_test/fuzzing/test_requester/test_spdm_requester_negotiate_algorithms/negotiate_algorithms.c
unit_test/fuzzing/test_requester/test_spdm_requester_psk_exchange/psk_exchange.c
unit_test/fuzzing/test_requester/test_spdm_requester_psk_finish/psk_finish.c
unit_test/fuzzing/test_responder/test_spdm_responder_encap_challenge/encap_challenge.c
unit_test/fuzzing/test_responder/test_spdm_responder_encap_key_update/encap_key_update.c
unit_test/fuzzing/test_responder/test_spdm_responder_end_session/end_session.c
unit_test/fuzzing/test_responder/test_spdm_responder_finish_rsp/finish_rsp.c
unit_test/fuzzing/test_responder/test_spdm_responder_heartbeat_ack/heartbeat_ack.c
unit_test/fuzzing/test_responder/test_spdm_responder_if_ready/respond_if_ready.c
unit_test/fuzzing/test_responder/test_spdm_responder_key_update/key_update.c
unit_test/fuzzing/test_responder/test_spdm_responder_measurements/measurements.c
unit_test/fuzzing/test_responder/test_spdm_responder_psk_exchange_rsp/psk_exchange_rsp.c
unit_test/fuzzing/test_responder/test_spdm_responder_psk_finish_rsp/psk_finish_rsp.c

Move all of unit_test/fuzzing to use copy_mem_s

Use copy_mem_s in unit_test/fuzzing

---

unit_test/test_spdm_requester/challenge.c
unit_test/test_spdm_requester/end_session.c
unit_test/test_spdm_requester/finish.c

Convert these files to copy_mem_s:
unit_test/test_spdm_requester/challenge.c
unit_test/test_spdm_requester/end_session.c
unit_test/test_spdm_requester/finish.c

copy_mem_s changes in unit_test/requester (challenge/end_session/finish)

---

unit_test/test_spdm_requester/get_certificate.c
unit_test/test_spdm_requester/get_measurements.c
unit_test/test_spdm_requester/heartbeat.c

copy_mem_s changes to these files:
unit_test/test_spdm_requester/get_certificate.c
unit_test/test_spdm_requester/get_measurements.c
unit_test/test_spdm_requester/heartbeat.c

copy_mem_s changes to unit_test/test_spdm_requester

---

unit_test/test_spdm_requester/psk_exchange.c
unit_test/test_spdm_requester/psk_finish.c

Use copy_mem_s in these files:
unit_test/test_spdm_requester/psk_exchange.c
unit_test/test_spdm_requester/psk_finish.c

Use copy_mem_s in unit_test/requester (psk_exchange/psk_finish)

---

unit_test/test_spdm_requester/key_exchange.c
unit_test/test_spdm_requester/key_update.c

Use copy_mem_s in following files:
unit_test/test_spdm_requester/key_exchange.c
unit_test/test_spdm_requester/key_update.c

Use copy_mem_s in unit_test/test_spdm_requester (key_exchange/key_update)

---

doc/design.md

Document platform_lib usage.

---

unit_test/fuzzing/spdm_unit_fuzzing_common/toolchain_harness.c
unit_test/fuzzing/spdm_unit_fuzzing_common/toolchain_harness.h

Update toolchain_harness to add AlignmentSize for libFuzzer like AFL.

---

os_stub/cryptlib_mbedtls/pk/dh.c
os_stub/cryptlib_mbedtls/pk/x509.c
os_stub/cryptlib_openssl/pk/x509.c

Use copy_mem_s in these files:
os_stub/cryptlib_mbedtls/pk/dh.c
os_stub/cryptlib_mbedtls/pk/x509.c
os_stub/cryptlib_openssl/pk/x509.c

Use copy_mem_s in os_stub part 2.

---

unit_test/fuzzing/test_requester/test_spdm_requester_psk_finish/psk_finish.c

Fix the test case issue for test_spdm_requester_psk_finish.

---

unit_test/test_spdm_requester/challenge.c
unit_test/test_spdm_requester/get_measurements.c
unit_test/test_spdm_requester/heartbeat.c
unit_test/test_spdm_requester/key_exchange.c
unit_test/test_spdm_requester/psk_exchange.c
unit_test/test_spdm_requester/psk_finish.c
unit_test/test_spdm_responder/respond_if_ready.c

Use copy_mem_s in unit_test missed in earlier commits.

---

include/internal/libspdm_responder_lib.h
include/library/spdm_common_lib.h
include/library/spdm_crypt_lib.h
include/library/spdm_device_secret_lib.h
include/library/spdm_responder_lib.h
include/library/spdm_secured_message_lib.h
library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_crypt_lib/libspdm_crypt_crypt.c
library/spdm_responder_lib/libspdm_rsp_receive_send.c
library/spdm_secured_message_lib/libspdm_secmes_context_data.c
library/spdm_secured_message_lib/libspdm_secmes_key_exchange.c
library/spdm_secured_message_lib/libspdm_secmes_session.c
os_stub/spdm_device_secret_lib_null/lib.c
os_stub/spdm_device_secret_lib_sample/lib.c

remove const for some types.

---

include/library/spdm_common_lib.h
include/library/spdm_transport_mctp_lib.h
include/library/spdm_transport_pcidoe_lib.h
library/spdm_transport_mctp_lib/libspdm_mctp_common.c
library/spdm_transport_pcidoe_lib/libspdm_doe_common.c

remove const for more types.

---

library/spdm_requester_lib/libspdm_req_send_receive.c
library/spdm_responder_lib/libspdm_rsp_receive_send.c

handle data_transfer_size

---

unit_test/fuzzing/test_requester/test_spdm_requester_challenge/challenge.c
unit_test/fuzzing/test_requester/test_spdm_requester_finish/finish.c
unit_test/fuzzing/test_requester/test_spdm_requester_key_exchange/key_exchange.c

assert and hang with the initial seed

---

unit_test/fuzzing/test_requester/test_spdm_requester_challenge/challenge.c
unit_test/fuzzing/test_requester/test_spdm_requester_encap_challenge_auth/encap_challenge_auth.c
unit_test/fuzzing/test_requester/test_spdm_requester_finish/finish.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_certificate/get_certificate.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_digests/get_digests.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_measurements/get_measurements.c
unit_test/fuzzing/test_requester/test_spdm_requester_key_exchange/key_exchange.c
unit_test/fuzzing/test_requester/test_spdm_requester_psk_finish/psk_finish.c

fix test_requester test case memory leaks problem

---

os_stub/cryptlib_mbedtls/internal_crypt_lib.h
os_stub/cryptlib_mbedtls/pk/dh.c
os_stub/cryptlib_mbedtls/pk/ec.c
os_stub/cryptlib_mbedtls/pk/rsa_ext.c
os_stub/cryptlib_mbedtls/pk/x509.c
os_stub/cryptlib_mbedtls/rand/rand.c
os_stub/cryptlib_null/rand/rand.c
os_stub/cryptlib_openssl/pk/x509.c
os_stub/cryptlib_openssl/rand/rand.c
os_stub/include/library/rnglib.h
os_stub/openssllib/rand_pool.c
os_stub/rnglib/rng_linux.c
os_stub/rnglib/rng_std.c
os_stub/rnglib/rng_win.c
unit_test/test_size/rnglib_null/rnglib.c

add libspdm_ for any external symbol or MACRO.

---

library/spdm_responder_lib/libspdm_rsp_end_session.c
library/spdm_responder_lib/libspdm_rsp_finish.c
library/spdm_responder_lib/libspdm_rsp_heartbeat.c
library/spdm_responder_lib/libspdm_rsp_key_update.c
library/spdm_responder_lib/libspdm_rsp_psk_finish.c
unit_test/test_spdm_responder/finish.c
unit_test/test_spdm_responder/key_update.c
unit_test/test_spdm_responder/psk_finish.c

if connection or session state check fails.
Fix: #686 

Need return SPDM_ERROR_CODE_UNEXPECTED_REQUEST

---

library/spdm_responder_lib/libspdm_rsp_challenge_auth.c
library/spdm_responder_lib/libspdm_rsp_key_exchange.c
library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
unit_test/test_spdm_responder/challenge_auth.c
unit_test/test_spdm_responder/key_exchange.c

misuse of SPDM_ERROR_CODE_UNSUPPORTED_REQUEST.

---

unit_test/test_spdm_requester/CMakeLists.txt
unit_test/test_spdm_requester/encap_certificate.c
unit_test/test_spdm_requester/encap_challenge_auth.c
unit_test/test_spdm_requester/encap_digests.c
unit_test/test_spdm_requester/encap_key_update.c
unit_test/test_spdm_requester/test_spdm_requester.c
unit_test/test_spdm_responder/CMakeLists.txt
unit_test/test_spdm_responder/encap_get_certificate.c
unit_test/test_spdm_responder/test_spdm_responder.c

Fix : #325
Add encapsulated related unit test:
encap_digests
encap_challenge_auth
encap_certificate
encap_key_update
encap_get_certificate

add encapsulated related unit test.

---

unit_test/test_spdm_requester/encap_certificate.c

Change the asym_algo for long_chains cert

---

library/spdm_common_lib/libspdm_com_context_data.c

remove const from ibspdm_register_transport_layer_func

---

include/library/spdm_responder_lib.h

remove const for libspdm_register_get_response_func.

---

unit_test/fuzzing/test_responder/test_spdm_responder_finish_rsp/finish_rsp.c
unit_test/fuzzing/test_responder/test_spdm_responder_if_ready/respond_if_ready.c
unit_test/fuzzing/test_responder/test_spdm_responder_key_exchange/key_exchange.c
unit_test/fuzzing/test_responder/test_spdm_responder_psk_exchange_rsp/psk_exchange_rsp.c
unit_test/fuzzing/test_responder/test_spdm_responder_psk_finish_rsp/psk_finish_rsp.c

Convert spdm_context local variables to pointers, and fix memory leaks

---

unit_test/fuzzing/fuzzing_LibFuzzer.sh

Add Summary information for Libfuzzer fuzzing out.
fix : #718
Signed-off-by: yaohuixguo <yaohuix.guo@intel.com>

Add Summary information for Libfuzzer fuzzing out.

---

include/library/spdm_return_status.h
library/spdm_requester_lib/libspdm_req_get_capabilities.c
library/spdm_requester_lib/libspdm_req_get_version.c
library/spdm_requester_lib/libspdm_req_handle_error_response.c
unit_test/test_spdm_requester/challenge.c
unit_test/test_spdm_requester/end_session.c
unit_test/test_spdm_requester/finish.c
unit_test/test_spdm_requester/get_capabilities.c
unit_test/test_spdm_requester/get_certificate.c
unit_test/test_spdm_requester/get_digests.c
unit_test/test_spdm_requester/get_measurements.c
unit_test/test_spdm_requester/get_version.c
unit_test/test_spdm_requester/heartbeat.c
unit_test/test_spdm_requester/key_exchange.c
unit_test/test_spdm_requester/key_update.c
unit_test/test_spdm_requester/negotiate_algorithms.c
unit_test/test_spdm_requester/psk_exchange.c
unit_test/test_spdm_requester/psk_finish.c

Still need to update unit tests 30 and 31.

Initial commit for new error codes for GET_CAPABILITIES

---

unit_test/fuzzing/spdm_unit_fuzzing_common/toolchain_harness.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_digests/get_digests.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_version/get_version.c

2.Correct some typo.
fix: #740
fix: #746

1.Considering the size of mutation seed reach to max_buffer_size.

---

include/library/spdm_return_status.h
library/spdm_common_lib/libspdm_com_crypto_service.c
library/spdm_requester_lib/libspdm_req_get_digests.c
library/spdm_requester_lib/libspdm_req_get_version.c
unit_test/test_spdm_requester/get_digests.c

Initial commit for new error codes for GET_DIGESTS

---

include/hal/aarch64/processor_bind.h
include/hal/arc/processor_bind.h
include/hal/arm/processor_bind.h
include/hal/base.h
include/hal/ia32/processor_bind.h
include/hal/library/cryptlib.h
include/hal/library/memlib.h
include/hal/nios2/processor_bind.h
include/hal/riscv32/processor_bind.h
include/hal/riscv64/processor_bind.h
include/hal/x64/processor_bind.h
include/internal/libspdm_common_lib.h
include/library/spdm_crypt_lib.h
library/spdm_common_lib/libspdm_com_crypto_service_session.c
library/spdm_crypt_lib/libspdm_crypt_crypt.c
os_stub/cryptlib_mbedtls/pk/x509.c
os_stub/cryptlib_null/pk/x509.c
os_stub/cryptlib_openssl/pem/pem.c
os_stub/cryptlib_openssl/pk/dh.c
os_stub/cryptlib_openssl/pk/ec.c
os_stub/cryptlib_openssl/pk/sm2.c
os_stub/cryptlib_openssl/pk/x509.c
os_stub/debuglib/debuglib.c
os_stub/memlib/compare_mem.c
os_stub/openssllib/include/crt_support.h
os_stub/openssllib/include/openssl/opensslconf.h
unit_test/test_size/cryptstublib_dummy/timeclock_dummy.c
unit_test/test_size/intrinsiclib/memory_intrinsics.c

REF: https://github.com/DMTF/libspdm/issues/63
signed-off-by: Jiewen Yao <jiewen.yao@intel.com>

remove intn.

---

unit_test/fuzzing/spdm_unit_fuzzing_common/toolchain_harness.c
unit_test/fuzzing/spdm_unit_fuzzing_common/toolchain_harness.h
unit_test/fuzzing/test_requester/test_spdm_requester_challenge/challenge.c
unit_test/fuzzing/test_requester/test_spdm_requester_encap_certificate/encap_certificate.c
unit_test/fuzzing/test_requester/test_spdm_requester_encap_challenge_auth/encap_challenge_auth.c
unit_test/fuzzing/test_requester/test_spdm_requester_encap_digests/encap_digests.c
unit_test/fuzzing/test_requester/test_spdm_requester_encap_key_update/encap_key_update.c
unit_test/fuzzing/test_requester/test_spdm_requester_encap_request/encap_request.c
unit_test/fuzzing/test_requester/test_spdm_requester_end_session/end_session.c
unit_test/fuzzing/test_requester/test_spdm_requester_finish/finish.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_capabilities/get_capabilities.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_certificate/get_certificate.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_digests/get_digests.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_measurements/get_measurements.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_version/get_version.c
unit_test/fuzzing/test_requester/test_spdm_requester_heartbeat/heartbeat.c
unit_test/fuzzing/test_requester/test_spdm_requester_key_exchange/key_exchange.c
unit_test/fuzzing/test_requester/test_spdm_requester_key_update/key_update.c
unit_test/fuzzing/test_requester/test_spdm_requester_negotiate_algorithms/negotiate_algorithms.c
unit_test/fuzzing/test_requester/test_spdm_requester_psk_exchange/psk_exchange.c
unit_test/fuzzing/test_requester/test_spdm_requester_psk_finish/psk_finish.c
unit_test/fuzzing/test_secured_message/test_spdm_decode_secured_message/spdm_decode_secured_message.c
unit_test/fuzzing/test_secured_message/test_spdm_encode_secured_message/spdm_encode_secured_message.c
unit_test/fuzzing/test_transport/test_spdm_transport_mctp_decode_message/spdm_transport_mctp_decode_message.c
unit_test/fuzzing/test_transport/test_spdm_transport_mctp_encode_message/transport_mctp_encode_message.c
unit_test/fuzzing/test_transport/test_spdm_transport_pci_doe_decode_message/spdm_transport_pci_doe_decode_message.c
unit_test/fuzzing/test_transport/test_spdm_transport_pci_doe_encode_message/spdm_transport_pci_doe_encode_message.c

Fix fuzzing case for io redesign.

---

include/library/spdm_return_status.h
library/spdm_requester_lib/libspdm_req_get_certificate.c
unit_test/test_spdm_requester/get_certificate.c

Initial commit for new GET_CERTIFICATE error codes

---

library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c

Fix https://github.com/DMTF/libspdm/issues/729

fix the extended algo check.

---

library/spdm_requester_lib/libspdm_req_get_certificate.c

Fix: https://github.com/DMTF/libspdm/issues/768

Fix uninitialized data warning.

---

library/spdm_common_lib/libspdm_com_crypto_service.c

Fix https://github.com/DMTF/libspdm/issues/769

Fix potential NULL ptr dereference.

---

unit_test/fuzzing/test_responder/test_spdm_responder_encap_challenge/encap_challenge.c

Fix: https://github.com/DMTF/libspdm/issues/770

Remove unnecessary malloc

---

include/library/spdm_device_secret_lib.h
include/library/spdm_return_status.h
include/library/spdm_secured_message_lib.h
library/spdm_responder_lib/libspdm_rsp_measurements.c
os_stub/spdm_device_secret_lib_null/lib.c
os_stub/spdm_device_secret_lib_sample/lib.c

remove return_status from device_secret_lib.

---

include/library/spdm_common_lib.h
include/library/spdm_return_status.h
include/library/spdm_secured_message_lib.h
library/spdm_requester_lib/libspdm_req_encap_key_update.c
library/spdm_requester_lib/libspdm_req_finish.c
library/spdm_requester_lib/libspdm_req_key_exchange.c
library/spdm_requester_lib/libspdm_req_key_update.c
library/spdm_requester_lib/libspdm_req_psk_exchange.c
library/spdm_requester_lib/libspdm_req_psk_finish.c
library/spdm_responder_lib/libspdm_rsp_encap_key_update.c
library/spdm_responder_lib/libspdm_rsp_finish.c
library/spdm_responder_lib/libspdm_rsp_key_exchange.c
library/spdm_responder_lib/libspdm_rsp_key_update.c
library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
library/spdm_responder_lib/libspdm_rsp_psk_finish.c
library/spdm_secured_message_lib/libspdm_secmes_context_data.c
library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c
library/spdm_secured_message_lib/libspdm_secmes_session.c

remove return_status from secure_message_lib.

---

include/library/spdm_transport_mctp_lib.h
include/library/spdm_transport_pcidoe_lib.h
library/spdm_transport_mctp_lib/libspdm_mctp_common.c
library/spdm_transport_mctp_lib/libspdm_mctp_mctp.c
library/spdm_transport_pcidoe_lib/libspdm_doe_common.c
library/spdm_transport_pcidoe_lib/libspdm_doe_pcidoe.c
unit_test/include/library/spdm_transport_test_lib.h
unit_test/spdm_transport_test_lib/common.c
unit_test/spdm_transport_test_lib/test.c
unit_test/test_spdm_requester/key_update.c

remove return_status from transport_lib.

---

include/internal/libspdm_requester_lib.h
include/library/spdm_requester_lib.h
library/spdm_requester_lib/libspdm_req_challenge.c
library/spdm_requester_lib/libspdm_req_communication.c
library/spdm_requester_lib/libspdm_req_encap_request.c
library/spdm_requester_lib/libspdm_req_end_session.c
library/spdm_requester_lib/libspdm_req_finish.c
library/spdm_requester_lib/libspdm_req_get_certificate.c
library/spdm_requester_lib/libspdm_req_get_digests.c
library/spdm_requester_lib/libspdm_req_get_measurements.c
library/spdm_requester_lib/libspdm_req_handle_error_response.c
library/spdm_requester_lib/libspdm_req_heartbeat.c
library/spdm_requester_lib/libspdm_req_key_exchange.c
library/spdm_requester_lib/libspdm_req_key_update.c
library/spdm_requester_lib/libspdm_req_psk_exchange.c
library/spdm_requester_lib/libspdm_req_psk_finish.c
library/spdm_requester_lib/libspdm_req_send_receive.c
unit_test/test_spdm_requester/challenge.c
unit_test/test_spdm_requester/encap_request.c
unit_test/test_spdm_requester/end_session.c
unit_test/test_spdm_requester/finish.c
unit_test/test_spdm_requester/get_measurements.c
unit_test/test_spdm_requester/heartbeat.c
unit_test/test_spdm_requester/key_exchange.c
unit_test/test_spdm_requester/key_update.c
unit_test/test_spdm_requester/psk_exchange.c
unit_test/test_spdm_requester/psk_finish.c

cleanup for requester_lib

---

include/internal/libspdm_requester_lib.h
include/library/spdm_requester_lib.h
library/spdm_requester_lib/libspdm_req_challenge.c
library/spdm_requester_lib/libspdm_req_encap_certificate.c
library/spdm_requester_lib/libspdm_req_encap_challenge_auth.c
library/spdm_requester_lib/libspdm_req_encap_digests.c
library/spdm_requester_lib/libspdm_req_encap_error.c
library/spdm_requester_lib/libspdm_req_encap_key_update.c
library/spdm_requester_lib/libspdm_req_encap_request.c
library/spdm_requester_lib/libspdm_req_get_measurements.c
unit_test/test_spdm_requester/challenge.c
unit_test/test_spdm_requester/encap_certificate.c
unit_test/test_spdm_requester/encap_challenge_auth.c
unit_test/test_spdm_requester/encap_digests.c
unit_test/test_spdm_requester/encap_key_update.c
unit_test/test_spdm_requester/encap_request.c
unit_test/test_spdm_requester/get_measurements.c

clean up requester_lib

---

library/spdm_common_lib/libspdm_com_context_data.c

internally check return value in libspdm_append_message_f ().

---

include/hal/library/debuglib.h

FIX: https://github.com/DMTF/libspdm/issues/393

remove ASSERT_RETURN_ERROR.

---

library/spdm_requester_lib/libspdm_req_send_receive.c

remove unnecessary assert.

---

include/industry_standard/spdm.h
include/library/spdm_secured_message_lib.h
library/spdm_secured_message_lib/libspdm_secmes_session.c
unit_test/fuzzing/test_requester/test_spdm_requester_encap_key_update/encap_key_update.c
unit_test/fuzzing/test_requester/test_spdm_requester_key_exchange/key_exchange.c
unit_test/fuzzing/test_requester/test_spdm_requester_key_update/key_update.c
unit_test/fuzzing/test_requester/test_spdm_requester_psk_exchange/psk_exchange.c
unit_test/fuzzing/test_responder/test_spdm_responder_encap_key_update/encap_key_update.c
unit_test/fuzzing/test_responder/test_spdm_responder_key_update/key_update.c
unit_test/test_spdm_requester/encap_key_update.c
unit_test/test_spdm_requester/key_exchange.c
unit_test/test_spdm_requester/key_update.c
unit_test/test_spdm_requester/psk_exchange.c
unit_test/test_spdm_responder/key_update.c

Fix: https://github.com/DMTF/libspdm/issues/798

Fix bin concat string for 1.2.

---

os_stub/cryptlib_openssl/pk/x509.c

Fix: https://github.com/DMTF/libspdm/issues/800
Fix: https://github.com/DMTF/libspdm/issues/802

Fix data uninitialized.

---

include/internal/libspdm_common_lib.h
include/library/spdm_lib_config.h

Expose LIBSPDM_SCRATCH_BUFFER_SIZE.

---

include/library/spdm_crypt_lib.h
include/library/spdm_device_secret_lib.h

correct path of spdm_lib_config.h in spdm_crypt_lib.h.

---

doc/design.md
doc/user_guide.md
include/library/spdm_lib_config.h

Fix: https://github.com/DMTF/libspdm/issues/799

Update readme for io buffer redesign.

---

library/spdm_common_lib/libspdm_com_context_data.c

Fix: https://github.com/DMTF/libspdm/issues/783

Add VCA for 1.2 basic mut auth transcript.

---

doc/design.md
include/library/spdm_secured_message_lib.h
library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c

Fix: https://github.com/DMTF/libspdm/issues/797

add more description on secure message encode/decode.

---

unit_test/test_spdm_requester/get_capabilities.c
unit_test/test_spdm_requester/get_measurements.c
unit_test/test_spdm_requester/key_exchange.c
unit_test/test_spdm_requester/negotiate_algorithms.c
unit_test/test_spdm_requester/psk_exchange.c
unit_test/test_spdm_responder/CMakeLists.txt
unit_test/test_spdm_responder/algorithms.c
unit_test/test_spdm_responder/capabilities.c
unit_test/test_spdm_responder/encap_challenge.c
unit_test/test_spdm_responder/encap_response.c
unit_test/test_spdm_responder/key_exchange.c
unit_test/test_spdm_responder/measurements.c
unit_test/test_spdm_responder/psk_exchange.c
unit_test/test_spdm_responder/test_spdm_responder.c

Add unit test to cover 1.2 extension TEST

---

unit_test/test_size/test_size_of_spdm_requester/spdm_requester_init.c
unit_test/test_size/test_size_of_spdm_responder/spdm_responder_init.c

fix test_size to use latest init flow.

---

unit_test/test_spdm_requester/get_version.c

Add a unit test case to trigger LIBSPDM_STATUS_INVALID_MSG_SIZE

---

os_stub/spdm_device_secret_lib_sample/lib.c
unit_test/test_spdm_requester/key_exchange.c

cleanup for missing spdm1.1 str.

---

README.md

Refactor documentation

---

library/spdm_common_lib/libspdm_com_context_data_session.c

Fix memory leak caused by libspdm_free_session_id

---

unit_test/fuzzing/test_requester/test_spdm_requester_challenge/challenge.c
unit_test/fuzzing/test_requester/test_spdm_requester_encap_challenge_auth/encap_challenge_auth.c
unit_test/fuzzing/test_requester/test_spdm_requester_finish/finish.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_certificate/get_certificate.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_digests/get_digests.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_measurements/get_measurements.c
unit_test/fuzzing/test_requester/test_spdm_requester_psk_finish/psk_finish.c
unit_test/fuzzing/test_responder/test_spdm_responder_finish_rsp/finish_rsp.c

 Fix memory leak on fuzzing test case

---

library/spdm_crypt_lib/libspdm_crypt_crypt.c
os_stub/cryptlib_openssl3/pk/sm2.c

Fix the issue for IDA with empty string

---

os_stub/cryptlib_openssl3/pem/pem.c
os_stub/cryptlib_openssl3/pk/sm2.c
os_stub/cryptlib_openssl3/pk/x509.c

Add the check for sm2 key type with EVP_PKEY_is_a function

---

library/spdm_common_lib/libspdm_com_opaque_data.c

fix #852 by checking version count.
Signed-off-by: Longlong Yang <longlong.yang@intel.com>

spdm_common_lib: libspdm_com_opaque_data assumes only one version count

---

include/internal/libspdm_common_lib.h

Fix issue #861 .
Signed-off-by: Troy Lee <troy_lee@aspeedtech.com>

Fix temp_message_k buffer size issue

---

os_stub/spdm_device_secret_lib_sample/lib.c

Fix nonstandard extension used: non-constant aggregate initializer

---

library/spdm_responder_lib/libspdm_rsp_algorithms.c
library/spdm_responder_lib/libspdm_rsp_challenge_auth.c
library/spdm_responder_lib/libspdm_rsp_key_exchange.c
library/spdm_responder_lib/libspdm_rsp_measurements.c
library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
os_stub/spdm_device_secret_lib_sample/lib.c
unit_test/test_spdm_responder/algorithms.c

Fix: https://github.com/DMTF/libspdm/issues/558

handle case that requester does not support measurement.

---

unit_test/test_spdm_requester/key_update.c

increase sequence number for next NOT Ready message

---

include/industry_standard/spdm.h
library/spdm_requester_lib/libspdm_req_get_capabilities.c
library/spdm_responder_lib/libspdm_rsp_capabilities.c
unit_test/test_spdm_requester/get_capabilities.c

Add data_size check for 1.2 capabilities.

---

library/spdm_responder_lib/libspdm_rsp_challenge_auth.c
unit_test/test_spdm_responder/challenge_auth.c

set M1/M2 to null in libspdm_get_response_challenge_auth().

---

os_stub/spdm_device_secret_lib_sample/lib.c

Change the function name to read_xxx_key

---

library/spdm_responder_lib/libspdm_rsp_certificate.c
unit_test/test_spdm_responder/certificate.c

Add invalid length (0) check in certificate rsp.

---

library/spdm_requester_lib/libspdm_req_challenge.c
library/spdm_requester_lib/libspdm_req_communication.c
library/spdm_requester_lib/libspdm_req_encap_request.c
library/spdm_requester_lib/libspdm_req_end_session.c
library/spdm_requester_lib/libspdm_req_finish.c
library/spdm_requester_lib/libspdm_req_get_capabilities.c
library/spdm_requester_lib/libspdm_req_get_certificate.c
library/spdm_requester_lib/libspdm_req_get_digests.c
library/spdm_requester_lib/libspdm_req_get_measurements.c
library/spdm_requester_lib/libspdm_req_get_version.c
library/spdm_requester_lib/libspdm_req_handle_error_response.c
library/spdm_requester_lib/libspdm_req_heartbeat.c
library/spdm_requester_lib/libspdm_req_key_exchange.c
library/spdm_requester_lib/libspdm_req_key_update.c
library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c
library/spdm_requester_lib/libspdm_req_psk_exchange.c
library/spdm_requester_lib/libspdm_req_psk_finish.c
library/spdm_requester_lib/libspdm_req_set_certificate.c
library/spdm_responder_lib/libspdm_rsp_communication.c

Add error handling for libspdm_acquire_sender_buffer

---

library/spdm_responder_lib/libspdm_rsp_measurements.c

Authentication is recommended by not required.

Change measurements state check.

---

library/spdm_responder_lib/libspdm_rsp_certificate.c
library/spdm_responder_lib/libspdm_rsp_digests.c

Allow get_certificate get_digest can be sent anytime.

---

include/internal/libspdm_common_lib.h
library/spdm_common_lib/libspdm_com_context_data_session.c
library/spdm_requester_lib/libspdm_req_psk_exchange.c
library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
unit_test/test_spdm_responder/respond_if_ready.c

process psk_hint field in libspdm_rsp_psk_exchange().

---

library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_requester_lib/libspdm_req_get_certificate.c
library/spdm_requester_lib/libspdm_req_get_digests.c
unit_test/test_spdm_requester/get_digests.c

Need support GET_DIGEST/GET_CERTIFICATE after CHALLENGE.

---

library/spdm_common_lib/libspdm_com_context_data.c

Session info free requires algorithm to clean up context.

Free session info before algorithms cleanup.

---

include/internal/libspdm_common_lib.h
library/spdm_common_lib/libspdm_com_context_data_session.c
library/spdm_requester_lib/libspdm_req_psk_exchange.c
library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
unit_test/test_spdm_responder/respond_if_ready.c

This reverts commit 0cd62f8192b24b4eac45978323f8ff79769e4ab5.
Need reopen: https://github.com/DMTF/libspdm/issues/886

Revert "process psk_hint field in libspdm_rsp_psk_exchange()."

---

library/spdm_common_lib/libspdm_com_crypto_service.c
unit_test/fuzzing/test_requester/test_spdm_requester_challenge/challenge.c
unit_test/fuzzing/test_requester/test_spdm_requester_encap_challenge_auth/encap_challenge_auth.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_measurements/get_measurements.c
unit_test/fuzzing/test_responder/test_spdm_responder_challenge_auth/challenge_auth.c
unit_test/fuzzing/test_responder/test_spdm_responder_measurements/measurements.c
unit_test/test_spdm_requester/challenge.c

the requester need free resource after the transcript is calculated.

---

library/spdm_responder_lib/libspdm_rsp_key_exchange.c
library/spdm_responder_lib/libspdm_rsp_psk_exchange.c

Add check for key exchange in session.

---

unit_test/test_spdm_requester/get_certificate.c
unit_test/test_spdm_requester/get_digests.c

Fix: https://github.com/DMTF/libspdm/issues/904

Fix typo in cert count calculation.

---

library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_requester_lib/libspdm_req_get_certificate.c
library/spdm_requester_lib/libspdm_req_get_digests.c
library/spdm_responder_lib/libspdm_rsp_certificate.c
library/spdm_responder_lib/libspdm_rsp_digests.c
unit_test/test_spdm_requester/get_digests.c
unit_test/test_spdm_responder/digests.c

Fix: #916 
some digests unit test about message_b full case was removed since the message_b is reset.

reset message_b after second GetDigest.

---

include/library/spdm_requester_lib.h
library/spdm_requester_lib/libspdm_req_get_certificate.c
library/spdm_requester_lib/libspdm_req_get_digests.c
library/spdm_responder_lib/libspdm_rsp_certificate.c
library/spdm_responder_lib/libspdm_rsp_digests.c
unit_test/test_spdm_requester/get_certificate.c
unit_test/test_spdm_requester/get_digests.c
unit_test/test_spdm_responder/certificate.c
unit_test/test_spdm_responder/digests.c

Add support for GET_CERTIFICATE and GET_DIGEST in a session.

---

include/industry_standard/spdm.h
include/internal/libspdm_common_lib.h
include/internal/libspdm_requester_lib.h
include/internal/libspdm_responder_lib.h
include/library/spdm_lib_config.h
library/spdm_requester_lib/libspdm_req_handle_error_response.c
library/spdm_requester_lib/libspdm_req_send_receive.c
library/spdm_responder_lib/CMakeLists.txt
library/spdm_responder_lib/libspdm_rsp_chunk_get.c
library/spdm_responder_lib/libspdm_rsp_chunk_send.c
library/spdm_responder_lib/libspdm_rsp_receive_send.c
unit_test/fuzzing/test_requester/test_spdm_requester_encap_request/CMakeLists.txt
unit_test/test_spdm_requester/CMakeLists.txt
unit_test/test_spdm_requester/chunk_get.c
unit_test/test_spdm_requester/test_spdm_requester.c
unit_test/test_spdm_responder/CMakeLists.txt
unit_test/test_spdm_responder/chunk_get.c
unit_test/test_spdm_responder/receive_send.c
unit_test/test_spdm_responder/test_spdm_responder.c

Just a copy from rkong_spdm_chunk_get_4 branch, rebased from main, and with all changes in a single commit.

SPDM Chunk Get Implementation

---

include/library/spdm_requester_lib.h
library/spdm_requester_lib/libspdm_req_get_csr.c
unit_test/test_spdm_requester/get_csr.c

Store csr for libspdm_req_get_csr more clearly

---

include/industry_standard/pci_idekm.h

Fix and add definition for PCI idekm.

---

library/spdm_requester_lib/libspdm_req_get_csr.c

Fix the  get_csr is not released

---

os_stub/spdm_device_secret_lib_sample/lib.c

fix the private key memory leak

---

include/hal/library/cryptlib.h
include/library/spdm_device_secret_lib.h
library/spdm_responder_lib/libspdm_rsp_csr.c
os_stub/cryptlib_mbedtls/pk/x509.c
os_stub/cryptlib_null/pk/x509.c
os_stub/cryptlib_openssl/pk/x509.c
os_stub/spdm_device_secret_lib_null/lib.c
os_stub/spdm_device_secret_lib_sample/lib.c
unit_test/test_crypt/x509_verify.c

Fix get csr memory leak

---

library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_common_lib/libspdm_com_crypto_service.c
library/spdm_requester_lib/libspdm_req_encap_certificate.c
library/spdm_requester_lib/libspdm_req_encap_challenge_auth.c
library/spdm_requester_lib/libspdm_req_encap_request.c
library/spdm_requester_lib/libspdm_req_finish.c
library/spdm_requester_lib/libspdm_req_key_exchange.c
library/spdm_responder_lib/libspdm_rsp_certificate.c
library/spdm_responder_lib/libspdm_rsp_challenge_auth.c
library/spdm_responder_lib/libspdm_rsp_finish.c
library/spdm_responder_lib/libspdm_rsp_key_exchange.c
library/spdm_responder_lib/libspdm_rsp_measurements.c
library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
library/spdm_responder_lib/libspdm_rsp_set_certificate.c
unit_test/test_spdm_responder/key_exchange.c
unit_test/test_spdm_responder/measurements.c

remove unnecessary slot_count check.

---

include/internal/libspdm_common_lib.h
include/internal/libspdm_secured_message_lib.h
library/spdm_common_lib/libspdm_com_context_data_session.c
library/spdm_requester_lib/libspdm_req_psk_exchange.c
library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
library/spdm_secured_message_lib/libspdm_secmes_context_data.c
os_stub/spdm_device_secret_lib_sample/lib.c
unit_test/test_spdm_requester/psk_finish.c
unit_test/test_spdm_responder/psk_finish.c
unit_test/test_spdm_responder/respond_if_ready.c

libspdm_rsp_psk_exchange not processing psk_hint field.

---

include/library/spdm_lib_config.h
library/spdm_responder_lib/libspdm_rsp_csr.c

Delete req_info buffer size

---

unit_test/fuzzing/fuzzing_AFL.sh

Fix : #952
Signed-off-by: yaohuixguo <yaohuix.guo@intel.com>

Fix run fuzzing_AFL.sh occurrence mixed code coverage

---

unit_test/fuzzing/test_responder/test_spdm_responder_capabilities/capabilities.c
unit_test/test_spdm_responder/algorithms.c
unit_test/test_spdm_responder/capabilities.c
unit_test/test_spdm_responder/version.c

remove ResponseNotReady unit test in vca

---

include/library/spdm_common_lib.h
library/spdm_common_lib/libspdm_com_context_data.c

support VCA cached for CACHE_CAP in 1.2 for transcript.

---

library/spdm_common_lib/libspdm_com_opaque_data.c

add check for element pointer returned from opaque data.

---

unit_test/fuzzing/test_requester/test_spdm_requester_get_measurements/get_measurements.c
unit_test/fuzzing/test_responder/test_spdm_responder_measurements/measurements.c

Fix memory leak for measurements without signature case.

---

include/internal/libspdm_common_lib.h
library/spdm_common_lib/libspdm_com_context_data_session.c
library/spdm_requester_lib/libspdm_req_encap_key_update.c
library/spdm_requester_lib/libspdm_req_key_update.c
library/spdm_responder_lib/libspdm_rsp_key_update.c
unit_test/fuzzing/test_requester/test_spdm_requester_encap_key_update/encap_key_update.c
unit_test/fuzzing/test_responder/test_spdm_responder_encap_key_update/encap_key_update.c
unit_test/fuzzing/test_responder/test_spdm_responder_key_update/key_update.c
unit_test/test_spdm_requester/encap_key_update.c
unit_test/test_spdm_responder/encap_key_update.c
unit_test/test_spdm_responder/key_update.c

fix the key update responder check

---

.github/workflows/build.yml

Add unit test test_spdm_crypt for CI

---

unit_test/test_spdm_requester/encap_request.c

Fix https://github.com/DMTF/libspdm/issues/940: 

Fix for stack corruption on encap request test cases.

---

unit_test/test_spdm_requester/get_measurements.c

Fix for stack corruption on requester get measurements test.

---

README.md

Update SPDM spec version.

---

library/spdm_responder_lib/libspdm_rsp_capabilities.c
unit_test/test_spdm_responder/capabilities.c

Check DataTransferSize and MaxSPDMmsgSize

---

library/spdm_requester_lib/libspdm_req_get_csr.c

Add session_id param for libspdm_handle_error_response_main

---

library/spdm_responder_lib/libspdm_rsp_psk_exchange.c

Fix : #981 
Add spdm_request->psk_hint_length length check condition to prevent oversize

Fix issues hang in libspdm_rsp_psk_exchange

---

doc/design.md
doc/test.md

Minor spelling and grammar changes.

Update documents for upcoming checkpoint

---

doc/test.md
unit_test/fuzzing/fuzzing_AFLTurbo.sh

Update the start guide and script for fuzzing with AFLTurbo

---

library/spdm_responder_lib/libspdm_rsp_certificate.c
library/spdm_responder_lib/libspdm_rsp_challenge_auth.c
library/spdm_responder_lib/libspdm_rsp_key_exchange.c

Add missing local_cert_chain_provision[slot_id] check.

Add slot_id check

---

os_stub/spdm_device_secret_lib_sample/lib.c

The successful return should change content_changed.

Fix measurement successful return

---

library/spdm_secured_message_lib/libspdm_secmes_session.c
os_stub/spdm_device_secret_lib_sample/lib.c
unit_test/test_spdm_requester/key_exchange.c

Fix: https://github.com/DMTF/libspdm/issues/987

Fix Handshake-Secret calculation

---

include/library/spdm_lib_config.h

REF: https://github.com/DMTF/libspdm/issues/950

Add comments for some of the macros

---

include/industry_standard/spdm.h
library/spdm_responder_lib/libspdm_rsp_csr.c
unit_test/test_spdm_requester/get_csr.c

Fix csr_length definition error.

---

library/spdm_responder_lib/libspdm_rsp_csr.c

Fix CSR data pointer misuse.

---

library/spdm_requester_lib/libspdm_req_get_measurements.c

Allow Get Measurement before/without Authentication

---

doc/test.md

Add the guide for Coverity.

---

library/spdm_requester_lib/libspdm_req_encap_challenge_auth.c
library/spdm_responder_lib/libspdm_rsp_challenge_auth.c

Fix bad large left shifting by more than 31 bits

---

library/spdm_requester_lib/libspdm_req_challenge.c

Remove illegal check of reserved field

---

include/internal/libspdm_responder_lib.h
include/library/spdm_lib_config.h
include/library/spdm_requester_lib.h
library/spdm_requester_lib/libspdm_req_get_csr.c
library/spdm_responder_lib/libspdm_rsp_csr.c
library/spdm_responder_lib/libspdm_rsp_receive_send.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_csr/get_csr.c.c
unit_test/fuzzing/test_responder/test_spdm_responder_csr/csr.c
unit_test/test_spdm_requester/get_csr.c
unit_test/test_spdm_requester/test_spdm_requester.c
unit_test/test_spdm_responder/csr.c
unit_test/test_spdm_responder/test_spdm_responder.c

Add CSR_CAP capabilities enable/disable macro

---

library/spdm_responder_lib/libspdm_rsp_measurements.c
unit_test/test_spdm_responder/measurements.c

Fix: #1030 
Because the `libspdm_create_measurement_opaque` and `libspdm_create_measurement_signature` have common code and they are internal function, I change the function parameters to make the common code reuse.
And add a unit test for code test.

Make the common code reuse in libspdm_rsp_measurements

---

include/library/spdm_return_status.h

Cleanup header file and change size of libspdm_return_t

---

doc/test.md
unit_test/test_spdm_requester/challenge.c
unit_test/test_spdm_responder/challenge_auth.c

Rename last vestiges of openspdm to libspdm

---

unit_test/fuzzing/test_requester/test_spdm_requester_encap_request/encap_request.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_digests/get_digests.c
unit_test/fuzzing/test_requester/test_spdm_requester_key_exchange/key_exchange.c
unit_test/fuzzing/test_requester/test_spdm_requester_set_certificate/set_certificate.c
unit_test/fuzzing/test_responder/test_spdm_responder_csr/csr.c

Fix and add fuzzy test cases to improve code coverage

---

include/internal/libspdm_secured_message_lib.h
include/library/spdm_device_secret_lib.h
library/spdm_secured_message_lib/libspdm_secmes_session.c
os_stub/spdm_device_secret_lib_sample/spdm_device_secret_lib_internal.h

Cleanup device secret lib

---

README.md
os_stub/openssllib/version.txt

Udpate openssl to 1.1.1q

---

os_stub/spdm_device_secret_lib_sample/lib.c

Fix memory leak by free key

---

library/spdm_responder_lib/libspdm_rsp_measurements.c

Fix libspdm_create_measurement_opaque address error

---

os_stub/cryptlib_openssl/pem/pem.c

Change right retrun in get_private_key_from_pem

---

os_stub/cryptlib_openssl/pk/x509.c

fix memory lost in function libspdm_gen_x509_csr.

---

library/spdm_responder_lib/libspdm_rsp_csr.c

Fix memory overflow in CSR

---

os_stub/cryptlib_openssl/pk/x509.c

Make libspdm_gen_x509_csr return right

---

include/library/spdm_crypt_lib.h
library/spdm_crypt_lib/libspdm_crypt_crypt.c
library/spdm_secured_message_lib/libspdm_secmes_session.c
os_stub/spdm_device_secret_lib_sample/lib.c

Fix: https://github.com/DMTF/libspdm/issues/1102

Define and use hkdf_extract.

---

os_stub/include/industry_standard/link_type_ex.h

fix unicode issue.

---

library/spdm_common_lib/libspdm_com_crypto_service.c

Fix the mut_hash inconsistent

---

os_stub/cryptlib_openssl/pk/x509.c

Fix Calling sk_X509_push without checking return value.

---

library/spdm_responder_lib/libspdm_rsp_chunk_get.c

Add license to file

---

include/industry_standard/pci_tdisp.h

Signe-off-by: Jiewen Yao <jiewen.yao@intel.com>
* The spdm-emu related update is at https://github.com/DMTF/spdm-emu/pull/138.
* The spdm-dump related update is at https://github.com/DMTF/spdm-dump/pull/49.

add PCI TDISP definition as SPDM application.

---

os_stub/cryptlib_mbedtls/pk/x509.c

Fix responder_csr  memory leak

---

library/spdm_common_lib/libspdm_com_context_data.c

Fix uninitialized variable hash_size in library/spdm_common_lib/libspdm_com_context_data.c

---

os_stub/cryptlib_mbedtls/pk/x509.c

fix uninitialized local variable in os_stub/cryptlib_mbedtls/pk/x509.c 

---

library/spdm_common_lib/libspdm_com_context_data.c

Add hash_free when hash_update failed

---

library/spdm_requester_lib/libspdm_req_finish.c
library/spdm_requester_lib/libspdm_req_key_exchange.c
library/spdm_requester_lib/libspdm_req_psk_exchange.c
library/spdm_requester_lib/libspdm_req_psk_finish.c
library/spdm_responder_lib/libspdm_rsp_finish.c
library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
library/spdm_responder_lib/libspdm_rsp_psk_finish.c

Change hard_code from 64 to LIBSPDM_MAX_HASH_SIZE

---

os_stub/cryptlib_mbedtls/sys_call/timer_wrapper_host.c

Fix the potential hazards of gmtime

---

unit_test/test_crypt/hkdf_verify.c

add hkdf-sha384 KAT in test_crypt.

---

os_stub/spdm_device_secret_lib_sample/lib.c

Fix code scanning alert - File created without restricting permissions

---

include/industry_standard/cxl_idekm.h

the spdm-emu patch is at https://github.com/DMTF/spdm-emu/pull/144
the spdm-dump patch is at https://github.com/DMTF/spdm-dump/pull/54

Add CXL IDE_KM message in CXL 3.0

---

os_stub/spdm_device_secret_lib_sample/lib.c

Fix the problem of open function in spdmemu

---

library/spdm_common_lib/libspdm_com_context_data.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_certificate/get_certificate.c
unit_test/fuzzing/test_responder/test_spdm_responder_encap_get_certificate/encap_get_certificate.c

fix: https://github.com/DMTF/libspdm/issues/1178

Add libspdm_register_verify_spdm_cert_chain_func().

---

unit_test/fuzzing/test_responder/test_spdm_responder_capabilities/capabilities.c

Fix incorrect enumeration values in test_spdm_responder_capabilities  test cases

---

library/spdm_responder_lib/libspdm_rsp_receive_send.c

need to session state when SPDM_FINISH_RSP is in Chunk.

---

include/hal/library/cryptlib.h
include/hal/library/cryptlib/cryptlib_rng.h

Cleanup rng in cryptlib

---

library/spdm_requester_lib/libspdm_req_send_receive.c
library/spdm_responder_lib/libspdm_rsp_receive_send.c

Validate chunking support in libspdm in session.

---

CMakeLists.txt

reduce complie optimize option in Libfuuzer for work around

---

include/library/spdm_lib_config.h
library/spdm_requester_lib/libspdm_req_send_receive.c
library/spdm_responder_lib/libspdm_rsp_receive_send.c

Validate chunking support in libspdm in session (2)

---

include/hal/library/cryptlib/cryptlib_sm2.h
os_stub/cryptlib_mbedtls/pk/ec.c
os_stub/cryptlib_mbedtls/pk/sm2.c
os_stub/cryptlib_null/pk/ec.c
os_stub/cryptlib_null/pk/sm2.c
os_stub/cryptlib_openssl/pk/ec.c
os_stub/cryptlib_openssl/pk/sm2.c

renames keywords in libspdm

---

include/library/spdm_lib_config.h
library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_requester_lib/libspdm_req_handle_error_response.c
library/spdm_requester_lib/libspdm_req_send_receive.c
library/spdm_responder_lib/libspdm_rsp_chunk_send_ack.c
library/spdm_responder_lib/libspdm_rsp_communication.c
library/spdm_responder_lib/libspdm_rsp_receive_send.c
unit_test/test_spdm_responder/capabilities.c

with change: `#define LIBSPDM_DATA_TRANSFER_SIZE 42`
1) libspdm unit test pass 
2) spdm-emu test pass

Make the chunk work with transfer_size 42 in spdm-emu.

---

doc/design.md

Document send and receive buffer requirements

---

README.md

Fix: #1194
Signed-off-by: Wei Liu <wei3.liu@intel.com>

Openssl customized build enhancement

---

doc/user_guide.md

Add message logging to documentation

---

include/library/spdm_crypt_lib.h
library/spdm_crypt_lib/libspdm_crypt_crypt.c
unit_test/test_size/test_size_of_spdm_requester/spdm_requester.h

Cleanup spdm_crypt_lib

---

library/spdm_requester_lib/libspdm_req_get_certificate.c
library/spdm_responder_lib/libspdm_rsp_certificate.c
library/spdm_responder_lib/libspdm_rsp_receive_send.c
unit_test/spdm_unit_test_common/common.c
unit_test/test_spdm_requester/chunk_get.c
unit_test/test_spdm_responder/certificate.c

Fixes #1018.
Still needs unit test coverage.

Add chunking to CERTIFICATE response

---

README.md

Clarify use of statically allocated memory

---

.github/workflows/build.yml

Ignore CI/CD when editing documents

---

library/spdm_crypt_lib/libspdm_crypt_crypt.c

Fix minor compilation warnings

---

VERSION.md

Update VERSION.md to 2.2.0 and released

---

VERSION.md

Update VERSION.md after the 2.2.0 release

---

library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_common_lib/libspdm_com_context_data_session.c
library/spdm_common_lib/libspdm_com_crypto_service.c
library/spdm_common_lib/libspdm_com_crypto_service_session.c
library/spdm_common_lib/libspdm_com_msg_log.c
library/spdm_common_lib/libspdm_com_opaque_data.c
library/spdm_common_lib/libspdm_com_support.c

This is a refactor and should not introduce any functional changes.

Cleanup common lib

---

.github/workflows/codeql-analysis.yml

Omit CodeQL if only documents are updated

---

include/library/spdm_secured_message_lib.h
library/spdm_secured_message_lib/libspdm_secmes_context_data.c
library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c
library/spdm_secured_message_lib/libspdm_secmes_key_exchange.c
library/spdm_secured_message_lib/libspdm_secmes_session.c

Cleanup secure message lib

---

library/spdm_requester_lib/libspdm_req_get_capabilities.c

Add more check for get_capability

---

library/spdm_responder_lib/libspdm_rsp_measurements.c

So that it is removed if debug is disabled. Also cleaned up some of the code in the file.
Fixes #1268.

Replace DEBUG_CODE_BEGIN with DEBUG_CODE

---

library/spdm_requester_lib/libspdm_req_send_receive.c

Unconditionally check version in response

---

library/spdm_requester_lib/libspdm_req_challenge.c
library/spdm_requester_lib/libspdm_req_finish.c
library/spdm_requester_lib/libspdm_req_get_digests.c
library/spdm_requester_lib/libspdm_req_get_measurements.c
library/spdm_requester_lib/libspdm_req_heartbeat.c
library/spdm_requester_lib/libspdm_req_key_exchange.c
library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c
unit_test/test_spdm_requester/get_measurements.c

Refactor code on the Requester side.

General cleanup

---

library/spdm_responder_lib/libspdm_rsp_algorithms.c
library/spdm_responder_lib/libspdm_rsp_capabilities.c
library/spdm_responder_lib/libspdm_rsp_version.c

Refactor Responder VCA

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/compliance-checks.yml

Update actions checkout version to 3

---

include/library/spdm_common_lib.h
include/library/spdm_requester_lib.h

Clean up integrator-visible headers

---

doc/test.md

Fix: #1295 
Signed-off-by: Wei Liu <wei3.liu@intel.com>

Correct the code coverage documentation in doc/test.md

---

os_stub/openssllib/include/crt_support.h
unit_test/test_size/cryptstublib_dummy/timeclock_dummy.c
unit_test/test_spdm_requester/chunk_get.c
unit_test/test_spdm_requester/encap_request.c
unit_test/test_spdm_requester/get_certificate.c
unit_test/test_spdm_responder/respond_if_ready.c

Fix Clang build error

---

unit_test/test_size/test_size_of_spdm_requester/CMakeLists.txt
unit_test/test_size/test_size_of_spdm_requester/spdm_requester_init.c
unit_test/test_size/test_size_of_spdm_responder/CMakeLists.txt
unit_test/test_size/test_size_of_spdm_responder/spdm_responder_init.c

Fix test_size app

---

unit_test/fuzzing/test_requester/test_spdm_requester_get_csr/get_csr.c
unit_test/fuzzing/test_responder/test_spdm_responder_csr/csr.c
unit_test/test_spdm_requester/chunk_get.c
unit_test/test_spdm_requester/get_certificate.c

fix build error when some cap disabled.

---

unit_test/test_crypt/aead_verify.c
unit_test/test_crypt/hkdf_verify.c

Fix build error when disable some algorithms.

---

library/spdm_responder_lib/libspdm_rsp_certificate.c
unit_test/test_spdm_responder/certificate.c

Allow for zero-length certificate chain

---

include/hal/library/cryptlib/cryptlib_ec.h
os_stub/cryptlib_mbedtls/pk/ec.c
os_stub/cryptlib_openssl/pk/ec.c
unit_test/test_crypt/ec_verify.c

Add libspdm_ec_set_priv_key function and test

---

os_stub/cryptlib_mbedtls/pk/dh.c

Fix dh_compute_key copy mem overlap

---

.github/workflows/build.yml

Add test_crypt in CI

---

unit_test/test_crypt/test_crypt.c
unit_test/test_spdm_crypt/test_spdm_crypt.c

Add test_crypt and test_spdm_crypt return for CI

---

CMakeLists.txt
unit_test/test_size/test_size_of_spdm_requester/CMakeLists.txt
unit_test/test_size/test_size_of_spdm_responder/CMakeLists.txt

This is needed to make test_size to pass build with mbedtls crypto and secret_lib_sample.

Add armbuildlib for ARM GNU toolchain.

---

unit_test/test_size/intrinsiclib/memory_intrinsics.c
unit_test/test_size/test_size_of_spdm_requester/CMakeLists.txt
unit_test/test_size/test_size_of_spdm_requester/support.c
unit_test/test_size/test_size_of_spdm_responder/CMakeLists.txt
unit_test/test_size/test_size_of_spdm_responder/support.c

Enable spdm_device_secret_lib_spdm build for test_size.

---

library/spdm_requester_lib/libspdm_req_get_capabilities.c
unit_test/test_spdm_requester/error_test/get_capabilities_err.c

Expand GET_CAPABILITIES unit test coverage

---

README.md

Add example on JAVA verifier.

---

os_stub/cryptlib_mbedtls/pk/ec.c
os_stub/cryptlib_openssl/pk/ec.c
unit_test/test_crypt/ec_verify.c

Fix ecdsa wrong nid

---

library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_common_lib/libspdm_com_context_data_session.c
library/spdm_common_lib/libspdm_com_crypto_service.c
unit_test/fuzzing/test_requester/test_spdm_requester_finish/finish.c
unit_test/fuzzing/test_requester/test_spdm_requester_key_exchange/key_exchange.c

Fix macro in expression

---

unit_test/test_spdm_requester/error_test/negotiate_algorithms_err.c

Expand NEGOTIATE_ALGORITHMS code coverage

---

.github/workflows/build.yml

Add ARM_GNU arch build to CI

---

library/spdm_requester_lib/libspdm_req_key_exchange.c

Fix the memory leak that occurred in req_key_exchange 

---

library/spdm_requester_lib/libspdm_req_key_exchange.c
library/spdm_requester_lib/libspdm_req_psk_exchange.c

Check if session IDs are available

---

.github/workflows/build.yml

Rename test names in CI / CD

---

library/spdm_requester_lib/libspdm_req_communication.c
library/spdm_requester_lib/libspdm_req_encap_certificate.c
library/spdm_requester_lib/libspdm_req_encap_challenge_auth.c
library/spdm_requester_lib/libspdm_req_encap_digests.c
library/spdm_requester_lib/libspdm_req_encap_error.c
library/spdm_requester_lib/libspdm_req_encap_key_update.c
library/spdm_requester_lib/libspdm_req_encap_request.c
library/spdm_requester_lib/libspdm_req_finish.c
library/spdm_requester_lib/libspdm_req_get_capabilities.c
library/spdm_requester_lib/libspdm_req_get_certificate.c
library/spdm_requester_lib/libspdm_req_get_csr.c
library/spdm_requester_lib/libspdm_req_get_version.c
library/spdm_requester_lib/libspdm_req_handle_error_response.c
library/spdm_requester_lib/libspdm_req_key_exchange.c
library/spdm_requester_lib/libspdm_req_key_update.c
library/spdm_requester_lib/libspdm_req_psk_exchange.c
library/spdm_requester_lib/libspdm_req_send_receive.c
library/spdm_requester_lib/libspdm_req_set_certificate.c

Delete Doxygen comments from spdm_requester_lib implementations

---

library/spdm_responder_lib/libspdm_rsp_algorithms.c
library/spdm_responder_lib/libspdm_rsp_capabilities.c
library/spdm_responder_lib/libspdm_rsp_certificate.c
library/spdm_responder_lib/libspdm_rsp_challenge_auth.c
library/spdm_responder_lib/libspdm_rsp_chunk_get.c
library/spdm_responder_lib/libspdm_rsp_chunk_send_ack.c
library/spdm_responder_lib/libspdm_rsp_communication.c
library/spdm_responder_lib/libspdm_rsp_csr.c
library/spdm_responder_lib/libspdm_rsp_digests.c
library/spdm_responder_lib/libspdm_rsp_encap_challenge.c
library/spdm_responder_lib/libspdm_rsp_encap_get_certificate.c
library/spdm_responder_lib/libspdm_rsp_encap_get_digests.c
library/spdm_responder_lib/libspdm_rsp_encap_response.c
library/spdm_responder_lib/libspdm_rsp_end_session.c
library/spdm_responder_lib/libspdm_rsp_error.c
library/spdm_responder_lib/libspdm_rsp_finish.c
library/spdm_responder_lib/libspdm_rsp_handle_response_state.c
library/spdm_responder_lib/libspdm_rsp_heartbeat.c
library/spdm_responder_lib/libspdm_rsp_key_exchange.c
library/spdm_responder_lib/libspdm_rsp_measurements.c
library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
library/spdm_responder_lib/libspdm_rsp_psk_finish.c
library/spdm_responder_lib/libspdm_rsp_respond_if_ready.c
library/spdm_responder_lib/libspdm_rsp_set_certificate.c
library/spdm_responder_lib/libspdm_rsp_version.c

Delete Doxygen comments from spdm_responder_lib implementations

---

library/spdm_requester_lib/libspdm_req_get_measurements.c
unit_test/test_spdm_requester/CMakeLists.txt
unit_test/test_spdm_requester/error_test/get_measurements_err.c
unit_test/test_spdm_requester/get_measurements.c
unit_test/test_spdm_requester/test_spdm_requester.c

Increased line coverage from 67.9 % to 73.9 %. Still have some work to do.

Increase GET_MEASUREMENTS code coverage

---

library/spdm_common_lib/libspdm_com_support.c

Remove assertions from managed buffer functions

---

library/spdm_requester_lib/libspdm_req_key_exchange.c
unit_test/test_spdm_requester/key_exchange.c

Enhance slot_id checking

---

library/spdm_requester_lib/libspdm_req_challenge.c

Fix build error when MUT_AUTH_CAP and ENCAP_CAP are disabled

---

doc/test.md
library/spdm_crypt_lib/libspdm_crypt_cert.c

Fixes #1462.
This does not include changes to LICENSE.md, as that requires DMTF board approval. A separate issue will be filed to track that effort.

Change http:// to https:// where appropriate

---

library/spdm_requester_lib/libspdm_req_finish.c
library/spdm_requester_lib/libspdm_req_heartbeat.c

Fix pointer 'session_info' checked for NULL may be dereferenced.

---

.github/workflows/build.yml

Disable test_crypt in CI

---

README.md
doc/build.md
doc/test.md

Fix: https://github.com/DMTF/libspdm/issues/1448

Move build info for other arch from readme to a build.md

---

doc/user_guide.md
include/library/spdm_common_lib.h

Fix #1146 
Fix #1147 
Signed-off-by: Jiewen Yao <jiewen.yao@Intel.com>

Add more info in User guide

---

include/library/spdm_secured_message_lib.h
library/spdm_secured_message_lib/libspdm_secmes_context_data.c
unit_test/test_spdm_common/context_data.c

Allow export of export master secret to target small destinations

---

library/spdm_requester_lib/libspdm_req_send_receive.c

Fix the wrong ct_exponent

---

doc/user_guide.md
include/internal/libspdm_common_lib.h
include/library/spdm_common_lib.h
library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_requester_lib/libspdm_req_get_version.c
library/spdm_responder_lib/libspdm_rsp_version.c

Add deinit_context function to free memory

---

os_stub/spdm_device_secret_lib_sample/lib.c

Fix result typo error

---

include/internal/libspdm_common_lib.h
library/spdm_common_lib/libspdm_com_context_data.c

Change rtt size

---

library/spdm_requester_lib/libspdm_req_challenge.c
library/spdm_requester_lib/libspdm_req_get_measurements.c
library/spdm_requester_lib/libspdm_req_key_exchange.c

Fix: #1514 
I have fixed the all code.

Fix the wrong check for slot_id when slot_id is 0xFF

---

library/spdm_requester_lib/libspdm_req_get_capabilities.c
library/spdm_responder_lib/libspdm_rsp_algorithms.c
library/spdm_responder_lib/libspdm_rsp_capabilities.c
library/spdm_responder_lib/libspdm_rsp_version.c
unit_test/test_spdm_responder/capabilities.c
unit_test/test_spdm_responder/version.c

This pull request weakens the strict request size checks done by the Responder in VCA. It also adds the "new" GET_CAPABILITIES checks from the Requester.

Cleanup VCA

---

doc/user_guide.md

Fix README doc

---

library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_common_lib/libspdm_com_crypto_service.c
library/spdm_requester_lib/libspdm_req_finish.c
library/spdm_requester_lib/libspdm_req_get_measurements.c
library/spdm_requester_lib/libspdm_req_key_exchange.c
library/spdm_responder_lib/libspdm_rsp_encap_get_certificate.c
library/spdm_responder_lib/libspdm_rsp_finish.c
library/spdm_responder_lib/libspdm_rsp_key_exchange.c

Add slot_id assert when it is used in array

---

include/library/spdm_common_lib.h
library/spdm_common_lib/libspdm_com_context_data.c

Add libspdm_set_data for provisioned_slot_id

---

include/hal/library/cryptlib/cryptlib_dh.h
os_stub/cryptlib_mbedtls/pk/dh.c
os_stub/cryptlib_openssl/pk/dh.c
unit_test/test_crypt/dh_verify.c
unit_test/test_crypt/test_crypt.c

add LIBSPDM_FFDHE_SUPPORT check

---

os_stub/spdm_device_secret_lib_sample/lib.c

Add LIBSPDM_PRIVATE_KEY_MODE_RAW_KEY_ONLY for image size calculation.

---

os_stub/cryptlib_mbedtls/pk/x509.c
os_stub/mbedtlslib/CMakeLists.txt
os_stub/mbedtlslib/include/mbedtls/config.h

1) Fix https://github.com/DMTF/libspdm/issues/1537
2) remove unnecessary mbedtls configuration.

Cleanup Mbedtls

---

library/spdm_requester_lib/libspdm_req_challenge.c
library/spdm_requester_lib/libspdm_req_encap_request.c
library/spdm_requester_lib/libspdm_req_get_measurements.c
library/spdm_requester_lib/libspdm_req_key_exchange.c
library/spdm_responder_lib/libspdm_rsp_encap_challenge.c
library/spdm_responder_lib/libspdm_rsp_encap_response.c
library/spdm_responder_lib/libspdm_rsp_key_exchange.c

Fix: https://github.com/DMTF/libspdm/issues/1541
Also need spdm-emu: https://github.com/DMTF/spdm-emu/pull/194

Fix slot 0xFF system crash issue.

---

unit_test/test_spdm_requester/error_test/negotiate_algorithms_err.c

Add unit test for OtherParamsSelection has more than one bit set.

---

unit_test/test_crypt/ecd_verify.c
unit_test/test_crypt/ecd_verify2.c

Add missing EDDSA macro check.

---

os_stub/spdm_crypt_ext_lib/spdm_crypt_ext.c
unit_test/test_crypt/test_crypt.h

Fix wrong include file.

---

doc/user_guide.md
include/internal/libspdm_common_lib.h
include/internal/libspdm_secured_message_lib.h
library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_secured_message_lib/libspdm_secmes_context_data.c

Fix https://github.com/DMTF/libspdm/issues/1443

define MACRO for LIBSPDM_CONTEXT_SIZE

---

unit_test/spdm_unit_test_common/algo.c
unit_test/test_spdm_requester/error_test/key_exchange_err.c
unit_test/test_spdm_requester/key_exchange.c
unit_test/test_spdm_requester/psk_exchange.c

fix test case issue on measurement_hash

---

include/industry_standard/spdm.h
library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c
library/spdm_responder_lib/libspdm_rsp_algorithms.c
unit_test/test_spdm_requester/error_test/negotiate_algorithms_err.c
unit_test/test_spdm_requester/negotiate_algorithms.c

Fix: https://github.com/DMTF/libspdm/issues/1548

use other_params_selection for response message.

---

include/library/spdm_common_lib.h
library/spdm_common_lib/libspdm_com_context_data.c

Fix: https://github.com/DMTF/libspdm/issues/1523
spdm_emu fix: https://github.com/DMTF/spdm-emu/pull/192

Add is_requester config setting.

---

unit_test/test_crypt/rsa_verify.c

https://github.com/DMTF/libspdm/issues/1561

Fix macro usage

---

os_stub/cryptlib_mbedtls/pk/x509.c

Deduce all RSA key parameters by mbedtls_rsa_complete

---

library/spdm_crypt_lib/libspdm_crypt_dhe.c

Remove function pointers from DHE cryptography in spdm_crypt_lib

---

library/spdm_requester_lib/libspdm_req_common.c
library/spdm_responder_lib/libspdm_rsp_common.c

Fix: https://github.com/DMTF/libspdm/issues/1566

Fix session_id check.

---

library/spdm_crypt_lib/libspdm_crypt_cert.c
library/spdm_responder_lib/libspdm_rsp_set_certificate.c
unit_test/test_spdm_requester/get_certificate.c

Fix: https://github.com/DMTF/libspdm/issues/1559

add cert_length check for set_certificate and get_certificate

---

README.md
doc/build.md
doc/design.md
doc/test.md
doc/user_guide.md
include/library/spdm_common_lib.h
include/library/spdm_lib_config.h
library/spdm_common_lib/libspdm_com_context_data.c

Update documentation for 2.3 release

---

include/library/spdm_lib_config.h

Add comments for newly added macros

---

VERSION.md

Update VERSION.md for 2.3 release

---

VERSION.md

Update VERSION.md to 3.0 after 2.3 release

---

library/spdm_requester_lib/libspdm_req_challenge.c
library/spdm_requester_lib/libspdm_req_get_measurements.c
library/spdm_requester_lib/libspdm_req_key_exchange.c
library/spdm_requester_lib/libspdm_req_psk_exchange.c
library/spdm_responder_lib/libspdm_rsp_encap_challenge.c

Change Client/Server to Requester/Responder

---

include/library/spdm_lib_config.h

Add FIPS 140-3 config for libspdm

---

.github/workflows/build.yml

Add concurrency to build and test action

---

include/library/spdm_common_lib.h
include/library/spdm_lib_config.h
library/spdm_common_lib/libspdm_com_context_data.c
unit_test/test_spdm_common/context_data.c

More tests can be added as needed.
Fixes #1027.

Initial commit for libspdm_check_context

---

library/spdm_secured_message_lib/libspdm_secmes_session.c

Delete bin_str0 in libspdm_generate_session_handshake_key

---

os_stub/spdm_device_secret_lib_sample/lib.c

Zero private key before free for FIPS

---

include/internal/libspdm_common_lib.h
library/spdm_common_lib/libspdm_com_context_data.c

Capitalize libspdm_context_struct_version

---

library/spdm_responder_lib/libspdm_rsp_capabilities.c
unit_test/test_spdm_responder/capabilities.c

Remove illegal capabilities checks

---

library/spdm_common_lib/libspdm_com_crypto_service.c
library/spdm_requester_lib/libspdm_req_get_measurements.c

Make libspdm_verify_challenge_auth_signature() and libspdm_verify_measurement_signature() align with libspdm_verify_key_exchange_rsp_signature() and libspdm_verify_finish_req_signature().
Just remove the duplicated code. No functionality change.

Reorg the libspdm_verify function.

---

library/spdm_responder_lib/libspdm_rsp_key_exchange.c

Add check for new dhe_context

---

library/spdm_crypt_lib/libspdm_crypt_asym.c
library/spdm_crypt_lib/libspdm_crypt_dhe.c
library/spdm_crypt_lib/libspdm_crypt_hash.c
library/spdm_crypt_lib/libspdm_crypt_hmac.c

Fix: https://github.com/DMTF/libspdm/issues/1612

Add NULL check on libspdm_crypt_lib free()

---

include/internal/libspdm_common_lib.h
include/internal/libspdm_lib_config.h
include/internal/libspdm_responder_lib.h
include/library/spdm_requester_lib.h
library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_requester_lib/libspdm_req_handle_error_response.c
library/spdm_requester_lib/libspdm_req_send_receive.c
library/spdm_requester_lib/libspdm_req_set_certificate.c
library/spdm_responder_lib/libspdm_rsp_chunk_get.c
library/spdm_responder_lib/libspdm_rsp_chunk_send_ack.c
library/spdm_responder_lib/libspdm_rsp_communication.c
library/spdm_responder_lib/libspdm_rsp_receive_send.c
library/spdm_responder_lib/libspdm_rsp_set_certificate.c

Remove deprecated macros

---

library/spdm_responder_lib/libspdm_rsp_algorithms.c
unit_test/test_spdm_requester/error_test/negotiate_algorithms_err.c
unit_test/test_spdm_responder/algorithms.c

Fix: https://github.com/DMTF/libspdm/issues/1607

Add alg_type check in algorithm response.

---

library/spdm_common_lib/libspdm_com_context_data.c

Delete unneeded assignment to 0

---

include/library/spdm_common_lib.h
include/library/spdm_requester_lib.h
library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_common_lib/libspdm_com_context_data_session.c
library/spdm_common_lib/libspdm_com_crypto_service.c
library/spdm_common_lib/libspdm_com_msg_log.c
library/spdm_requester_lib/libspdm_req_challenge.c
library/spdm_requester_lib/libspdm_req_communication.c
library/spdm_requester_lib/libspdm_req_encap_error.c
library/spdm_requester_lib/libspdm_req_encap_request.c
library/spdm_requester_lib/libspdm_req_get_certificate.c
library/spdm_requester_lib/libspdm_req_get_csr.c
library/spdm_requester_lib/libspdm_req_get_digests.c
library/spdm_requester_lib/libspdm_req_get_measurements.c
library/spdm_requester_lib/libspdm_req_heartbeat.c
library/spdm_requester_lib/libspdm_req_key_update.c
library/spdm_requester_lib/libspdm_req_send_receive.c
library/spdm_requester_lib/libspdm_req_set_certificate.c

spdm_common_lib: Context Parameter Consistency.

---

include/internal/libspdm_common_lib.h
include/library/spdm_responder_lib.h
library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_common_lib/libspdm_com_context_data_session.c
library/spdm_common_lib/libspdm_com_crypto_service.c
library/spdm_common_lib/libspdm_com_crypto_service_session.c
library/spdm_common_lib/libspdm_com_msg_log.c
library/spdm_responder_lib/libspdm_rsp_communication.c
library/spdm_responder_lib/libspdm_rsp_encap_response.c
library/spdm_responder_lib/libspdm_rsp_error.c
library/spdm_responder_lib/libspdm_rsp_receive_send.c

spdm_responder_lib: Context Parameter Consistency

---

unit_test/test_crypt/rsa_verify.c

test_crypt: wrapper SHA256 by LIBSPDM_SHA256_SUPPORT_TEST.

---

include/internal/libspdm_requester_lib.h
include/internal/libspdm_responder_lib.h
library/spdm_requester_lib/libspdm_req_encap_certificate.c
library/spdm_requester_lib/libspdm_req_encap_challenge_auth.c
library/spdm_requester_lib/libspdm_req_encap_digests.c
library/spdm_requester_lib/libspdm_req_encap_key_update.c
library/spdm_requester_lib/libspdm_req_handle_error_response.c
library/spdm_responder_lib/libspdm_rsp_algorithms.c
library/spdm_responder_lib/libspdm_rsp_capabilities.c
library/spdm_responder_lib/libspdm_rsp_certificate.c
library/spdm_responder_lib/libspdm_rsp_challenge_auth.c
library/spdm_responder_lib/libspdm_rsp_chunk_get.c
library/spdm_responder_lib/libspdm_rsp_chunk_send_ack.c
library/spdm_responder_lib/libspdm_rsp_csr.c
library/spdm_responder_lib/libspdm_rsp_digests.c
library/spdm_responder_lib/libspdm_rsp_encap_response.c
library/spdm_responder_lib/libspdm_rsp_end_session.c
library/spdm_responder_lib/libspdm_rsp_finish.c
library/spdm_responder_lib/libspdm_rsp_handle_response_state.c
library/spdm_responder_lib/libspdm_rsp_heartbeat.c
library/spdm_responder_lib/libspdm_rsp_key_exchange.c
library/spdm_responder_lib/libspdm_rsp_key_update.c
library/spdm_responder_lib/libspdm_rsp_measurements.c
library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
library/spdm_responder_lib/libspdm_rsp_psk_finish.c
library/spdm_responder_lib/libspdm_rsp_respond_if_ready.c
library/spdm_responder_lib/libspdm_rsp_set_certificate.c
library/spdm_responder_lib/libspdm_rsp_version.c

Internal lib: Context Parameter Consistency

---

include/hal/library/cryptlib/cryptlib_cert.h
include/internal/libspdm_common_lib.h
include/library/spdm_common_lib.h
include/library/spdm_crypt_lib.h
include/library/spdm_lib_config.h
include/library/spdm_requester_lib.h
library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_common_lib/libspdm_com_crypto_service.c
library/spdm_common_lib/libspdm_com_crypto_service_session.c
library/spdm_requester_lib/libspdm_req_get_digests.c
library/spdm_responder_lib/libspdm_rsp_algorithms.c

Fix spelling errors in comments

---

library/spdm_responder_lib/libspdm_rsp_measurements.c

Fix potential unaligned access in rsp_measurements

---

include/internal/libspdm_requester_lib.h
include/library/spdm_requester_lib.h

Move libspdm_get_certificate_choose_length* to internal header

---

.github/workflows/build.yml

Print CMake version in CI/CD

---

.github/workflows/code_coverage.yml

Enable gcov's all_blocks for code coverage

---

include/internal/libspdm_fips_lib.h
library/spdm_crypt_lib/CMakeLists.txt
library/spdm_crypt_lib/fips/libspdm_get_selftest_result.c
library/spdm_crypt_lib/fips/libspdm_selftest_hkdf.c

Add hkdf self_test

---

include/internal/libspdm_fips_lib.h
library/spdm_crypt_lib/CMakeLists.txt
library/spdm_crypt_lib/fips/libspdm_get_selftest_result.c
library/spdm_crypt_lib/fips/libspdm_selftest_ecdh.c

Add ecdh self_test

---

include/internal/libspdm_common_lib.h

Resolves #1455
Signed-off-by: Ray Wang <ray.wang1@broadcom.com>

Allow override default dump functions

---

include/internal/libspdm_requester_lib.h
include/internal/libspdm_responder_lib.h
library/spdm_requester_lib/libspdm_req_common.c
library/spdm_requester_lib/libspdm_req_key_exchange.c
library/spdm_requester_lib/libspdm_req_psk_exchange.c
library/spdm_responder_lib/libspdm_rsp_common.c
library/spdm_responder_lib/libspdm_rsp_key_exchange.c
library/spdm_responder_lib/libspdm_rsp_psk_exchange.c

Remove return value from opaque build function

---

unit_test/test_spdm_requester/error_test/get_capabilities_err.c
unit_test/test_spdm_responder/capabilities.c

Add unit test for MaxSPDMmsgSize less than DataTransferSize.

---

unit_test/test_spdm_requester/get_certificate.c

Fix typo in GET_CERTIFICATE unit_test.

---

include/internal/libspdm_fips_lib.h
library/spdm_crypt_lib/CMakeLists.txt
library/spdm_crypt_lib/fips/libspdm_get_selftest_result.c
library/spdm_crypt_lib/fips/libspdm_selftest_ffdh.c

Add ffdh self_test

---

include/hal/library/cryptlib/cryptlib_ec.h
include/internal/libspdm_fips_lib.h
library/spdm_crypt_lib/CMakeLists.txt
library/spdm_crypt_lib/fips/libspdm_get_selftest_result.c
library/spdm_crypt_lib/fips/libspdm_selftest_ecdsa.c
os_stub/cryptlib_mbedtls/pk/ec.c
os_stub/cryptlib_openssl/pk/ec.c

**Both openssl and mbedtsl KAT and PCT test are passed.**

Add ecdsa self_test

---

unit_test/test_spdm_requester/get_certificate.c
unit_test/test_spdm_responder/certificate.c

Add unit test for Bad SlotID in CERTIFICATE message.

---

unit_test/test_spdm_requester/challenge.c

Add unit test for unrecommended OpaqueDataLength in CHALLENGE_AUTH message.

---

library/spdm_requester_lib/libspdm_req_challenge.c
library/spdm_requester_lib/libspdm_req_key_exchange.c
library/spdm_requester_lib/libspdm_req_psk_exchange.c

Check measurement_hash_type

---

library/spdm_requester_lib/libspdm_req_get_measurements.c
unit_test/test_spdm_requester/error_test/get_measurements_err.c

Unconditionally check content_changed in MEASUREMENTS response

---

doc/api/requester_api.md

This is far from the finished version, but I'd like to start a pull request to get feedback.

Initial rough draft for the Requester API documentation

---

include/library/spdm_common_lib.h
include/library/spdm_return_status.h
library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_common_lib/libspdm_com_context_data_session.c

Fix spelling

---

library/spdm_responder_lib/libspdm_rsp_challenge_auth.c
library/spdm_responder_lib/libspdm_rsp_chunk_get.c
library/spdm_responder_lib/libspdm_rsp_chunk_send_ack.c
library/spdm_responder_lib/libspdm_rsp_digests.c
library/spdm_responder_lib/libspdm_rsp_finish.c
library/spdm_responder_lib/libspdm_rsp_heartbeat.c
library/spdm_responder_lib/libspdm_rsp_key_exchange.c
library/spdm_responder_lib/libspdm_rsp_measurements.c
library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
library/spdm_responder_lib/libspdm_rsp_psk_finish.c
unit_test/test_spdm_responder/challenge_auth.c
unit_test/test_spdm_responder/chunk_get.c
unit_test/test_spdm_responder/chunk_send_ack.c
unit_test/test_spdm_responder/digests.c
unit_test/test_spdm_responder/finish.c
unit_test/test_spdm_responder/measurements.c
unit_test/test_spdm_responder/psk_finish.c

Fix incorrect error data.

---

library/spdm_transport_mctp_lib/libspdm_mctp_mctp.c

Check transport length in libspdm_mctp_encode_message()

---

os_stub/cryptlib_mbedtls/pk/x509.c
os_stub/cryptlib_openssl/pk/x509.c

Improve infinite loops

---

library/spdm_responder_lib/libspdm_rsp_chunk_send_ack.c
library/spdm_responder_lib/libspdm_rsp_measurements.c
unit_test/test_spdm_responder/chunk_send_ack.c
unit_test/test_spdm_responder/measurements.c

Fix incorrect use of UnsupportedRequest.

---

library/spdm_requester_lib/libspdm_req_encap_certificate.c
library/spdm_requester_lib/libspdm_req_encap_challenge_auth.c
library/spdm_requester_lib/libspdm_req_encap_digests.c
library/spdm_requester_lib/libspdm_req_encap_key_update.c

Fix incorrect error data of error code VersionMismatch.

---

doc/test.md
unit_test/fuzzing/fuzzing_AFLplusplus.sh

Fix: #1709 
In the test, on the same machine, the total  paths found by AFL++at the same time is faster than that by AFL

added fuzz guide and AFL++ patch

---

unit_test/fuzzing/spdm_unit_fuzzing_common/toolchain_harness.c

Fix LIBFUZZER warning

---

library/spdm_responder_lib/libspdm_rsp_finish.c

Fix: #1770 
Fix: #1771 
Fix: #1772

FINISH.Param2 only valid if FINISH.Param1 == 0x01.

---

include/library/spdm_secured_message_lib.h
include/library/spdm_transport_mctp_lib.h
library/spdm_transport_mctp_lib/libspdm_mctp_mctp.c
library/spdm_transport_pcidoe_lib/libspdm_doe_pcidoe.c
unit_test/include/library/spdm_transport_test_lib.h
unit_test/spdm_transport_test_lib/test.c

Fix typo randum -> random

---

.uncrustify.cfg

Fix uncrustify warnings

---

library/spdm_requester_lib/libspdm_req_get_measurements.c

Add additional check to `MEASUREMENTS` validation

---

library/spdm_responder_lib/libspdm_rsp_receive_send.c

Fix function pointer check.

---

library/spdm_requester_lib/libspdm_req_get_csr.c

Add check for libspdm_try_get_csr.

---

library/spdm_common_lib/libspdm_com_context_data.c

Check type in libspdm_{set,get}_data

---

library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c

Remove unneeded aead_pad_size.

---

doc/api/responder_api.md

This document will be updated in a subsequent pull request.

Initial draft for Responder API document

---

doc/programming_environment.md

Specify architecture size

---

library/spdm_common_lib/libspdm_com_crypto_service.c
library/spdm_requester_lib/libspdm_req_get_measurements.c
library/spdm_requester_lib/libspdm_req_handle_error_response.c
library/spdm_requester_lib/libspdm_req_key_exchange.c
library/spdm_requester_lib/libspdm_req_psk_exchange.c
library/spdm_responder_lib/libspdm_rsp_finish.c
library/spdm_responder_lib/libspdm_rsp_psk_finish.c

Fix https://github.com/DMTF/libspdm/issues/1661

Correct debug message level

---

library/spdm_requester_lib/libspdm_req_get_certificate.c
library/spdm_responder_lib/libspdm_rsp_encap_get_certificate.c

Check integer overflow.

---

library/spdm_requester_lib/libspdm_req_get_certificate.c
library/spdm_responder_lib/libspdm_rsp_encap_get_certificate.c

Fix: #1773
Signed-off-by: Wenxing Hou [wenxing.hou@intel.com](mailto:wenxing.hou@intel.com)

Cert check should continue after authority check failed

---

unit_test/test_spdm_responder/encap_response.c

message with a ResponseNotReady in encapsulated request flow.

Add unit test for requester deliver an encapsulated ERROR

---

doc/api/requester_api.md
include/industry_standard/spdm.h
library/spdm_requester_lib/libspdm_req_get_certificate.c

Require Integrator to provide certificate chain buffer

---

include/internal/libspdm_requester_lib.h
include/library/spdm_requester_lib.h
library/spdm_requester_lib/libspdm_req_communication.c

Split `libspdm_send_receive_data` into separate functions

---

include/hal/library/cryptlib/cryptlib_ec.h
library/spdm_crypt_lib/fips/libspdm_selftest_ecdh.c
library/spdm_crypt_lib/fips/libspdm_selftest_ffdh.c
os_stub/spdm_crypt_ext_lib/cryptlib_ext.h

Move function declaration to include

---

include/library/spdm_common_lib.h
include/library/spdm_lib_config.h

Fix https://github.com/DMTF/libspdm/issues/1660

move LIBSPDM_SCRATCH_BUFFER_SIZE to spdm_common_lib.h

---

include/internal/libspdm_common_lib.h
include/library/spdm_lib_config.h
library/spdm_crypt_lib/libspdm_crypt_cert.c
unit_test/fuzzing/test_requester/test_spdm_requester_challenge/challenge.c
unit_test/fuzzing/test_responder/test_spdm_responder_encap_challenge/encap_challenge.c
unit_test/test_spdm_requester/chunk_get.c
unit_test/test_spdm_requester/error_test/get_capabilities_err.c
unit_test/test_spdm_requester/error_test/get_version_err.c
unit_test/test_spdm_requester/error_test/negotiate_algorithms_err.c
unit_test/test_spdm_requester/get_capabilities.c
unit_test/test_spdm_requester/get_version.c
unit_test/test_spdm_requester/negotiate_algorithms.c

Fix: https://github.com/DMTF/libspdm/issues/1659

Cleanup SMALL_BUFFER_SIZE and MEDIUM_BUFFER_SIZE

---

include/internal/libspdm_common_lib.h
library/spdm_common_lib/libspdm_com_crypto_service.c
library/spdm_common_lib/libspdm_com_crypto_service_session.c
library/spdm_requester_lib/libspdm_req_get_measurements.c
library/spdm_responder_lib/libspdm_rsp_measurements.c
unit_test/fuzzing/test_requester/test_spdm_requester_key_exchange/key_exchange.c
unit_test/fuzzing/test_requester/test_spdm_requester_psk_exchange/psk_exchange.c
unit_test/fuzzing/test_responder/test_spdm_responder_encap_get_certificate/encap_get_certificate.c
unit_test/fuzzing/test_responder/test_spdm_responder_finish_rsp/finish_rsp.c
unit_test/fuzzing/test_responder/test_spdm_responder_psk_finish_rsp/psk_finish_rsp.c
unit_test/test_spdm_requester/error_test/key_exchange_err.c
unit_test/test_spdm_requester/finish.c
unit_test/test_spdm_requester/key_exchange.c
unit_test/test_spdm_requester/psk_exchange.c
unit_test/test_spdm_responder/encap_get_certificate.c
unit_test/test_spdm_responder/finish.c
unit_test/test_spdm_responder/psk_finish.c
unit_test/test_spdm_responder/respond_if_ready.c

Fix: https://github.com/DMTF/libspdm/issues/1659

Prepare to remove libspdm_large_managed_buffer_t.

---

unit_test/test_spdm_responder/algorithms.c

Fix: #1839
Fix: #1841
Fix: #1847

Fix ALGORITHMS related unit test issue.

---

include/internal/libspdm_common_lib.h
include/internal/libspdm_requester_lib.h
include/internal/libspdm_responder_lib.h
include/library/spdm_common_lib.h
library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_common_lib/libspdm_com_context_data_session.c
library/spdm_requester_lib/libspdm_req_common.c
library/spdm_requester_lib/libspdm_req_key_exchange.c
library/spdm_requester_lib/libspdm_req_psk_exchange.c
library/spdm_responder_lib/libspdm_rsp_common.c
library/spdm_responder_lib/libspdm_rsp_key_exchange.c
library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
unit_test/test_spdm_common/context_data.c
unit_test/test_spdm_requester/error_test/key_exchange_err.c
unit_test/test_spdm_requester/key_exchange.c
unit_test/test_spdm_requester/psk_exchange.c

Fix https://github.com/DMTF/libspdm/issues/1860
Fix https://github.com/DMTF/libspdm/issues/1887

Add max_dhe/psk_session_count support

---

include/internal/libspdm_common_lib.h
include/library/spdm_lib_config.h
unit_test/fuzzing/spdm_unit_fuzzing_common/spdm_unit_fuzzing.h
unit_test/spdm_unit_test_common/spdm_unit_test.h

Fix https://github.com/DMTF/libspdm/issues/1893

move LIBSPDM_MAX_MESSAGE_x_BUFFER_SIZE into RECORD_TRANSCRIPT_DATA_SUPPORT

---

include/internal/libspdm_common_lib.h
include/internal/libspdm_requester_lib.h
include/library/spdm_common_lib.h
include/library/spdm_requester_lib.h
library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_requester_lib/libspdm_req_communication.c
library/spdm_requester_lib/libspdm_req_psk_exchange.c
unit_test/fuzzing/test_requester/test_spdm_requester_end_session/end_session.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_measurements/get_measurements.c
unit_test/fuzzing/test_requester/test_spdm_requester_heartbeat/heartbeat.c
unit_test/fuzzing/test_requester/test_spdm_requester_psk_exchange/psk_exchange.c
unit_test/fuzzing/test_requester/test_spdm_requester_psk_finish/psk_finish.c
unit_test/fuzzing/test_responder/test_spdm_responder_end_session/end_session.c
unit_test/fuzzing/test_responder/test_spdm_responder_heartbeat_ack/heartbeat_ack.c
unit_test/fuzzing/test_responder/test_spdm_responder_measurements/measurements.c
unit_test/fuzzing/test_responder/test_spdm_responder_psk_exchange_rsp/psk_exchange_rsp.c
unit_test/fuzzing/test_responder/test_spdm_responder_psk_finish_rsp/psk_finish_rsp.c
unit_test/test_size/test_size_of_spdm_requester/spdm_requester_session.c
unit_test/test_spdm_requester/end_session.c
unit_test/test_spdm_requester/get_measurements.c
unit_test/test_spdm_requester/heartbeat.c
unit_test/test_spdm_requester/psk_exchange.c
unit_test/test_spdm_requester/psk_finish.c
unit_test/test_spdm_responder/end_session.c
unit_test/test_spdm_responder/heartbeat.c
unit_test/test_spdm_responder/measurements.c
unit_test/test_spdm_responder/psk_exchange.c
unit_test/test_spdm_responder/psk_finish.c
unit_test/test_spdm_responder/respond_if_ready.c

Fix https://github.com/DMTF/libspdm/issues/1878

Add PSK in libspdm_start_session(), remove PSK in context provision

---

include/library/spdm_common_lib.h
include/library/spdm_lib_config.h
unit_test/fuzzing/spdm_unit_fuzzing_common/spdm_unit_fuzzing.h
unit_test/spdm_unit_test_common/spdm_unit_test.h
unit_test/test_size/test_size_of_spdm_requester/spdm_requester_init.c
unit_test/test_size/test_size_of_spdm_responder/spdm_responder_init.c

Fix https://github.com/DMTF/libspdm/issues/1900

move LIBSPDM_MAX_SENDER_RECEIVER_BUFFER_SIZE to test only

---

library/spdm_requester_lib/libspdm_req_psk_exchange.c
unit_test/fuzzing/test_requester/test_spdm_requester_psk_exchange/psk_exchange.c
unit_test/test_spdm_requester/psk_exchange.c

Fix https://github.com/DMTF/libspdm/issues/1855

Add PSK_CAP and context check

---

doc/api/secured_message_api.md

Initial draft for secured message API

---

library/spdm_responder_lib/libspdm_rsp_receive_send.c

Add checking the status that get_response_func () function returned.

---

library/spdm_secured_message_lib/libspdm_secmes_context_data.c

Fix https://github.com/DMTF/libspdm/issues/1906

remove redundant assert.

---

include/library/spdm_common_lib.h
library/spdm_common_lib/libspdm_com_context_data.c
unit_test/fuzzing/spdm_unit_fuzzing_common/common.c
unit_test/spdm_unit_test_common/common.c
unit_test/test_size/test_size_of_spdm_requester/spdm_requester_init.c
unit_test/test_size/test_size_of_spdm_responder/spdm_responder_init.c
unit_test/test_spdm_common/context_data.c

Fix https://github.com/DMTF/libspdm/issues/1910

make sender_buffer_size and receiver_buffer_size static

---

library/spdm_responder_lib/libspdm_rsp_chunk_send_ack.c
library/spdm_responder_lib/libspdm_rsp_csr.c

fix improper usage for MAX_SPDM_MSG_SIZE

---

library/spdm_common_lib/libspdm_com_context_data.c

Fix https://github.com/DMTF/libspdm/issues/1939

Fix missing CHUNK cap macro check.

---

include/library/spdm_crypt_lib.h

Fix header documentation for `libspdm_get_leaf_cert_public_key_from_cert_chain`

---

include/industry_standard/spdm_secured_message.h
library/spdm_common_lib/libspdm_com_context_data.c

Add SPDM_MAX_SECURED_VERSION_COUNT MACRO

---

unit_test/test_spdm_responder/receive_send.c

Fix wrong buffer size retrieving

---

doc/api/common_api.md
doc/api/requester_api.md
doc/api/responder_api.md

Will revisit this before release.

Initial draft for common API

---

include/library/spdm_secured_message_lib.h

Cleanup `spdm_secured_message_lib` header

---

os_stub/cryptlib_openssl/CMakeLists.txt

Fix arm build error when openssl is updated

---

library/spdm_common_lib/libspdm_com_context_data.c
unit_test/test_spdm_requester/get_certificate.c

Add spdm cert_chain format process when set data

---

include/library/spdm_common_lib.h

Remove LIBSPDM_DATA_LOCAL_SLOT_COUNT

---

library/spdm_common_lib/libspdm_com_context_data.c

Add check for slot_id

---

unit_test/spdm_transport_test_lib/common.c
unit_test/spdm_transport_test_lib/test.c

Fix https://github.com/DMTF/libspdm/issues/1924

add check for transport for test.

---

include/hal/library/responder_secretlib.h
include/internal/libspdm_common_lib.h
library/spdm_responder_lib/libspdm_rsp_measurements.c
os_stub/spdm_device_secret_lib_null/lib.c
os_stub/spdm_device_secret_lib_sample/lib.c
unit_test/fuzzing/test_responder/test_spdm_responder_measurements/measurements.c
unit_test/test_spdm_responder/CMakeLists.txt
unit_test/test_spdm_responder/measurements.c
unit_test/test_spdm_responder/respond_if_ready.c

Collect opaque data from secretlib

---

library/spdm_common_lib/libspdm_com_context_data.c

Fix: https://github.com/DMTF/libspdm/issues/1936

support ct_exponent setting for peer

---

library/spdm_responder_lib/libspdm_rsp_version.c

Fix https://github.com/DMTF/libspdm/issues/1987

add check for GET_VERSION in session.

---

library/spdm_responder_lib/libspdm_rsp_finish.c
library/spdm_responder_lib/libspdm_rsp_psk_finish.c

Reference: DMTF-2023-0001
Fix: https://github.com/DMTF/libspdm/issues/2005

Add handshake mode switch check in FINISH and PSK_FINISH.

---

include/internal/libspdm_requester_lib.h
include/library/spdm_requester_lib.h
library/spdm_requester_lib/libspdm_req_challenge.c
library/spdm_requester_lib/libspdm_req_communication.c
library/spdm_requester_lib/libspdm_req_get_measurements.c
library/spdm_requester_lib/libspdm_req_key_exchange.c
library/spdm_requester_lib/libspdm_req_psk_exchange.c
unit_test/fuzzing/test_requester/test_spdm_requester_challenge/challenge.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_measurements/get_measurements.c
unit_test/fuzzing/test_requester/test_spdm_requester_key_exchange/key_exchange.c
unit_test/fuzzing/test_requester/test_spdm_requester_psk_exchange/psk_exchange.c
unit_test/test_spdm_requester/challenge.c
unit_test/test_spdm_requester/get_measurements.c
unit_test/test_spdm_requester/key_exchange.c

Allow Integrator to retrieve opaque data

---

library/spdm_common_lib/libspdm_com_crypto_service.c
library/spdm_crypt_lib/libspdm_crypt_cert.c
os_stub/spdm_device_secret_lib_sample/cert.c

Responder does not determine Requester's certificate model

---

library/spdm_responder_lib/libspdm_rsp_measurements.c
unit_test/test_spdm_responder/measurements.c
unit_test/test_spdm_responder/receive_send.c

Fix: https://github.com/DMTF/SPDM-Responder-Validator/issues/72

Add slot_id check in responder measurements

---

unit_test/test_spdm_responder/receive_send.c

Fix unit_test when add cert porvision check for measurement

---

library/spdm_requester_lib/libspdm_req_handle_error_response.c
unit_test/test_spdm_requester/challenge.c
unit_test/test_spdm_requester/end_session.c
unit_test/test_spdm_requester/error_test/get_capabilities_err.c
unit_test/test_spdm_requester/error_test/get_digests_err.c
unit_test/test_spdm_requester/error_test/get_measurements_err.c
unit_test/test_spdm_requester/error_test/get_version_err.c
unit_test/test_spdm_requester/error_test/key_exchange_err.c
unit_test/test_spdm_requester/error_test/negotiate_algorithms_err.c
unit_test/test_spdm_requester/finish.c
unit_test/test_spdm_requester/get_capabilities.c
unit_test/test_spdm_requester/get_certificate.c
unit_test/test_spdm_requester/get_digests.c
unit_test/test_spdm_requester/get_measurements.c
unit_test/test_spdm_requester/get_version.c
unit_test/test_spdm_requester/heartbeat.c
unit_test/test_spdm_requester/key_exchange.c
unit_test/test_spdm_requester/key_update.c
unit_test/test_spdm_requester/negotiate_algorithms.c
unit_test/test_spdm_requester/psk_exchange.c
unit_test/test_spdm_requester/psk_finish.c

Requester need check RDTM

---

.github/workflows/build.yml
os_stub/debuglib/debuglib.c

fix running CI/CD, hit LIBSPDM_ ASSERT did not exit

---

.github/workflows/code_coverage.yml

Add FIPS to code coverage

---

library/spdm_requester_lib/libspdm_req_get_csr.c
library/spdm_requester_lib/libspdm_req_handle_error_response.c
os_stub/cryptlib_openssl/pk/x509.c

Make csr_len check right

---

include/library/spdm_return_status.h
library/spdm_requester_lib/libspdm_req_send_receive.c
unit_test/test_spdm_requester/chunk_send.c

Handle requester message too large

---

include/hal/library/cryptlib/cryptlib_cert.h
include/hal/library/responder_secretlib.h
include/library/spdm_lib_config.h
library/spdm_responder_lib/libspdm_rsp_csr.c
os_stub/cryptlib_mbedtls/pk/x509.c
os_stub/cryptlib_null/pk/x509.c
os_stub/cryptlib_openssl/pk/x509.c
os_stub/spdm_crypt_ext_lib/cryptlib_ext.h
os_stub/spdm_device_secret_lib_null/lib.c
os_stub/spdm_device_secret_lib_sample/lib.c
unit_test/fuzzing/test_requester/test_spdm_requester_get_csr/get_csr.c
unit_test/test_spdm_requester/get_csr.c
unit_test/test_spdm_responder/csr.c

Fix: #2002 
Commit1:
1.add opaque data input;
2.change Change uint8_t **csr_pointer to uint8_t *csr_pointer;
3.delete LIBSPDM_MAX_CSR_SIZE;
Commit2: 
Fix unit_test after enhance gen_csr api;

Enhance gen csr API

---

library/spdm_requester_lib/libspdm_req_get_csr.c
library/spdm_responder_lib/libspdm_rsp_csr.c
unit_test/test_spdm_requester/get_csr.c
unit_test/test_spdm_responder/csr.c

Fix byte offset mismatch in OpaqueData field in GET_CSR request message format 

---

include/internal/libspdm_common_lib.h
library/spdm_common_lib/libspdm_com_opaque_data.c
library/spdm_requester_lib/libspdm_req_challenge.c
library/spdm_requester_lib/libspdm_req_get_measurements.c
library/spdm_responder_lib/libspdm_rsp_csr.c
unit_test/test_spdm_requester/challenge.c
unit_test/test_spdm_requester/get_measurements.c
unit_test/test_spdm_responder/csr.c

OpaqueData field shall conform to the selected opaque data format in OtherParamsSelection

---

include/internal/libspdm_common_lib.h
library/spdm_requester_lib/libspdm_req_get_capabilities.c
library/spdm_requester_lib/libspdm_req_handle_error_response.c
library/spdm_requester_lib/libspdm_req_send_receive.c
library/spdm_responder_lib/libspdm_rsp_capabilities.c
unit_test/test_spdm_requester/error_test/get_capabilities_err.c
unit_test/test_spdm_responder/capabilities.c

Prevent undefined behavior

---

library/spdm_responder_lib/libspdm_rsp_measurements.c
unit_test/test_spdm_responder/measurements.c

Fix measurement signature generate input

---

include/hal/library/responder_secretlib.h
library/spdm_requester_lib/libspdm_req_challenge.c
library/spdm_responder_lib/libspdm_rsp_challenge_auth.c
library/spdm_responder_lib/libspdm_rsp_encap_challenge.c
library/spdm_responder_lib/libspdm_rsp_key_exchange.c
library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
os_stub/spdm_device_secret_lib_null/lib.c
os_stub/spdm_device_secret_lib_sample/lib.c
unit_test/test_spdm_responder/key_exchange.c
unit_test/test_spdm_responder/psk_exchange.c

Make measurement_summary_hash_size type consistent

---

include/internal/libspdm_common_lib.h
library/spdm_common_lib/libspdm_com_opaque_data.c
library/spdm_requester_lib/libspdm_req_key_exchange.c
library/spdm_requester_lib/libspdm_req_psk_exchange.c
library/spdm_responder_lib/libspdm_rsp_key_exchange.c
library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
unit_test/test_spdm_requester/key_exchange.c
unit_test/test_spdm_requester/psk_exchange.c
unit_test/test_spdm_responder/key_exchange.c
unit_test/test_spdm_responder/psk_exchange.c

Add libspdm_process_general_opaque_data_check  to KEY_EXCHANGE / PSK_EXCHANGE

---

library/spdm_responder_lib/libspdm_rsp_key_exchange.c
library/spdm_responder_lib/libspdm_rsp_psk_exchange.c

Fix missing calling libspdm_free_session_id function.

---

include/internal/libspdm_common_lib.h
library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_responder_lib/libspdm_rsp_encap_get_certificate.c
library/spdm_responder_lib/libspdm_rsp_encap_response.c
library/spdm_responder_lib/libspdm_rsp_receive_send.c
unit_test/fuzzing/test_responder/test_spdm_responder_encap_get_certificate/encap_get_certificate.c
unit_test/test_spdm_responder/encap_get_certificate.c

Move Responder's certificate chain buffer

---

unit_test/test_spdm_responder/challenge_auth.c

fix wrong request variable name

---

include/hal/library/responder_platformlib.h
include/hal/library/responder_secretlib.h
library/spdm_requester_lib/libspdm_req_set_certificate.c
library/spdm_responder_lib/libspdm_rsp_set_certificate.c
os_stub/spdm_device_secret_lib_null/lib.c
os_stub/spdm_device_secret_lib_sample/lib.c
unit_test/test_spdm_requester/set_certificate.c
unit_test/test_spdm_responder/set_certificate_rsp.c

Fix https://github.com/DMTF/libspdm/issues/2077

Fix Set cert slot number check.

---

library/spdm_requester_lib/libspdm_req_challenge.c
library/spdm_requester_lib/libspdm_req_finish.c
library/spdm_requester_lib/libspdm_req_get_capabilities.c
library/spdm_requester_lib/libspdm_req_get_certificate.c
library/spdm_requester_lib/libspdm_req_get_digests.c
library/spdm_requester_lib/libspdm_req_get_measurements.c
library/spdm_requester_lib/libspdm_req_key_exchange.c
library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c
library/spdm_requester_lib/libspdm_req_psk_exchange.c
library/spdm_requester_lib/libspdm_req_psk_finish.c

Fix https://github.com/DMTF/libspdm/issues/2119

propagate error code from libspdm_append_message_x.

---

unit_test/test_spdm_requester/challenge.c
unit_test/test_spdm_requester/encap_challenge_auth.c
unit_test/test_spdm_responder/challenge_auth.c
unit_test/test_spdm_responder/encap_challenge.c

Update unit test to check Completion of CHALLENGE sets M1/M2 to null.

---

library/spdm_requester_lib/libspdm_req_get_measurements.c
library/spdm_responder_lib/libspdm_rsp_measurements.c

fix: https://github.com/DMTF/libspdm/issues/2114

reset L1/L2 in case of error

---

unit_test/test_spdm_responder/measurements.c

Fix `libspdm_test_responder_measurements_case22` version mismatch

---

library/spdm_requester_lib/libspdm_req_send_receive.c
library/spdm_responder_lib/libspdm_rsp_receive_send.c

Fix https://github.com/DMTF/libspdm/issues/2081
Fix https://github.com/DMTF/libspdm/issues/2082

Free session_id case of error in session error

---

library/spdm_responder_lib/libspdm_rsp_psk_exchange.c

Fix https://github.com/DMTF/libspdm/issues/2135

start watchdog in case of PSK without context.

---

README.md
os_stub/openssllib/CMakeLists.txt
os_stub/openssllib/openssl_gen/openssl/opensslv.h
os_stub/openssllib/version.txt

Fix https://github.com/DMTF/libspdm/issues/2138

update to openssl 3.0.9

---

library/spdm_common_lib/libspdm_com_context_data.c

Fix https://github.com/DMTF/libspdm/issues/2107

Fix CERT_PARSER build error.

---

library/spdm_requester_lib/libspdm_req_send_receive.c
library/spdm_responder_lib/libspdm_rsp_chunk_get.c
library/spdm_responder_lib/libspdm_rsp_chunk_send_ack.c

Fix https://github.com/DMTF/libspdm/issues/2141
Fix https://github.com/DMTF/libspdm/issues/2145

Fix Chunk issue

---

include/industry_standard/spdm.h

Fix https://github.com/DMTF/libspdm/issues/2132

define SPDM_MAX_CSR_SIZE

---

library/spdm_common_lib/libspdm_com_context_data.c

Add line break

---

library/spdm_responder_lib/libspdm_rsp_set_certificate.c
os_stub/spdm_device_secret_lib_sample/lib.c
unit_test/test_spdm_responder/csr.c

Fix: #2061
The current code meet the follow table.

Make need_reset for get_csr and set_cert clear

---

library/spdm_responder_lib/libspdm_rsp_receive_send.c

Return RESPONSE_TOO_LARGE if ChunkCap is unsupported.

---

library/spdm_requester_lib/libspdm_req_encap_challenge_auth.c

Fix https://github.com/DMTF/libspdm/issues/2172

Check CHALLENGE.Param2 during basic mutual auth

---

include/hal/library/debuglib.h
include/hal/library/memlib.h
os_stub/memlib/copy_mem.c
os_stub/memlib/set_mem.c
os_stub/memlib/zero_mem.c

memlib enhancements

---

os_stub/spdm_device_secret_lib_sample/lib.c
unit_test/spdm_unit_test_common/support.c
unit_test/test_spdm_responder/set_certificate_rsp.c

Add unit_test for set_cert to check overwrite same slot_id

---

library/spdm_requester_lib/libspdm_req_send_receive.c

Fix https://github.com/DMTF/libspdm/issues/2181

Add error checking for chunk EARLY_ERROR_DETECTED.

---

unit_test/test_spdm_requester/challenge.c

~~Two~~ One assorted cleanup for debug code which has accumulated on my development branch:
- Elimination of superfluous code in a unit test
- ~~Addition of ASCII output to hex dumps~~
Thanks!

Clean up unit test

---

include/library/spdm_common_lib.h
library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_requester_lib/libspdm_req_send_receive.c

Fix message logging bugs

---

doc/changelog.md

Create 3.0 change log

---

doc/api/common_api.md
include/internal/libspdm_common_lib.h
library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_responder_lib/libspdm_rsp_end_session.c
unit_test/test_spdm_responder/end_session.c

Retrieve NSPI from spdm_context without session ID

---

VERSION.md

Signed-off-by： Jiewen Yao <jiewen.yao@intel.com>

prepare 3.0.0 pre-release

---

library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_responder_lib/libspdm_rsp_receive_send.c

Fix https://github.com/DMTF/libspdm/issues/2207

Rsp check max_spdm_msg_size size to avoid assert

---

library/spdm_requester_lib/libspdm_req_send_receive.c

Fix https://github.com/DMTF/libspdm/issues/2206

req check max_spdm_msg_size to avoid assert.

---

doc/design.md
doc/threat_model.md
doc/user_guide.md

Fix https://github.com/DMTF/libspdm/issues/2217
Fix https://github.com/DMTF/libspdm/issues/2215

update doc according to the new API.

---

doc/user_guide.md

Fix https://github.com/DMTF/libspdm/issues/2228

Clean up user guide.

---

doc/fips.md

Fix https://github.com/DMTF/libspdm/issues/2219

Add FIPS doc

---

doc/crypto_endianness.md

Fix https://github.com/DMTF/libspdm/issues/2220

Add endianness clarification.

---

doc/raw_public_key.md

Fix https://github.com/DMTF/libspdm/issues/2233

Add raw public key doc.

---

doc/api/common_api.md

Document `MAX_SPDM_SESSION_SEQUENCE_NUMBER`

---

doc/programming_environment.md

Document assertions

---

library/spdm_responder_lib/libspdm_rsp_algorithms.c
library/spdm_responder_lib/libspdm_rsp_capabilities.c
library/spdm_responder_lib/libspdm_rsp_certificate.c
library/spdm_responder_lib/libspdm_rsp_challenge_auth.c
library/spdm_responder_lib/libspdm_rsp_csr.c
library/spdm_responder_lib/libspdm_rsp_digests.c
library/spdm_responder_lib/libspdm_rsp_finish.c
library/spdm_responder_lib/libspdm_rsp_heartbeat.c
library/spdm_responder_lib/libspdm_rsp_key_exchange.c
library/spdm_responder_lib/libspdm_rsp_key_update.c
library/spdm_responder_lib/libspdm_rsp_measurements.c
library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
library/spdm_responder_lib/libspdm_rsp_psk_finish.c
library/spdm_responder_lib/libspdm_rsp_respond_if_ready.c
library/spdm_responder_lib/libspdm_rsp_set_certificate.c
library/spdm_responder_lib/libspdm_rsp_version.c

Add request code assertions

---

library/spdm_responder_lib/libspdm_rsp_version.c
unit_test/test_spdm_responder/version.c

Ensure error version of 1.0

---

os_stub/cryptlib_mbedtls/cipher/aead_aes_gcm.c
os_stub/cryptlib_mbedtls/cipher/aead_chacha20_poly1305.c
os_stub/cryptlib_mbedtls/der/der.c
os_stub/cryptlib_mbedtls/hash/sha.c
os_stub/cryptlib_mbedtls/hmac/hmac_sha.c
os_stub/cryptlib_mbedtls/kdf/hkdf_sha.c
os_stub/cryptlib_mbedtls/pem/pem.c
os_stub/cryptlib_mbedtls/pk/dh.c
os_stub/cryptlib_mbedtls/pk/ec.c
os_stub/cryptlib_mbedtls/pk/rsa_basic.c
os_stub/cryptlib_mbedtls/pk/rsa_ext.c
os_stub/cryptlib_mbedtls/pk/x509.c

Use correct return type

---

doc/fips.md

Fix https://github.com/DMTF/libspdm/issues/2257

Fix FIPS document

---

library/spdm_crypt_lib/fips/libspdm_selftest_rsa_ssa.c

Fix wrong debug message for libspdm_selftest_rsa_ssa

---

include/internal/libspdm_common_lib.h
library/spdm_common_lib/libspdm_com_crypto_service.c
unit_test/test_spdm_common/context_data.c

Move `libspdm_verify_peer_cert_chain_buffer` to unit_test

---

doc/programming_environment.md
include/library/spdm_crypt_lib.h
library/spdm_crypt_lib/fips/libspdm_selftest.c
os_stub/spdm_device_secret_lib_sample/cert.c
os_stub/spdm_device_secret_lib_sample/lib.c

A bit of housekeeping to cleanup some typos :)

miscellaneous: fixup typos across libspdm

---

include/library/spdm_common_lib.h
include/library/spdm_secured_message_lib.h
library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c
library/spdm_transport_mctp_lib/libspdm_mctp_common.c
library/spdm_transport_pcidoe_lib/libspdm_doe_common.c
unit_test/spdm_transport_test_lib/common.c

Fix https://github.com/DMTF/libspdm/issues/2306

rename is_requester to is_requester_message for encode/decode

---

os_stub/cryptlib_openssl/pk/ec.c

The OpenSSL source code describes the crypto include as:
"Internal EC functions for other submodules: not for application use"
- https://github.com/openssl/openssl/blob/master/include/crypto/ec.h
Using the internal APIs makes it difficult to use libspdm as a library
with other packages. So let's remove the uses of the internal API and
instead use the public API.
We can also assume that the internal APIs don't provide backwards
compatible guarantees

cryptlib_openssl: ec: Remove internal OpenSSL crypto include

---

os_stub/cryptlib_mbedtls/pk/rsa_ext.c
unit_test/test_crypt/rsa_verify.c

Fix: #2336
Fix `libspdm_rsa_generate_key` always using the default key and add unit_test for `libspdm_rsa_generate_key`.

Fix libspdm_rsa_generate_key always using the default key

---

include/hal/library/cryptlib/cryptlib_rsa.h
os_stub/spdm_crypt_ext_lib/cryptlib_ext.h

Move libspdm_rsa_generate_key to os_stub

---

include/hal/library/cryptlib/cryptlib_rsa.h
os_stub/spdm_crypt_ext_lib/cryptlib_ext.h

Move rsa_check_key and rsa_get_key to os_stub

---

library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c
library/spdm_responder_lib/libspdm_rsp_algorithms.c
unit_test/test_spdm_requester/chunk_get.c
unit_test/test_spdm_requester/chunk_send.c
unit_test/test_spdm_responder/algorithms.c

This addresses the issues discussed in  #2344.

req/resp: improve conformance for negotiating algorithms

---

include/internal/libspdm_common_lib.h
unit_test/test_spdm_common/CMakeLists.txt
unit_test/test_spdm_common/support.c
unit_test/test_spdm_common/test_spdm_common.c

Add little-endian to big-endian function

---

os_stub/memlib/zero_mem.c

Enhance libspdm_zero_mem by using more secured api

---

include/internal/libspdm_common_lib.h
include/internal/libspdm_secured_message_lib.h
include/library/spdm_common_lib.h
library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_common_lib/libspdm_com_context_data_session.c
library/spdm_secured_message_lib/libspdm_secmes_context_data.c
library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c

Specify sequence number endianness

---

library/spdm_requester_lib/libspdm_req_get_csr.c
library/spdm_requester_lib/libspdm_req_handle_error_response.c
library/spdm_requester_lib/libspdm_req_set_certificate.c

Remove 1.2.1 capability checks from Requester

---

doc/api/common_api.md
include/library/spdm_common_lib.h
library/spdm_common_lib/libspdm_com_context_data.c

Add API documentation for endianness

---

README.md
doc/aead_limit.md
doc/crypto_endianness.md
doc/raw_public_key.md

Fix up documentation before 3.1 release

---

library/spdm_crypt_lib/libspdm_crypt_asym.c
unit_test/test_spdm_crypt/test_spdm_crypt.c

Fix for wrong endian determination when signature is same for both

---

VERSION.md
include/library/spdm_common_lib.h

Update version information for 3.1.1 release

---

VERSION.md
include/library/spdm_common_lib.h

Update version information to unreleased 3.2

---

os_stub/spdm_device_secret_lib_sample/lib.c

Fix https://github.com/DMTF/libspdm/issues/2404

fix measurement summary hash calculation.

---

library/spdm_requester_lib/libspdm_req_get_capabilities.c
library/spdm_responder_lib/libspdm_rsp_capabilities.c

Add version check code for some fields in GET_CAPABILITIES and CAPABLITIES messages

---

include/industry_standard/spdm.h
include/library/spdm_requester_lib.h
library/spdm_requester_lib/libspdm_req_get_measurements.c
library/spdm_responder_lib/libspdm_rsp_measurements.c

Fix https://github.com/DMTF/libspdm/issues/2283

Add 1.3 support for measurements

---

unit_test/sample_key/openssl.cnf

Delete duplicate openssl.cnf

---

unit_test/test_spdm_responder/measurements.c

Regarding #2449, unit tests should add checks for `OpaqueData `content

Enhance unit test measurements_case27

---

library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_requester_lib/libspdm_req_get_version.c
library/spdm_responder_lib/libspdm_rsp_version.c

Fix https://github.com/DMTF/libspdm/issues/2465

Fix Message D calculation - only first Msg counts.

---

library/spdm_requester_lib/libspdm_req_get_capabilities.c
library/spdm_responder_lib/libspdm_rsp_capabilities.c

Fix https://github.com/DMTF/libspdm/issues/2466

Add multi-key and pub_key_id exclusive check

---

include/internal/libspdm_common_lib.h
library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_requester_lib/libspdm_req_encap_request.c
library/spdm_responder_lib/libspdm_rsp_encap_response.c

Relax capabilities check for encapsulated messages

---

library/spdm_requester_lib/libspdm_req_get_capabilities.c

Fix https://github.com/DMTF/libspdm/issues/2478

forbid PUB_KEY_ID with GET_KEY_PAIR_INFO or SET_KEY_PAIR_INFO

---

library/spdm_requester_lib/libspdm_req_get_certificate.c
library/spdm_responder_lib/libspdm_rsp_encap_get_certificate.c

Fix https://github.com/DMTF/libspdm/issues/2498

relax cert_model check for cert.

---

library/spdm_requester_lib/libspdm_req_get_certificate.c
library/spdm_requester_lib/libspdm_req_get_digests.c
library/spdm_responder_lib/libspdm_rsp_encap_get_certificate.c
library/spdm_responder_lib/libspdm_rsp_encap_get_digests.c
unit_test/test_spdm_requester/get_digests.c
unit_test/test_spdm_responder/encap_get_digests.c

Fix https://github.com/DMTF/libspdm/issues/2490
Fix https://github.com/DMTF/libspdm/issues/2492

Add 1.3 cert check for digest.

---

library/spdm_crypt_lib/libspdm_crypt_cert.c

Fix: #2491 
The patch has passed the existing `test_spdm_crypt` unit_test.

Improve the OID check logic in cert extension

---

unit_test/spdm_unit_test_common/common.c

Make unit test send/receive buffer tracking more granular

---

doc/api/common_api.md

Update API documentation for multi-key

---

library/spdm_requester_lib/libspdm_req_get_certificate.c
library/spdm_responder_lib/libspdm_rsp_encap_get_certificate.c

Fix https://github.com/DMTF/libspdm/issues/2512

add check for cert_mode NULL.

---

library/spdm_requester_lib/libspdm_req_encap_challenge_auth.c
library/spdm_requester_lib/libspdm_req_encap_request.c
library/spdm_requester_lib/libspdm_req_key_exchange.c
library/spdm_responder_lib/libspdm_rsp_challenge_auth.c
library/spdm_responder_lib/libspdm_rsp_key_exchange.c
library/spdm_responder_lib/libspdm_rsp_measurements.c

Fix https://github.com/DMTF/libspdm/issues/2495

Add check for KeyUsage bit 

---

library/spdm_requester_lib/libspdm_req_get_csr.c
library/spdm_requester_lib/libspdm_req_handle_error_response.c
library/spdm_requester_lib/libspdm_req_set_certificate.c
unit_test/test_spdm_requester/get_csr.c

Reinstate capability checks for 1.3 endpoints

---

library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c

Fix SPDM 1.3 MEL algorithm negotiate

---

unit_test/test_spdm_requester/negotiate_algorithms.c

Enhance unit test for SPDM 1.3 MEL algorithm negotiate

---

library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c
library/spdm_responder_lib/libspdm_rsp_algorithms.c

Fix https://github.com/DMTF/libspdm/issues/2539

Mask other_param for 1.2

---

.github/workflows/compliance-checks.yml
script/check_copyright_date.sh

Add CI/CD script to detect out of date copyrights

---

.github/workflows/build.yml
.github/workflows/code_coverage.yml
.github/workflows/codeql-analysis.yml
.github/workflows/compliance-checks.yml

Update checkout version from 3 to 4

---

library/spdm_requester_lib/libspdm_req_key_update.c

Fix debug message

---

library/spdm_responder_lib/libspdm_rsp_receive_send.c

And scope the typedef to the function in which it's used.

Use `LIBSPDM_ARRAY_SIZE`

---

include/hal/library/debuglib.h

Enhance `libspdm_debug_print` documentation

---

include/library/spdm_crypt_lib.h
library/spdm_crypt_lib/libspdm_crypt_cert.c
os_stub/spdm_device_secret_lib_sample/lib.c
unit_test/test_spdm_crypt/test_spdm_crypt.c

Fix the issue: https://github.com/DMTF/libspdm/issues/2505

spdm_crypt_lib: Update the API to handle cert_mode

---

library/spdm_responder_lib/libspdm_rsp_certificate.c
library/spdm_responder_lib/libspdm_rsp_digests.c

Use correct message size when logging to transcript

---

include/hal/library/cryptlib/cryptlib_cert.h
os_stub/cryptlib_mbedtls/pk/x509.c
os_stub/cryptlib_null/pk/x509.c
os_stub/cryptlib_openssl/pk/x509.c

Fix libspdm_x509_get_extension_data description and logic error

---

.github/workflows/cifuzz.yml

Fix: #2593
Waiting for oss-fuzz [PR](https://github.com/google/oss-fuzz/pull/11672) merged.

CI: Enable oss-fuzz

---

include/internal/libspdm_lib_config.h

Remove check of `MDEPKG_NDEBUG`

---

include/hal/library/cryptlib/cryptlib_cert.h
library/spdm_crypt_lib/libspdm_crypt_cert.c
os_stub/cryptlib_mbedtls/pk/x509.c
os_stub/cryptlib_null/pk/x509.c
os_stub/cryptlib_openssl/pk/x509.c

Enhance libspdm_x509_get_extension_data returned value check

---

library/spdm_requester_lib/libspdm_req_get_csr.c

Add more check for csr response size

---

README.md
doc/api/requester_api.md
include/library/spdm_requester_lib.h

Update documentation for the 3.3 release

---

library/spdm_requester_lib/libspdm_req_vendor_request.c

Fix https://github.com/DMTF/libspdm/issues/2661

Fix the vendor defined message length check in requester.

---

library/spdm_responder_lib/libspdm_rsp_vendor_response.c
unit_test/test_spdm_responder/receive_send.c

Fix https://github.com/DMTF/libspdm/issues/2670

Add vendor_request length check in responder.

---

library/spdm_responder_lib/libspdm_rsp_vendor_response.c

Fix https://github.com/DMTF/libspdm/issues/2669

fix typo for vendor_req msg.

---

library/spdm_responder_lib/libspdm_rsp_vendor_response.c

Hi @jyao1,
This is most likely a simple fix to a simple overlook.
Please check lines 108..110.

Fix req_vendor_id and req_size duplication

---

library/spdm_requester_lib/libspdm_req_get_certificate.c

Fix: #2689
The verify authority and integrity should be in the same logic.

Fix authority and integrity verify logic

---

library/spdm_responder_lib/libspdm_rsp_encap_get_certificate.c

Fix cert verify logic in rsp_encap_get_certificate

---

library/spdm_responder_lib/libspdm_rsp_vendor_response.c

Hi @steven-bellock,
I believe we need to fix acquiring Session ID prior to #2694.
Please check the call of spdm_context->get_response_func (i.e., line 67).
session_info is not a pointer, it's an array. Therefore, Session ID is correct only if Session Info is stored at index zero.

Fix acquiring Session ID in Vendor Defined Response

---

unit_test/test_spdm_responder/error_test/vendor_response_err.c
unit_test/test_spdm_responder/vendor_response.c

Fix vendor response test case issues

---

library/spdm_crypt_lib/libspdm_crypt_cert.c
unit_test/test_spdm_crypt/test_spdm_crypt.c

Change basic constraints as mandatory for SPDM 1.3

---

include/hal/library/cryptlib/cryptlib_cert.h
library/spdm_crypt_lib/libspdm_crypt_cert.c
os_stub/cryptlib_mbedtls/pk/x509.c
os_stub/cryptlib_null/pk/x509.c
os_stub/cryptlib_openssl/pk/x509.c

Change cert fields to optional for GenericCert model cert check

---

include/hal/library/cryptlib/cryptlib_cert.h
include/library/spdm_lib_config.h
library/spdm_crypt_lib/libspdm_crypt_cert.c
os_stub/cryptlib_mbedtls/pk/x509.c
os_stub/cryptlib_null/pk/x509.c
os_stub/cryptlib_openssl/pk/x509.c
os_stub/spdm_crypt_ext_lib/cryptlib_ext.h

Add signature algo check for cert

---

include/library/spdm_lib_config.h

Cleanup spdm_lib_config.h

---

os_stub/spdm_device_secret_lib_sample/lib.c

Update the index type to prevent infinite loop

---

library/spdm_requester_lib/libspdm_req_set_certificate.c
unit_test/test_spdm_requester/set_certificate.c

Fix SET_CERTIFICATE issues

---

doc/api/common_api.md
doc/crypto_endianness.md
library/spdm_common_lib/libspdm_com_context_data_session.c
unit_test/test_spdm_requester/key_exchange.c

Specify little-endian sequence number for 277 1.2

---

doc/api/requester_api.md

Update API documentation for MEL

---

README.md

Update documentation for 3.4 release

---

library/spdm_responder_lib/libspdm_rsp_challenge_auth.c
library/spdm_responder_lib/libspdm_rsp_key_exchange.c
library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
os_stub/spdm_device_secret_lib_null/lib.c
os_stub/spdm_device_secret_lib_sample/lib.c
unit_test/test_spdm_responder/key_exchange.c
unit_test/test_spdm_responder/psk_exchange.c
unit_test/test_spdm_responder/receive_send.c

Fix `MEAS_CAP` build failures

---

VERSION.md
include/library/spdm_common_lib.h

Update version after 3.4 release

---

library/spdm_requester_lib/libspdm_req_challenge.c
library/spdm_requester_lib/libspdm_req_communication.c
library/spdm_requester_lib/libspdm_req_end_session.c
library/spdm_requester_lib/libspdm_req_finish.c
library/spdm_requester_lib/libspdm_req_get_capabilities.c
library/spdm_requester_lib/libspdm_req_get_certificate.c
library/spdm_requester_lib/libspdm_req_get_csr.c
library/spdm_requester_lib/libspdm_req_get_digests.c
library/spdm_requester_lib/libspdm_req_get_event_types.c
library/spdm_requester_lib/libspdm_req_get_measurements.c
library/spdm_requester_lib/libspdm_req_get_version.c
library/spdm_requester_lib/libspdm_req_handle_error_response.c
library/spdm_requester_lib/libspdm_req_heartbeat.c
library/spdm_requester_lib/libspdm_req_key_exchange.c
library/spdm_requester_lib/libspdm_req_key_update.c
library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c
library/spdm_requester_lib/libspdm_req_psk_exchange.c
library/spdm_requester_lib/libspdm_req_psk_finish.c
library/spdm_requester_lib/libspdm_req_set_certificate.c
library/spdm_requester_lib/libspdm_req_vendor_request.c

Add spdm_requester_size check before use

---

README.md

Remove disclaimer from readme

---

unit_test/test_spdm_requester/error_test/key_exchange_err.c
unit_test/test_spdm_requester/key_exchange.c
unit_test/test_spdm_requester/key_update.c
unit_test/test_spdm_requester/psk_exchange.c
unit_test/test_spdm_responder/key_exchange.c
unit_test/test_spdm_responder/key_update.c
unit_test/test_spdm_responder/psk_exchange.c

Fix the incorrect use of logical negation in the unit tests.

---

unit_test/test_spdm_requester/finish.c
unit_test/test_spdm_responder/finish.c

add unit test : Requester and Responder set HANDSHAKE_IN_THE_CLEAR_CAP to 0.

---

README.md

Update specification versions / revisions

---

.github/workflows/code_coverage.yml

Squash code coverage commits

---

library/spdm_requester_lib/libspdm_req_key_exchange.c
library/spdm_responder_lib/libspdm_rsp_key_exchange.c
unit_test/test_spdm_requester/error_test/key_exchange_err.c
unit_test/test_spdm_requester/key_exchange.c
unit_test/test_spdm_responder/key_exchange.c
unit_test/test_spdm_responder/respond_if_ready.c

Check key exchange capabilities

---

unit_test/test_spdm_responder/measurements.c

fix test case measurements

---

library/spdm_requester_lib/libspdm_req_get_csr.c
library/spdm_requester_lib/libspdm_req_set_certificate.c

Delete duplicate version check

---

.github/workflows/code_coverage.yml

Add secure messages to test coverage

---

doc/api/common_api.md
include/industry_standard/spdm.h

Specify SPDM certificate chain structure

---

include/library/spdm_crypt_lib.h

Add retvals to libspdm_get_random_number

---

include/internal/libspdm_common_lib.h
library/spdm_common_lib/libspdm_com_support.c
library/spdm_requester_lib/libspdm_req_get_capabilities.c
library/spdm_responder_lib/libspdm_rsp_capabilities.c

Mask capability flags based on negotiated version

---

unit_test/test_spdm_requester/encap_certificate.c
unit_test/test_spdm_responder/certificate.c

Fix spelling lenghts -> lengths

---

.github/workflows/coverity.yml

Setup nightly Coverity scanning

---

unit_test/test_spdm_requester/encap_key_update.c

Change logical negation to bitwise negation

---

library/spdm_responder_lib/libspdm_rsp_set_key_pair_info_ack.c

Increase the check to determine whether at most one bit is set for DesiredAsymAlgo.

---

library/spdm_crypt_lib/libspdm_crypt_cert.c

Skip keyUsage check for AliasCert and SET_CERTIFICATE

---

library/spdm_responder_lib/libspdm_rsp_end_session.c
library/spdm_responder_lib/libspdm_rsp_finish.c
library/spdm_responder_lib/libspdm_rsp_heartbeat.c
library/spdm_responder_lib/libspdm_rsp_key_update.c
library/spdm_responder_lib/libspdm_rsp_psk_finish.c

Fix https://github.com/DMTF/libspdm/issues/2844

Do not use SPDM_ERROR_CODE_SESSION_REQUIRED for SPDM 1.1.

---

include/industry_standard/cxl_tsp.h
include/library/spdm_lib_config.h
os_stub/spdm_device_secret_lib_sample/lib.c
os_stub/spdm_device_secret_lib_sample/spdm_device_secret_lib_internal.h

The related spdm-emu change is at https://github.com/DMTF/spdm-emu/pull/380.

Add CXL TSP 2nd session support

---

library/spdm_common_lib/libspdm_com_context_data.c

Fix https://github.com/DMTF/libspdm/issues/2865

remove unnecessary slot_id assignment.

---

library/spdm_requester_lib/libspdm_req_send_receive.c

More descriptive buffer error codes

---

.github/workflows/cifuzz.yml

Update CodeQL version from 2 to 3

---

library/spdm_requester_lib/libspdm_req_send_receive.c
library/spdm_responder_lib/libspdm_rsp_receive_send.c

The send/receive code is complex and difficult to follow. This is a first small attempt to refactor the code so that it's a little easier to read.

Refactor send/receive part 1

---

library/spdm_requester_lib/libspdm_req_set_key_pair_info.c

fix https://github.com/DMTF/libspdm/issues/2916

fix req length calculation for set_key_pair_info.

---

doc/api/common_api.md
include/library/spdm_common_lib.h

Clarify timeout and RTT documentation

---

os_stub/spdm_device_secret_lib_sample/key_pair.c

fix https://github.com/DMTF/libspdm/issues/2915

use macro to determine key pair info reporting.

---

os_stub/spdm_device_secret_lib_sample/key_pair.c
os_stub/spdm_device_secret_lib_sample/spdm_device_secret_lib_internal.h
unit_test/fuzzing/test_responder/test_spdm_responder_set_key_pair_info_ack/set_key_pair_info_ack.c
unit_test/test_spdm_responder/key_pair_info.c
unit_test/test_spdm_responder/set_key_pair_info_ack.c

Fix https://github.com/DMTF/libspdm/issues/2913

Key pairs number

---

include/hal/base.h
include/hal/library/cryptlib/cryptlib_cert.h
include/industry_standard/spdm.h
include/library/spdm_common_lib.h
library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_crypt_lib/libspdm_crypt_cert.c
library/spdm_requester_lib/libspdm_req_common.c
library/spdm_requester_lib/libspdm_req_handle_error_response.c
library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c
library/spdm_responder_lib/libspdm_rsp_chunk_send_ack.c
os_stub/cryptlib_mbedtls/pk/x509.c
os_stub/cryptlib_null/pk/x509.c
os_stub/cryptlib_openssl/pk/x509.c
os_stub/spdm_cert_verify_callback_sample/spdm_cert_verify_callback_internal.h
unit_test/test_spdm_common/context_data.c
unit_test/test_spdm_requester/get_version.c

Fix spelling errors

---

library/spdm_crypt_lib/libspdm_crypt_hmac.c

Fix libspdm_hmac_new return type

---

library/spdm_requester_lib/libspdm_req_encap_key_update.c

Return proper error code when session is required

---

library/spdm_responder_lib/libspdm_rsp_measurement_extension_log.c

Fix incorrect error data for UnsupportedRequest

---

include/internal/libspdm_common_lib.h
library/spdm_common_lib/libspdm_com_context_data.c
library/spdm_crypt_lib/fips/libspdm_selftest.c
library/spdm_crypt_lib/fips/libspdm_selftest_aes_gcm.c
library/spdm_crypt_lib/fips/libspdm_selftest_ecdh.c
library/spdm_crypt_lib/fips/libspdm_selftest_ecdsa.c
library/spdm_crypt_lib/fips/libspdm_selftest_eddsa.c
library/spdm_crypt_lib/fips/libspdm_selftest_ffdh.c
library/spdm_crypt_lib/fips/libspdm_selftest_hkdf.c
library/spdm_crypt_lib/fips/libspdm_selftest_hmac.c
library/spdm_crypt_lib/fips/libspdm_selftest_rsa_pss.c
library/spdm_crypt_lib/fips/libspdm_selftest_rsa_ssa.c
library/spdm_crypt_lib/fips/libspdm_selftest_sha2.c
library/spdm_crypt_lib/fips/libspdm_selftest_sha3.c
unit_test/test_spdm_fips/test_spdm_fips.c

GCC Warning for shadow

---

library/spdm_requester_lib/libspdm_req_get_capabilities.c
library/spdm_responder_lib/libspdm_rsp_capabilities.c

Fix `EP_INFO_CAP` logic error

---

library/spdm_responder_lib/libspdm_rsp_finish.c
library/spdm_responder_lib/libspdm_rsp_key_exchange.c

Refactor the code so that it is easier to read. There are no functional changes.

Refactor Responder's key exchange code

---

library/spdm_responder_lib/libspdm_rsp_encap_response.c
unit_test/test_spdm_responder/encap_response.c

Use SPDM 1.3 NoPendingRequests

---

unit_test/test_spdm_requester/chunk_get.c

Add unit test coverage for chunk sequence no wrapped in chunk get.

---

library/spdm_responder_lib/libspdm_rsp_encap_get_certificate.c

I apparently introduced this in #2033. How embarrassing.

Remove extra semi-colon

---

os_stub/cryptlib_openssl/pk/ecd.c
unit_test/test_crypt/ecd_verify.c

Pass spdm_context to ED448

---

os_stub/cryptlib_openssl/pk/x509.c
unit_test/test_crypt/test_crypt.c
unit_test/test_crypt/x509_verify.c

Fix #3044
Fix https://github.com/DMTF/libspdm/issues/3064

Add EdDSA support and unit test for libspdm_gen_x509_csr()

---

os_stub/cryptlib_openssl/pk/x509.c
unit_test/test_crypt/test_crypt.c
unit_test/test_crypt/x509_verify.c

Add SM2 support in libspdm_gen_x509_csr()

---

library/spdm_requester_lib/libspdm_req_get_capabilities.c
library/spdm_responder_lib/libspdm_rsp_capabilities.c
unit_test/test_spdm_requester/error_test/get_capabilities_err.c
unit_test/test_spdm_responder/capabilities.c

Check `MULTI_KEY_CAP` and `CERT_CAP`

---

library/spdm_transport_tcp_lib/libspdm_tcp_common.c

Change format specifier from `p` to `xu`

---

doc/multikey.md

Initial draft for multikey guide

---

library/spdm_transport_tcp_lib/libspdm_tcp_common.c

Prevent uninitialized size when encoding SPDM to APP message. Fixes coverity spotted issue: https://github.com/DMTF/libspdm/issues/3104

TCP: Initialize app_message_size and fix header size usage

---

README.md

Fix https://github.com/DMTF/libspdm/issues/3112

Add TCP binding and Storage binding to readme

---

VERSION.md
include/library/spdm_common_lib.h

This may change to 4.0 in the future.

Update version to `3.9`

---

.github/workflows/coverity.yml

For now it must be manually triggered.

Add Coverity to CI/CD

---

.github/workflows/coverity.yml

Allow build type to be selected when triggering Coverity scan.

Add Coverity build options

---

include/library/spdm_requester_lib.h
library/spdm_requester_lib/libspdm_req_heartbeat.c
library/spdm_requester_lib/libspdm_req_key_update.c
library/spdm_responder_lib/libspdm_rsp_heartbeat.c
library/spdm_responder_lib/libspdm_rsp_key_update.c

Add macros for key update and heartbeat code

---

include/industry_standard/spdm.h
library/spdm_common_lib/libspdm_com_support.c
unit_test/test_spdm_common/context_data.c

Fix https://github.com/DMTF/libspdm/issues/3134

1.4 Add DMTF-DSP vendor ID definition.

---

script/check_copyright_date.sh

See https://github.com/steven-bellock/libspdm/actions/runs/16348820750/job/46189787626 for a trial run.

Check unit tests for copyright date

---

VERSION.md
include/library/spdm_common_lib.h

See https://github.com/DMTF/libspdm/discussions/3156 for the announcement.

Update version to 4.0

---

include/industry_standard/spdm.h
include/library/spdm_common_lib.h
include/library/spdm_requester_lib.h
library/spdm_requester_lib/libspdm_req_vendor_request.c
library/spdm_responder_lib/libspdm_rsp_vendor_response.c
unit_test/fuzzing/test_requester/test_spdm_requester_vendor_cmds/vendor_cmds.c
unit_test/fuzzing/test_responder/test_spdm_responder_vendor_cmds/vendor_cmds.c
unit_test/test_spdm_requester/chunk_get.c
unit_test/test_spdm_requester/chunk_send.c
unit_test/test_spdm_requester/error_test/vendor_request_err.c
unit_test/test_spdm_requester/vendor_request.c
unit_test/test_spdm_responder/error_test/vendor_response_err.c
unit_test/test_spdm_responder/receive_send.c
unit_test/test_spdm_responder/vendor_response.c

1.4 Add LargePayload to VDM.

---

include/internal/libspdm_common_lib.h
library/spdm_common_lib/libspdm_com_support.c
library/spdm_requester_lib/libspdm_req_vendor_request.c
library/spdm_responder_lib/libspdm_rsp_vendor_response.c
unit_test/test_spdm_responder/vendor_response.c

Check `StandardID` and `Len` in `VENDOR_DEFINED_*`

---

include/industry_standard/spdm.h
include/internal/libspdm_common_lib.h
library/spdm_requester_lib/libspdm_req_handle_error_response.c
library/spdm_requester_lib/libspdm_req_send_receive.c
library/spdm_responder_lib/libspdm_rsp_chunk_get.c
library/spdm_responder_lib/libspdm_rsp_chunk_send_ack.c
unit_test/test_spdm_requester/chunk_get.c
unit_test/test_spdm_requester/chunk_send.c
unit_test/test_spdm_responder/chunk_get.c
unit_test/test_spdm_responder/chunk_send_ack.c

1.4 increase chunk_seq_no from 2 bytes to 4 bytes

---

CMakeLists.txt
os_stub/cryptlib_mbedtls/pk/x509.c

Unsupported critical extension in Mbed TLS build

---

library/spdm_responder_lib/libspdm_rsp_receive_send.c

1.4 Fix incorrect message offset caused by send_ack_response size change

---

doc/api/requester_api.md
include/industry_standard/spdm.h
include/internal/libspdm_requester_lib.h
include/library/spdm_requester_lib.h
library/spdm_requester_lib/libspdm_req_communication.c
library/spdm_requester_lib/libspdm_req_get_capabilities.c
library/spdm_responder_lib/libspdm_rsp_capabilities.c
unit_test/test_spdm_requester/get_capabilities.c
unit_test/test_spdm_responder/capabilities.c

Fix https://github.com/DMTF/libspdm/issues/2279.
Previous pull request: https://github.com/DMTF/libspdm/pull/2968

[SPDM 1.3] CAPABILITIES: Add SupportedAlgorithms

---

include/library/spdm_requester_lib.h
library/spdm_requester_lib/libspdm_req_challenge.c
unit_test/fuzzing/test_requester/test_spdm_requester_challenge/challenge.c
unit_test/test_spdm_requester/challenge.c

Use `LIBSPDM_SEND_CHALLENGE_SUPPORT`

---

include/library/spdm_crypt_lib.h
library/spdm_crypt_lib/libspdm_crypt_dhe.c
library/spdm_secured_message_lib/libspdm_secmes_context_data.c

Fix https://github.com/DMTF/libspdm/issues/3239

add `get_dhe_shared_secret_size()` API to avoid confusion.

---

library/spdm_requester_lib/libspdm_req_handle_error_response.c
library/spdm_responder_lib/libspdm_rsp_set_key_pair_info_ack.c
unit_test/test_spdm_requester/set_key_pair_info.c
unit_test/test_spdm_responder/set_key_pair_info_ack.c

1.4 Add `SET_KEY_PAIR_RESET_CAP` support
