include/library/spdm_secured_message_lib.h, library/spdm_secured_message_lib/session.c
Fixes #57
Updates comment to provide accurate description on size of string expected for spdm_bin_concat.
=> Correcting argument description on spdm_bin_concat.

library/spdm_requester_lib/encap_certificate.c, library/spdm_requester_lib/encap_challenge_auth.c, library/spdm_requester_lib/encap_digests.c, library/spdm_responder_lib/algorithms.c, library/spdm_responder_lib/capabilities.c, library/spdm_responder_lib/certificate.c, library/spdm_responder_lib/challenge_auth.c, library/spdm_responder_lib/digests.c, library/spdm_responder_lib/finish.c, library/spdm_responder_lib/key_exchange.c, library/spdm_responder_lib/measurements.c, library/spdm_responder_lib/psk_exchange.c, library/spdm_responder_lib/psk_finish.c, library/spdm_responder_lib/version.c, unit_test/test_spdm_responder/digests.c
Fix #23
1.Internal message appending error should return Unspecified.
2.Internal calculation error such as hash,signature... should return Unspecified.
Signed-off-by: yi1.li <yi1.li@intel.com>
=> Fit responder error return value

library/spdm_requester_lib/challenge.c, library/spdm_requester_lib/encap_certificate.c, library/spdm_requester_lib/encap_challenge_auth.c, library/spdm_requester_lib/encap_digests.c, library/spdm_requester_lib/get_capabilities.c, library/spdm_requester_lib/get_certificate.c, library/spdm_requester_lib/get_digests.c, library/spdm_requester_lib/get_measurements.c, library/spdm_requester_lib/get_version.c, library/spdm_requester_lib/key_exchange.c, library/spdm_requester_lib/negotiate_algorithms.c, library/spdm_requester_lib/psk_exchange.c, library/spdm_responder_lib/algorithms.c, library/spdm_responder_lib/capabilities.c, library/spdm_responder_lib/certificate.c, library/spdm_responder_lib/challenge_auth.c, library/spdm_responder_lib/digests.c, library/spdm_responder_lib/key_exchange.c, library/spdm_responder_lib/measurements.c, library/spdm_responder_lib/psk_exchange.c, library/spdm_responder_lib/version.c, unit_test/test_spdm_requester/challenge.c, unit_test/test_spdm_requester/get_digests.c, unit_test/test_spdm_requester/get_measurements.c
Fix #24
And fix derivation issues of bug24:
1. Remove useless shrink function using.
2. Unit-test should not assume there is any data in meesage buffer if response fail.
=> Adjust message appending flow

library/spdm_common_lib/crypto_service.c, library/spdm_common_lib/spdm_common_lib_internal.h, library/spdm_requester_lib/get_digests.c, library/spdm_responder_lib/encap_get_digests.c, unit_test/test_spdm_requester/get_digests.c
Fix #64
Requester should compare digests in response to local cached digests one by one.
=> fix get_digests verification

unit_test/test_spdm_requester/finish.c, unit_test/test_spdm_responder/finish.c
This commit adds new unit test cases for the FINISH/FINISH_RSP messages.
On the requester side:
- no capabilities for key exchange
- incomplete state (up to negotiate_algorithms)
- wrong response code
- session not initiated
- with mutual authentication (success case)
- wrong MAC (all-zero and arbitrary)
- wrong MAC size (double and half sizes)
On the responder side:
- with mutual authentication (success case)
- no capabilities for key exchange
- session not initiated
- incorrect MAC (all-zero and arbitrary)
- wrong MAC size (double and half sizes)
- wrong requester signature (all-zero and arbitrary)
They were tested for x64 on Ubuntu (GCC), and for ia32 and x64 on Windows (VS2019), for debug and release.
We were unable to compile libspdm for ia32 in a x64 Ubuntu machine as we were used …
=> Adding new unit test cases for the finish message.

library/spdm_responder_lib/measurements.c
Fixes #80
spdm_create_measurement_signature returns boolean, while the existing code checks for negative value as failure return status. This check will never be true, so we can quietly fail spdm_create_measurement_signature and continue on.
Fixing return value check to ensure we catch failure.
=> Fixing incorrect return value check in measurements.c

CMakeLists.txt, include/library/spdm_common_lib.h, library/spdm_common_lib/context_data.c, library/spdm_common_lib/spdm_common_lib_internal.h, unit_test/test_spdm_common/CMakeLists.txt, unit_test/test_spdm_common/context_data.c, unit_test/test_spdm_common/test_spdm_common.c
Fix DMTF#66
Added opaque data pointer to spdm context. This is useful to pass
pointers to application specific data through the context to callback
functions such as spdm_device_send_message_func.
Signed-off-by: Raghu Krishnamurthy raghupathyk@nvidia.com
=> Add application specific opaque data into spdm context

library/spdm_requester_lib/encap_certificate.c, library/spdm_requester_lib/encap_digests.c, library/spdm_responder_lib/certificate.c, library/spdm_responder_lib/digests.c
local_cert_chain_provision is an array used to store cert chain pointers,
should compare the member of array instead of array-self.
If slot_id is valid but local_cert_chain_provision[slot_id] is NULL,
should report internal error with SPDM_ERROR_CODE_UNSPECIFIED.
Fix #51
=> Array compared to null bug

library/spdm_common_lib/context_data.c, library/spdm_responder_lib/receive_send.c
When compiling with more restrictive options, such as force error on warning, the compiler will think these two variables (session_info and return_status) may be used before initialized.  Fix this issue by always initializing the variables.
=> Fix for uninitialized variables error on warning

unit_test/test_spdm_requester/psk_finish.c, unit_test/test_spdm_responder/psk_finish.c
This commit adds new unit test cases for the PSK_FINISH/PSK_FINISH_RSP messages.
On the requester side:
* no capabilities for PSK
* wrong response code
* session not initiated
On the responder side:
* with mutual authentication (success case)
* no capabilities for PSK
* session not initiated
* incorrect MAC (all-zero and arbitrary)
* wrong MAC size (double and half sizes)
Signed-off-by: Marcos Vinicius Maciel da Silva <vinicius_ceth@yahoo.com.br>
=> Adding new test cases for the psk_finish message.

library/spdm_crypt_lib/crypt.c
REF: #124
Skip the first certificate of a certificate chain without root certificate when verifying integrity.
=> Skip the first cert when verifying integrity

include/library/spdm_requester_lib.h, library/spdm_common_lib/crypto_service.c, library/spdm_common_lib/spdm_common_lib_internal.h, library/spdm_requester_lib/get_certificate.c, library/spdm_responder_lib/encap_get_certificate.c
The caller may need to know which trust anchor is used to pass the certificate verification.
REF: https://github.com/DMTF/libspdm/issues/138
=> need return trust anchor in GetCertificate to the caller

unit_test/test_size/test_size_of_spdm_requester/CMakeLists.txt, unit_test/test_size/test_size_of_spdm_requester/spdm_requester_main.c, unit_test/test_size/test_size_of_spdm_responder/CMakeLists.txt, unit_test/test_size/test_size_of_spdm_responder/spdm_responder_main.c
1) Always enable MAP.
2) Use cryptlib_dummy to remove impact from crypto lib.
3) Disable optimization in main test_size entrypoint.
Now the size info is:
39,424 test_size_of_spdm_requester.exe
48,128 test_size_of_spdm_responder.exe
=> Fix test_size binary to help size analysis.

library/spdm_requester_lib/key_update.c, unit_test/test_spdm_requester/CMakeLists.txt, unit_test/test_spdm_requester/key_update.c, unit_test/test_spdm_requester/test_spdm_requester.c
We add unit test cases on the requester side for the key_update message. Including the standard tests from previous messages.
These tests verify the output of the requester side of the key update, and whether the major secret was updated.
We also include the handling of retries and received ERROR responses, as in previous messages.
It includes 4 commits:
1) when receiving an ERROR response, we call the "spdm_handle_error_response_main()" function to handle it, both in the UpdateKey/UpdateAllKeys and VerifyNewKey operations.
The major secret is rolled back in most "failed" cases for UpdateKey/UpdateAllKeys, but not for VerifyNewKey.
Additionally, it can successfully retry when receiving a Busy or ResponseNotReady ERROR response.
2) new test cases for the UpdateKey operation:
- send request …
=> Adding new test cases for the key_update message (requester side)

library/spdm_requester_lib/challenge.c, library/spdm_responder_lib/challenge_auth.c
Fix #99
Should reset message_c before return error.
=> Fix error handling for CHALLENGE_AUTH signature generation

library/spdm_common_lib/crypto_service.c, unit_test/test_crypt/sm2_verify.c, unit_test/test_crypt/sm2_verify2.c, unit_test/test_spdm_requester/get_certificate.c, unit_test/test_spdm_requester/get_digests.c, unit_test/test_spdm_requester/get_measurements.c, unit_test/test_spdm_responder/certificate.c, unit_test/test_spdm_responder/digests.c
Fix unused variables generated by conditional compilation directives.
The Liunx and Windows unit tests passed.
=> Fix unused code

library/spdm_common_lib/context_data.c, library/spdm_common_lib/crypto_service_session.c
=> Use secured_message_context directly to simplify code.

include/library/spdm_device_secret_lib.h, library/spdm_common_lib/crypto_service.c, library/spdm_responder_lib/measurements.c, os_stub/spdm_device_secret_lib_null/lib.c, os_stub/spdm_device_secret_lib_sample/lib.c
Fix #179
This change optimizes the get measurements code path related to [https://github.com/DMTF/libspdm/issues/179](https://github.com/DMTF/libspdm/issues/179)
- 4.5K is saved off the stack by not using an extra local buffer for copying measurements when **spdm_get_response_measurements** calls **spdm_measurement_collection**. The response buffer is passed instead and **spdm_measurement_collection** will fill in the response buffer directly.
- The size of the **spdm_get_response_measurements** code is reduced from ~1.3K to ~500bytes (Release build x64). The size of **spdm_measurement_collection**, which is just an example, increases slightly by ~180 bytes.
- **spdm_measurement_collection** now receives and "**measurements_index**" so it does not need to calculate all measurements when …
=> Optimize Get Measurements code path 

library/spdm_common_lib/crypto_service.c
Fix #254
Bug fix for [Incorrect measurements buffer size hashed in spdm_generate_measurement_summary_hash #254](https://github.com/DMTF/libspdm/issues/254)
=> Fix for bug wrong measurement buffer size used for copy and hash.

os_stub/openssllib/include/crt_support.h
Fix: #277 
Update the time_t type to ensure that:
time_t is 4 bytes for 32bit machine and 8 bytes for 64bit machine.
=> Fix the bug for test_spdm_requester crashes with OpenSSL in Linux

CMakeLists.txt, README.md
Fix : #280 
Add description for README : how to build ia32 on 64bit linux machine.
Update CMakeLists to fix error : build error with Openssl for ia32 in Linux.
=> Update ia32 build on linux

library/spdm_requester_lib/libspdm_req_key_exchange.c
Fix: #290 
'dhe_context' should be checked whether it is a NULL Pointer before subsequent using
=> Add dhe_context check for NULL pointer return

library/spdm_responder_lib/libspdm_rsp_algorithms.c, unit_test/test_spdm_responder/algorithms.c
Fix: #204 
Add the support GET_MEASUREMENTS check in responder.
The Responder measurement_hash_algo shall set coincident for whether Responder support GET_MEASUREMENTS or not.
The same is measurement_spec.
Update the unit_test for spdm_get_response_algorithms to fix:
the inconsistent for GET_MEASUREMENTS support and measurement_hash_algo\measurement_spec.
=> Add the support GET_MEASUREMENTS check in responder

CMakeLists.txt
Fix the openssl build fail issue with AFL in Linux.
Fix: #331
=> fix the openssl build fail issue with AFL in Linux

unit_test/fuzzing/test_spdm_requester_get_certificate/get_certificate.c
Because the CI check is not realize timely, some new patches were merged.
And the patch include Tabs. The patch change Tab to 4 spaces again.
=> Change Tab to 4 spaces again

.github/workflows/cmake.yml
Add format check for later patch:
If the later patch include Tab, the check will not pass.
And the check will skip on openssl/mbedtls/cmocka/README.
Add build with mbedtls :
Add mbedtls build to CI check.
=> Add CI for format check and mbedtls build check

README.md, doc/design.md, doc/test.md, doc/threat_model.md, doc/user_guide.md
Fix: #46 
Change most instances of "openspdm" to "libspdm".
Make the the code meaning clearly.
=> Change all "openspdm" to "libspdm"

library/spdm_requester_lib/libspdm_req_encap_challenge_auth.c, library/spdm_requester_lib/libspdm_req_encap_digests.c, library/spdm_requester_lib/libspdm_req_encap_key_update.c, library/spdm_requester_lib/libspdm_req_key_exchange.c, library/spdm_requester_lib/libspdm_req_key_update.c, library/spdm_requester_lib/libspdm_req_psk_finish.c, library/spdm_responder_lib/libspdm_rsp_challenge_auth.c, library/spdm_responder_lib/libspdm_rsp_digests.c, library/spdm_responder_lib/libspdm_rsp_encap_key_update.c, library/spdm_responder_lib/libspdm_rsp_key_exchange.c, library/spdm_responder_lib/libspdm_rsp_key_update.c, library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c
First round of fixes for #75 .
Going to do these in batches since there's a lot of ground to cover.
This fixes (most) functions that had their return values not checked in:
- include/internal/libspdm_common_lib.h
- include/internal/libspdm_requester_lib.h
- include/internal/libspdm_responder_lib.h
- include/internal/libspdm_secured_message_lib.h
- include/library/spdm_secured_message_lib.h
There's a few omissions from the above two that I'll handle in a separate follow up:
- spdm_hmac_\*_with_\*_finished_key
- append_managed_buffer
=> First batch of fixes for missing return value checks

include/library/spdm_common_lib.h, library/spdm_common_lib/libspdm_com_context_data.c, library/spdm_common_lib/libspdm_com_crypto_service.c, library/spdm_crypt_lib/libspdm_crypt_crypt.c, library/spdm_secured_message_lib/libspdm_secmes_context_data.c, library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c, os_stub/cryptlib_mbedtls/rand/rand.c, os_stub/cryptlib_null/rand/rand.c
Addresses #75 in part.
Additionally: 
- Modifies libspdm_init_context to have a return value. Required as it calls random_seed(), which can fail.
- Removes random_seed from spdm_secured_message_init_context - presuming this is OK as we already seed RNG in libspdm_init_context. If we need to seed everytime we init the secured message context - there is a very wide cascading effect of functions we need to modify to have return values.
- Changes some direct calls of random_bytes to spdm_get_random_number.
Signed-off-by: Timothy <tandrewprinz@nvidia.com>
=> Adding missing return value checks for cryptlib.h file.

include/library/spdm_common_lib.h, library/spdm_common_lib/libspdm_com_context_data.c, library/spdm_common_lib/libspdm_com_context_data_session.c, library/spdm_common_lib/libspdm_com_crypto_service_session.c, library/spdm_common_lib/libspdm_com_support.c, library/spdm_requester_lib/libspdm_req_encap_certificate.c, library/spdm_requester_lib/libspdm_req_encap_challenge_auth.c, library/spdm_requester_lib/libspdm_req_encap_key_update.c, library/spdm_requester_lib/libspdm_req_encap_request.c, library/spdm_responder_lib/libspdm_rsp_algorithms.c, library/spdm_responder_lib/libspdm_rsp_capabilities.c, library/spdm_responder_lib/libspdm_rsp_certificate.c, library/spdm_responder_lib/libspdm_rsp_challenge_auth.c, library/spdm_responder_lib/libspdm_rsp_digests.c, library/spdm_responder_lib/libspdm_rsp_encap_response.c, library/spdm_responder_lib/libspdm_rsp_end_session.c, library/spdm_responder_lib/libspdm_rsp_finish.c, library/spdm_responder_lib/libspdm_rsp_handle_response_state.c, library/spdm_responder_lib/libspdm_rsp_heartbeat.c, library/spdm_responder_lib/libspdm_rsp_key_exchange.c, library/spdm_responder_lib/libspdm_rsp_key_update.c, library/spdm_responder_lib/libspdm_rsp_measurements.c, library/spdm_responder_lib/libspdm_rsp_psk_exchange.c, library/spdm_responder_lib/libspdm_rsp_psk_finish.c, library/spdm_responder_lib/libspdm_rsp_receive_send.c, library/spdm_responder_lib/libspdm_rsp_respond_if_ready.c, library/spdm_responder_lib/libspdm_rsp_version.c
Partially addresses #75.
Adds missing return status checks to functions defined in:
- include/library/spdm_common_lib.h
- include/library/spdm_device_secret_lib.h (none missing)
- include/library/spdm_requester_lib.h
- include/library/spdm_responder_lib.h
Also changes libspdm_free_session_id and libspdm_write_uint24 to no longer have return values - as there wasn't any usage of them, and doesn't seem like the return value was necessary (free functions typically don't return anything, write_uint24 return isn't needed).
=> Fix missing return statuses in requester, responder, and common library functions.

include/internal/libspdm_common_lib.h, include/library/spdm_common_lib.h, library/spdm_common_lib/libspdm_com_context_data.c, unit_test/test_spdm_common/context_data.c
Fix #274.
The reason is that "opaque" is used in SPDM spec with special meaning.
Here we just need a pointer for application, not related to opaque in SPDM spec.
=> Rename OPAQUE_CONTEXT_DATA to APP_CONTEXT_DATA.

library/spdm_responder_lib/libspdm_rsp_version.c
Fixes: https://github.com/DMTF/libspdm/issues/41
=> Don't reset Responder's connection state unless it receives a valid GET_VERSION request

library/spdm_requester_lib/libspdm_req_get_version.c
In function `spdm_negotiate_connection_version` there is a potential buffer overflow (line 115) where the indexing variable (`res_index`) is incremented before the array access.
This bug was found by ESBMC as a part of our work of applying formal verification to libspdm.
=> [spdm_requester_lib] fixed potential buffer overflow

unit_test/fuzzing/test_responder/test_spdm_responder_algorithms/algorithms.c
test_spdm_responder_algorithms_case9 call spdm_get_response_algorithms function twice, so divide it into two cases.
Fix: #394
=> Fix test_spdm_responder_algorithms fuzzing test case issue.

library/spdm_common_lib/libspdm_com_crypto_service.c, library/spdm_common_lib/libspdm_com_crypto_service_session.c, library/spdm_crypt_lib/libspdm_crypt_crypt.c, os_stub/spdm_device_secret_lib_sample/cert.c, os_stub/spdm_device_secret_lib_sample/lib.c
Addresses #75
Fixes missing return values for spdm_hash_all. For certain usages of spdm_hash_all, which were only meant for debug code, gated the usage behind DEBUG_CODE macro to ensure the functions wouldn't be called in Release builds.
Signed-off-by: Timothy Prinz <tandrewprinz@nvidia.com>
=> Fixing missing return values for spdm_hash_all

library/spdm_common_lib/CMakeLists.txt, library/spdm_common_lib/libspdm_com_context_data.c, library/spdm_common_lib/libspdm_com_crypto_service.c, library/spdm_common_lib/libspdm_com_crypto_service_session.c
Addresses #75.
Addresses most remaining functions - these functions use allocated contexts heavily, so have to be more careful when checking for and handling error, so that we do not unintentionally disrupt state.
Note: I did NOT address the libspdm_append_message_k and libspdm_append_message_f buffers yet. These functions are not written in a way to handle errors gracefully. If we fail at any point during these functions, the message hashes and buffers can enter an unrecoverable state. The changes required to gracefully handle this error would need close care when reviewing, and so I will defer it to a later PR. This probably deserves its own issue.
Signed-off-by: Timothy Prinz <tandrewprinz@nvidia.com>
=> Fixing return values for most spdm_hash* and spdm_hmac* functions

include/library/spdm_secured_message_lib.h, library/spdm_crypt_lib/libspdm_crypt_crypt.c, library/spdm_requester_lib/libspdm_req_key_update.c, library/spdm_secured_message_lib/libspdm_secmes_session.c
Addresses #75 
The purpose of this PR was to fix any missing return value checks for functions that may not have declarations in header files. This is so that they were not overlooked when doing the large swaths of checking via adding __attribute__((warn_unused_result)) to every function declaration. This didn't catch many/any functions that were only defined internally, but did provide a few warnings for other functions declared in headers we haven't gotten do yet.
Also updates the spdm_create_update_session_data_key and spdm_activate_update_session_data_key to be single operation. With error checks, these could fail halfway and have halfway completed result, which is a pain to deal with. Changing to single operation at a time, to try and prevent.
=> Additional return value checks fixed

library/spdm_responder_lib/libspdm_rsp_respond_if_ready.c
Fix #421
This is dispatch function.
Following same pattern, we should either add ASSERT for all, or not add ASSERT for all.
Since no other functions are using ASSERT, we remove it here.
=> Remove unnecessary assert for request_response_code

include/internal/libspdm_requester_lib.h, include/library/spdm_requester_lib.h, library/spdm_requester_lib/libspdm_req_communication.c, library/spdm_requester_lib/libspdm_req_key_exchange.c, library/spdm_requester_lib/libspdm_req_psk_exchange.c, unit_test/fuzzing/test_requester/test_spdm_requester_key_exchange/key_exchange.c, unit_test/fuzzing/test_requester/test_spdm_requester_psk_exchange/psk_exchange.c, unit_test/test_size/test_size_of_spdm_requester/spdm_requester_session.c, unit_test/test_spdm_requester/key_exchange.c, unit_test/test_spdm_requester/psk_exchange.c
This is for SPDM 1.2 compatibility.
=> Add session_policy to libspdm_start_session().

include/library/spdm_requester_lib.h, library/spdm_requester_lib/libspdm_req_get_measurements.c, unit_test/fuzzing/test_requester/test_spdm_requester_get_measurements/get_measurements.c, unit_test/test_spdm_requester/get_measurements.c
This is for SPDM 1.2 compatibility.
=> Add content_change in libspdm_get_measurement().

include/library/spdm_crypt_lib.h, unit_test/fuzzing/test_secured_message/test_spdm_encode_secured_message/spdm_encode_secured_message.c, unit_test/fuzzing/test_transport/test_spdm_transport_mctp_encode_message/transport_mctp_encode_message.c, unit_test/fuzzing/test_transport/test_spdm_transport_pci_doe_encode_message/spdm_transport_pci_doe_encode_message.c
=> Limit the test encoding buffer size to avoid assert.

unit_test/test_spdm_common/context_data.c
Fix: #450 
Change the hard code to fix test_spdm_common unit test error.
Because the size of viod* is different on different machine, test_spdm_common unit test error is happen in ia32. Change the hard code to fix it.
Make the test case id correct.
=> Change the hard code to fix test_spdm_common error  and make the test case id correct

include/library/spdm_common_lib.h, include/library/spdm_secured_message_lib.h
The last element in an enum cannot have a trailing comma; that was introduced in C99.
=> Enhance C89 compatibility.

library/spdm_common_lib/libspdm_com_crypto_service.c
Fix: #462 
Add some comment to describe the expected behavior to avoid confusing.
=> Add comment to spdm_verify_peer_cert_chain_buffer to avoid confusing

library/spdm_requester_lib/libspdm_req_handle_error_response.c, library/spdm_responder_lib/libspdm_rsp_encap_challenge.c, library/spdm_responder_lib/libspdm_rsp_encap_get_certificate.c, library/spdm_responder_lib/libspdm_rsp_encap_get_digests.c, library/spdm_responder_lib/libspdm_rsp_encap_key_update.c
Fix: #402 
Add check version for mutual function in spdm_responder_lib.
Add missing check the SPDM Version filed of response message in spdm_requester_lib.
=> Add check version for mutual function and add missing check in spdm_requester_lib

library/spdm_requester_lib/libspdm_req_encap_certificate.c, library/spdm_requester_lib/libspdm_req_encap_challenge_auth.c, library/spdm_requester_lib/libspdm_req_encap_digests.c, library/spdm_requester_lib/libspdm_req_encap_key_update.c, library/spdm_responder_lib/libspdm_rsp_algorithms.c, library/spdm_responder_lib/libspdm_rsp_certificate.c, library/spdm_responder_lib/libspdm_rsp_challenge_auth.c, library/spdm_responder_lib/libspdm_rsp_digests.c, library/spdm_responder_lib/libspdm_rsp_end_session.c, library/spdm_responder_lib/libspdm_rsp_finish.c, library/spdm_responder_lib/libspdm_rsp_heartbeat.c, library/spdm_responder_lib/libspdm_rsp_key_exchange.c, library/spdm_responder_lib/libspdm_rsp_key_update.c, library/spdm_responder_lib/libspdm_rsp_measurements.c, library/spdm_responder_lib/libspdm_rsp_psk_exchange.c, library/spdm_responder_lib/libspdm_rsp_psk_finish.c, library/spdm_responder_lib/libspdm_rsp_respond_if_ready.c, unit_test/test_spdm_responder/algorithms.c, unit_test/test_spdm_responder/capabilities.c, unit_test/test_spdm_responder/certificate.c, unit_test/test_spdm_responder/digests.c, unit_test/test_spdm_responder/end_session.c, unit_test/test_spdm_responder/finish.c, unit_test/test_spdm_responder/heartbeat.c, unit_test/test_spdm_responder/key_update.c, unit_test/test_spdm_responder/measurements.c, unit_test/test_spdm_responder/psk_exchange.c, unit_test/test_spdm_responder/psk_finish.c
Fix: #237
For any received command (except GET_VERSION),
the responder should check if the command uses the negotiated version.
=> Add check version for of requester message

include/internal/libspdm_common_lib.h, include/library/spdm_crypt_lib.h, library/spdm_common_lib/libspdm_com_context_data.c, library/spdm_common_lib/libspdm_com_crypto_service.c, library/spdm_common_lib/libspdm_com_crypto_service_session.c, library/spdm_crypt_lib/libspdm_crypt_crypt.c, library/spdm_requester_lib/libspdm_req_get_certificate.c, library/spdm_responder_lib/libspdm_rsp_encap_get_certificate.c, unit_test/fuzzing/test_requester/test_spdm_requester_challenge/challenge.c, unit_test/fuzzing/test_requester/test_spdm_requester_end_session/end_session.c, unit_test/fuzzing/test_requester/test_spdm_requester_get_measurements/get_measurements.c, unit_test/fuzzing/test_requester/test_spdm_requester_heartbeat/heartbeat.c, unit_test/fuzzing/test_requester/test_spdm_requester_key_exchange/key_exchange.c, unit_test/fuzzing/test_requester/test_spdm_requester_key_update/key_update.c, unit_test/fuzzing/test_requester/test_spdm_requester_psk_exchange/psk_exchange.c, unit_test/fuzzing/test_requester/test_spdm_requester_psk_finish/psk_finish.c, unit_test/fuzzing/test_responder/test_spdm_responder_encap_challenge/encap_challenge.c, unit_test/fuzzing/test_responder/test_spdm_responder_finish_rsp/finish_rsp.c, unit_test/test_spdm_requester/challenge.c, unit_test/test_spdm_requester/end_session.c, unit_test/test_spdm_requester/finish.c, unit_test/test_spdm_requester/get_certificate.c, unit_test/test_spdm_requester/get_measurements.c, unit_test/test_spdm_requester/heartbeat.c, unit_test/test_spdm_requester/key_exchange.c, unit_test/test_spdm_requester/key_update.c, unit_test/test_spdm_requester/psk_exchange.c, unit_test/test_spdm_requester/psk_finish.c, unit_test/test_spdm_responder/finish.c
peer_used_cert_chain_buffer.
about 4K is saved for context size.
Fix: #147 
=> cache peer_used_cert_chain_buffer_hash instead of

unit_test/fuzzing/spdm_unit_fuzzing_common/toolchain_harness.c
=> Restore LIBFUZZER's "Function Implicit Declaration"

include/internal/libspdm_common_lib.h, library/spdm_common_lib/libspdm_com_context_data.c, library/spdm_common_lib/libspdm_com_opaque_data.c, library/spdm_requester_lib/libspdm_req_get_version.c, unit_test/test_spdm_requester/key_exchange.c, unit_test/test_spdm_requester/psk_exchange.c
Fix: #480 
Sort for secured message binding version.
Find the first match version in loop.
Fix the hardcode for secured message binding version.
Make sort function consistent and remove sort function to common lib.
=> Fix the hardcode for secured message binding version

library/spdm_requester_lib/libspdm_req_get_version.c
Fix: #467 
The req_get_vesrion should free hash first when the m1m2 didn't equal 0.
Then req_get_vesrion reset context.
=> Move libspdm_reset_message_*() before libspdm_reset_context()

library/spdm_crypt_lib/libspdm_crypt_crypt.c
Resolve unused variable warning when LIBSPDM_SM2_KEY_EXCHANGE_SUPPORT
is disabled
=> Resolve compile warning without SM2 Key Exchange

CMakeLists.txt, unit_test/test_size/rnglib_null/CMakeLists.txt, unit_test/test_size/rnglib_null/rnglib.c, unit_test/test_size/test_size_of_spdm_requester/CMakeLists.txt, unit_test/test_size/test_size_of_spdm_responder/CMakeLists.txt
It is commented by default.
It will be used to calculate size with real cryptolib used such as mbedtls.
=> Add rnglib_null to support size calculation.

include/hal/base.h
MAX, MIN, NULL, TRUE, and FALSE are very common defines, redefining them
causes warnings if they are already defined.
This change only redefines these common macros if they are not already
defined.
=> Protect redefinition of common defines

library/spdm_responder_lib/libspdm_rsp_algorithms.c
This change resolves the switch missing default case compilation warning
within the spdm_get_response_algorithms function.
SPDM specification 1.2.0 indicates:
The algorithm structure table need be present only if the Responder
supports that AlgType.
Based on this wording, we can silently skip over unsupportd algorithm
types.
=> Resolve warning in spdm_get_response_algorithms

library/spdm_common_lib/libspdm_com_crypto_service.c, library/spdm_crypt_lib/libspdm_crypt_crypt.c
This change resolves a series of switch missing default case warnings
that are functionality equivalent to the original code.
=> Resolve switch missing default case warnings

library/spdm_responder_lib/libspdm_rsp_receive_send.c
This change is functionality equivalent to previous code and only
addresses compile warnings regarding missing default case in switch
statement.
=> Resolve switch missing default case warning

unit_test/test_spdm_common/context_data.c
Minor change to address pointer-to-integer cast warnings on 32-bit architectures within spdm_common unit tests (observed with GCC for ARMv7 originally, and also on IA32).
> error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
note: in expansion of macro 'assert_int_equal'
note: in expansion of macro 'cast_to_uintmax_type'
uintmax_t should be large enough to hold a 32-bit pointer, but depending on the platform can be of a different underlying type. There was already an `assert_ptr_equal()` handy which first converts the pointers to the `uintptr_t` integral type.
Possibly related to the comment in https://github.com/DMTF/libspdm/pull/550 regarding additional CI configurations.
=> Address pointer-to-int-cast warnings on 32-bit architectures

os_stub/memlib/copy_mem.c
=> Resolve copy_mem discards qualifiers compile warning

os_stub/memlib/compare_mem.c
=> Resolve const_compare_mem discards qualifiers compile warning

include/library/spdm_crypt_lib.h, library/spdm_crypt_lib/libspdm_crypt_crypt.c
This change resolves the "cast discards qualifiers from pointer target
type" warning for libspdm_get_dmtf_subject_alt_name_from_bytes by
removing the const qualifier from the input buffer.
The mbedtls mbedtls_asn1_get_len function requires the buffer to not be
constant which forces this lack of const up the stack.
=> Resolve compile warning for libspdm_get_dmtf_subject_alt_name_from_bytes

include/hal/library/cryptlib.h, library/spdm_crypt_lib/libspdm_crypt_crypt.c, os_stub/cryptlib_mbedtls/pk/x509.c, os_stub/cryptlib_null/pk/x509.c, os_stub/cryptlib_openssl/pk/x509.c, unit_test/test_crypt/x509_verify.c
This change resolves the "cast discards qualifiers from pointer target
type" for  x509_get_extension_data function by marking the oid filed as
a pointer to const.
=> Resolve compile warning for x509_get_extension_data

.github/workflows/compliance-checks.yml
The current implementation of uncrustify style application silently
fails if the style is not compliant. This change shows the diff between
the current implementation and style corrections done by uncrustify.
=> Add uncrustify style problem output on failure

README.md
Splitting up the sample cmake block into individual blocks to make it easier to copy/paste.
=> Split example cmake sections to make it easier to copy-paste.

.github/workflows/build.yml
Github VMs report at least two processors. 
=> Make Linux build a little bit quicker

include/hal/library/memlib.h, library/spdm_responder_lib/libspdm_rsp_challenge_auth.c, library/spdm_responder_lib/libspdm_rsp_measurements.c, os_stub/memlib/copy_mem.c, unit_test/test_size/intrinsiclib/copy_mem.c
@jyao1 @steven-bellock @taprinz 
This is a proposal for a copy_mem_s function that behaves similar to memcpy_s. This is just a review for the function change itself.  Once this new function is approved, I will add another PR to change all the calling locations to the new function and remove the older copy_mem function.
=> Proposal for copy_mem_s function that adds the destination size as parameter.

library/spdm_common_lib/libspdm_com_context_data.c
That aligns current spec version.
=> Correct default secured message version to 1.0.

library/spdm_common_lib/libspdm_com_context_data.c, library/spdm_responder_lib/libspdm_rsp_error.c
In some cases, if the version is not negotiated, the ERROR message shall use version=0x10.
=> Fix version=0 in ERROR message.

library/spdm_requester_lib/libspdm_req_encap_challenge_auth.c
This is to avoid assert in copy_mem.
=> Check opaque data ptr before copy_mem.

include/internal/libspdm_common_lib.h, include/library/spdm_common_lib.h, library/spdm_common_lib/libspdm_com_context_data.c, library/spdm_responder_lib/libspdm_rsp_finish.c, library/spdm_responder_lib/libspdm_rsp_psk_finish.c, library/spdm_responder_lib/libspdm_rsp_receive_send.c
Fix: #489
Add error_return_policy to control send DECRYPT_ERROR or drop request.
If the handle_error_return_policy BIT0 set, drop the request silently.
=> Add a plocicy to control send DECRYPT_ERROR or drop request silently

library/spdm_requester_lib/libspdm_req_communication.c, library/spdm_requester_lib/libspdm_req_end_session.c, library/spdm_requester_lib/libspdm_req_finish.c, library/spdm_requester_lib/libspdm_req_heartbeat.c, library/spdm_requester_lib/libspdm_req_key_update.c, library/spdm_requester_lib/libspdm_req_psk_finish.c, library/spdm_responder_lib/libspdm_rsp_encap_key_update.c, unit_test/test_spdm_requester/end_session.c, unit_test/test_spdm_requester/finish.c, unit_test/test_spdm_requester/heartbeat.c, unit_test/test_spdm_requester/key_update.c, unit_test/test_spdm_requester/psk_finish.c
Fix: #488
For handshake and application phase:
If ErrorCode = DecryptError, the session shall immediately terminate and proceed to session termination.
=> Add SPDM_ERROR_CODE_DECRYPT_ERROR handle for requester

include/library/spdm_responder_lib.h, library/spdm_responder_lib/libspdm_rsp_receive_send.c
Fix: #490 
When the callback function drop the response, the return response_size is 0.
And the return status is RETURN_UNSUPPORTED.
=> Add a check when callback function drop the response

library/spdm_requester_lib/libspdm_req_finish.c, library/spdm_requester_lib/libspdm_req_psk_finish.c
Because the libspdm_free_session_id function feature contain libspdm_clear_handshake_secret, the code is duplicate.
=> Delete the duplicate code for clear_handshake_secret

include/internal/libspdm_requester_lib.h, library/spdm_requester_lib/libspdm_req_communication.c, library/spdm_requester_lib/libspdm_req_get_version.c, unit_test/fuzzing/test_requester/test_spdm_requester_get_version/get_version.c, unit_test/test_spdm_requester/get_version.c
It will be used in conformance test.
=> Add full response version info in get_version API.

unit_test/test_spdm_responder/end_session.c, unit_test/test_spdm_responder/finish.c, unit_test/test_spdm_responder/heartbeat.c, unit_test/test_spdm_responder/key_update.c, unit_test/test_spdm_responder/measurements.c, unit_test/test_spdm_responder/psk_exchange.c, unit_test/test_spdm_responder/psk_finish.c, unit_test/test_spdm_responder/respond_if_ready.c
Change code under unit_test/test_spdm_responder to use copy_mem_s.
=> Use copy_mem_s in unit_test/test_spdm_responder/*

unit_test/fuzzing/test_requester/test_spdm_requester_psk_finish/psk_finish.c
=> fix memory leak with initial corpus for test_spdm_requester_psk_finish

os_stub/cryptlib_mbedtls/hmac/hmac_sha.c, os_stub/cryptlib_mbedtls/pem/pem.c, os_stub/cryptlib_mbedtls/rand/rand.c, os_stub/cryptlib_mbedtls/sys_call/timer_wrapper_host.c, os_stub/cryptlib_null/cipher/aead_aes_gcm.c, os_stub/cryptlib_openssl/pem/pem.c, os_stub/cryptlib_openssl/pk/sm2.c, os_stub/openssllib/rand_pool.c, os_stub/spdm_device_secret_lib_sample/cert.c, os_stub/spdm_device_secret_lib_sample/lib.c
Use copy_mem_s in these files:
os_stub/cryptlib_mbedtls/hmac/hmac_sha.c
os_stub/cryptlib_mbedtls/pem/pem.c
os_stub/cryptlib_mbedtls/rand/rand.c
os_stub/cryptlib_mbedtls/sys_call/timer_wrapper_host.c
os_stub/cryptlib_null/cipher/aead_aes_gcm.c
os_stub/cryptlib_openssl/pem/pem.c
os_stub/cryptlib_openssl/pk/sm2.c
os_stub/openssllib/rand_pool.c
os_stub/spdm_device_secret_lib_sample/cert.c
os_stub/spdm_device_secret_lib_sample/lib.c
=> Use copy_mem_s in os_stub files part 1.

include/hal/library/platform_lib.h, os_stub/platform_lib/watchdog.c
=> change libspdm_start_watchdog uint64_t seconds to uint16_t.

include/hal/library/memlib.h, os_stub/memlib/copy_mem.c
Get rid of copy_mem_s name. All to use copy_mem with same parameters.
=> Remove copy_mem_s name from memlib. All to use copy_mem.

library/spdm_crypt_lib/libspdm_crypt_crypt.c, library/spdm_requester_lib/libspdm_req_challenge.c, library/spdm_requester_lib/libspdm_req_encap_request.c, library/spdm_requester_lib/libspdm_req_end_session.c, library/spdm_requester_lib/libspdm_req_finish.c, library/spdm_requester_lib/libspdm_req_get_capabilities.c, library/spdm_requester_lib/libspdm_req_get_certificate.c, library/spdm_requester_lib/libspdm_req_get_digests.c, library/spdm_requester_lib/libspdm_req_get_measurements.c, library/spdm_requester_lib/libspdm_req_get_version.c, library/spdm_requester_lib/libspdm_req_handle_error_response.c, library/spdm_requester_lib/libspdm_req_heartbeat.c, library/spdm_requester_lib/libspdm_req_key_exchange.c, library/spdm_requester_lib/libspdm_req_key_update.c, library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c, library/spdm_requester_lib/libspdm_req_psk_exchange.c, library/spdm_requester_lib/libspdm_req_psk_finish.c, library/spdm_responder_lib/libspdm_rsp_algorithms.c, library/spdm_responder_lib/libspdm_rsp_capabilities.c, library/spdm_responder_lib/libspdm_rsp_encap_response.c, library/spdm_responder_lib/libspdm_rsp_measurements.c, library/spdm_responder_lib/libspdm_rsp_receive_send.c, library/spdm_responder_lib/libspdm_rsp_version.c, library/spdm_secured_message_lib/libspdm_secmes_context_data.c, library/spdm_secured_message_lib/libspdm_secmes_session.c, library/spdm_transport_mctp_lib/libspdm_mctp_common.c, library/spdm_transport_mctp_lib/libspdm_mctp_mctp.c, library/spdm_transport_pcidoe_lib/libspdm_doe_common.c, library/spdm_transport_pcidoe_lib/libspdm_doe_pcidoe.c
Fix: #576 
in spdm_crypt_lib, spdm_requester_lib, spdm_responder_lib,
spdm_secured_message_lib, spdm_secured_message_lib and
spdm_transport_mctp_lib, spdm_transport_pcidoe_lib
=> add LIBSPDM_ or libspdm_ for any external symbol or MACRO.

include/library/spdm_common_lib.h, include/library/spdm_return_status.h, library/spdm_requester_lib/libspdm_req_get_version.c, unit_test/test_spdm_requester/get_version.c
Add spdm_return_status.h to library\spdm_common_lib.h.
Create a new macro to check and return on error.
=> Transition GET_VERSION to new error codes

library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c, unit_test/test_spdm_requester/negotiate_algorithms.c
The function returns LIBSPDM_STATUS_NEGOTIATION_FAIL to preserve the current behavior. When issue #85 gets resolved then this error message may go away.
=> Initial commit for new error codes for NEGOTIATE_ALGORITHMS

include/internal/libspdm_common_lib.h, library/spdm_common_lib/libspdm_com_context_data.c, library/spdm_requester_lib/libspdm_req_challenge.c, library/spdm_requester_lib/libspdm_req_communication.c, library/spdm_requester_lib/libspdm_req_encap_request.c, library/spdm_requester_lib/libspdm_req_end_session.c, library/spdm_requester_lib/libspdm_req_finish.c, library/spdm_requester_lib/libspdm_req_get_capabilities.c, library/spdm_requester_lib/libspdm_req_get_certificate.c, library/spdm_requester_lib/libspdm_req_get_digests.c, library/spdm_requester_lib/libspdm_req_get_measurements.c, library/spdm_requester_lib/libspdm_req_get_version.c, library/spdm_requester_lib/libspdm_req_handle_error_response.c, library/spdm_requester_lib/libspdm_req_heartbeat.c, library/spdm_requester_lib/libspdm_req_key_exchange.c, library/spdm_requester_lib/libspdm_req_key_update.c, library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c, library/spdm_requester_lib/libspdm_req_psk_exchange.c, library/spdm_requester_lib/libspdm_req_psk_finish.c, library/spdm_responder_lib/libspdm_rsp_communication.c
It is unnecessary, because libspdm context already cached it.
=> remove msg_buf_ptr field in release_buffer.

unit_test/test_spdm_requester/challenge.c, unit_test/test_spdm_requester/finish.c, unit_test/test_spdm_requester/get_capabilities.c, unit_test/test_spdm_requester/get_certificate.c, unit_test/test_spdm_requester/get_digests.c, unit_test/test_spdm_requester/get_measurements.c, unit_test/test_spdm_requester/get_version.c, unit_test/test_spdm_requester/key_exchange.c, unit_test/test_spdm_requester/negotiate_algorithms.c, unit_test/test_spdm_requester/psk_exchange.c, unit_test/test_spdm_requester/psk_finish.c, unit_test/test_spdm_responder/algorithms.c, unit_test/test_spdm_responder/capabilities.c, unit_test/test_spdm_responder/certificate.c, unit_test/test_spdm_responder/challenge_auth.c, unit_test/test_spdm_responder/digests.c, unit_test/test_spdm_responder/finish.c, unit_test/test_spdm_responder/key_exchange.c, unit_test/test_spdm_responder/measurements.c, unit_test/test_spdm_responder/psk_exchange.c, unit_test/test_spdm_responder/psk_finish.c, unit_test/test_spdm_responder/version.c
This commit contains one new test case that verifies if the correct data was appended to the correct buffer regarding the message transcripts. It contains one test for each of the following messages:
- requester: get_version, get_capabilities, negotiate_algorithms, get_digests, get_certificate, get_measurements, challenge, key_exchange, finish, psk_exchange, psk_finish.
- responder: version, capabilities, algorithms, digests, certificate, measurements, challenge_auth, key_exchange, finish, psk_exchange, psk_finish.
Note that previous test cases only verified if the amount of data was correctly added to the buffers. Now, the test cases in this commit extend the test by also verifying if the correct data (message request and response) was appended to the correct buffer (A, B, C, M, K, or F) …
=> New test cases to verify transcript buffers contents

include/internal/libspdm_responder_lib.h, include/library/spdm_responder_lib.h
They are removed in io redesign by mistake.
=> Add libspdm_process_request and libspdm_build_response back to external.

.github/workflows/build.yml, CMakeLists.txt, unit_test/fuzzing/run_initial_seed.sh
Get the test result by checking the return value of test program.
Add a new command 'copy_seed' to copy the seed files.
Enable the basic test with initial seed.
fix: #749
=> set LIBSPDM_DEBUG_LIBSPDM_ASSERT_CONFIG=0 to avoid ASSERT_DEADLOOP.

.github/workflows/build.yml, unit_test/test_spdm_common/context_data.c
Fix: #775 
Add unit_test: test_spdm_common to CI test.
Fit the unit_test: test_spdm_common error.
=> Add unit_test:test_spdm_common to CI test and fix the test_spdm_common error

include/industry_standard/spdm_secured_message.h, include/internal/libspdm_common_lib.h, include/library/spdm_lib_config.h, library/spdm_common_lib/libspdm_com_context_data.c
The consumer need to know the required sender/receiver buffer size.
=> Add macro for the data size in IO redefine.

unit_test/fuzzing/spdm_unit_fuzzing_common/common.c
fix memory leak for scratch_buffer
fix: #813
=> fix memory leak for scratch_buffer

include/library/spdm_common_lib.h, include/library/spdm_transport_mctp_lib.h, include/library/spdm_transport_pcidoe_lib.h, library/spdm_requester_lib/libspdm_req_send_receive.c, library/spdm_responder_lib/libspdm_rsp_receive_send.c, library/spdm_transport_mctp_lib/libspdm_mctp_common.c, library/spdm_transport_pcidoe_lib/libspdm_doe_common.c, unit_test/include/library/spdm_transport_test_lib.h, unit_test/spdm_transport_test_lib/common.c, unit_test/test_spdm_requester/get_measurements.c, unit_test/test_spdm_requester/key_update.c, unit_test/test_spdm_requester/psk_finish.c
transport lib should be agnostic on the buffer management.
=> move scratch buffer out of transport lib.

library/spdm_common_lib/libspdm_com_context_data.c, library/spdm_requester_lib/libspdm_req_get_version.c
fix #850 by sorting local copy of request version list.
Signed-off-by: Longlong Yang <longlong.yang@intel.com>
=> spdm_common_lib: libspdm_negotiate_connection_version corrupts request buffer

README.md
And capitalize CMake were appropriate.
=> Add example for Visual Studio project file

os_stub/rnglib/rng_std.c
It appears since CI only builds linux and windows variants of the
rnglib, the std variant was left behind on the conversion to stdint
types.
=> Update rnglib std variant to stdint

CMakeLists.txt
Fix https://github.com/DMTF/libspdm/issues/864
Use openssl to align the readme and current CI.
=> openssl name

library/spdm_responder_lib/libspdm_rsp_communication.c
Fixing #868
The session_id is a pointer point to receiver buffer, and it will be
dereferenced during construst response message. However, the buffer
is released after process the request message. So it may cause
use-after-free error.
Signed-off-by: Troy Lee <troy_lee@aspeedtech.com>
=> Buffer use after free

include/industry_standard/spdm.h, include/internal/libspdm_common_lib.h, include/internal/libspdm_responder_lib.h, include/library/spdm_common_lib.h, include/library/spdm_device_secret_lib.h, include/library/spdm_lib_config.h, include/library/spdm_requester_lib.h, library/spdm_common_lib/libspdm_com_context_data.c, library/spdm_requester_lib/CMakeLists.txt, library/spdm_requester_lib/libspdm_req_set_certificate.c, library/spdm_responder_lib/CMakeLists.txt, library/spdm_responder_lib/libspdm_rsp_receive_send.c, library/spdm_responder_lib/libspdm_rsp_set_certificate.c, os_stub/spdm_device_secret_lib_null/lib.c, os_stub/spdm_device_secret_lib_sample/lib.c, unit_test/test_spdm_requester/CMakeLists.txt, unit_test/test_spdm_requester/set_certificate.c, unit_test/test_spdm_requester/test_spdm_requester.c, unit_test/test_spdm_responder/CMakeLists.txt, unit_test/test_spdm_responder/set_certificate_rsp.c, unit_test/test_spdm_responder/test_spdm_responder.c
Fix: #506 
- Add SET_CERTIFICATE new feature for libspdm 1.2.
- Add unit_test for new libspdm 1.2 feature: set_certificate.
- Add set_certificate new feature support for emu test.
Set cert for slot_id 0 and 1 in emu/unit test suceessfully: 
1. Set cert for slot_id 0 in secure environment;
2. Set cert for slot_id 1 in secure session.
=> Add set cert new feature for libspdm 1.2

unit_test/fuzzing/test_requester/test_spdm_requester_encap_certificate/encap_certificate.c, unit_test/fuzzing/test_requester/test_spdm_requester_encap_digests/encap_digests.c, unit_test/fuzzing/test_responder/test_spdm_responder_certificate/certificate.c, unit_test/fuzzing/test_responder/test_spdm_responder_challenge_auth/challenge_auth.c, unit_test/fuzzing/test_responder/test_spdm_responder_digests/digests.c, unit_test/fuzzing/test_responder/test_spdm_responder_encap_get_certificate/encap_get_certificate.c, unit_test/fuzzing/test_responder/test_spdm_responder_encap_get_digests/encap_get_digests.c, unit_test/fuzzing/test_responder/test_spdm_responder_encap_response/encap_response.c, unit_test/fuzzing/test_responder/test_spdm_responder_finish_rsp/finish_rsp.c, unit_test/fuzzing/test_responder/test_spdm_responder_key_exchange/key_exchange.c, unit_test/fuzzing/test_responder/test_spdm_responder_measurements/measurements.c, unit_test/fuzzing/test_responder/test_spdm_responder_psk_exchange_rsp/psk_exchange_rsp.c, unit_test/fuzzing/test_responder/test_spdm_responder_psk_finish_rsp/psk_finish_rsp.c
Fix : #871
Fix "reset message k " on test_spdm_responder_psk_exchange_rsp,and fix similar problems about "reset message cache in spdm context"
Signed-off-by: yaohuixguo <yaohuix.guo@intel.com>
=> Fix "reset message k " on fuzzing test case

include/internal/libspdm_common_lib.h, library/spdm_common_lib/libspdm_com_crypto_service.c
This commit passes a libspdm_large_managed_buffer_t pointer directly
to libspdm_calculate_l1l2 to save a l1l2 message copy. It also
saves 'LIBSPDM_MAX_MESSAGE_BUFFER_SIZE' bytes of stack usage.
=> Optimize function libspdm_calculate_l1l2

library/spdm_common_lib/libspdm_com_context_data.c
This commit moves the VCA logic inside the block of
'digest_context_l1l2 == NULL' in libspdm_append_message_m(). It
could avoid VCA being added into the digest_context_l1l2 each
time the libspdm_append_message_m() function is called, which
causes incompatability between requestor and respondor that are
compiled with different LIBSPDM_RECORD_TRANSCRIPT_DATA_SUPPORT.
=> Avoid adding VCA multiple times into digest_context_l1l2

os_stub/cryptlib_openssl/pk/x509.c
False should be returned, when no asn1 object is inputted.
When parse asn1 data cyclically, libspdm_asn1_get_tag will return the true in the end of the asn1 data for any tag type.
The follow example code  will be error with old libspdm_asn1_get_tag code logic :
```
for (index = 0; index < 2; index++) {
ret = libspdm_asn1_get_tag(&ptr, end, &obj_len,
LIBSPDM_CRYPTO_ASN1_SEQUENCE |
LIBSPDM_CRYPTO_ASN1_CONSTRUCTED);
if (ret) {
ptr += obj_len;
} else {
break;
}
}
```
=> Fix libspdm_asn1_get_tag bug in cryptlib_openssl

library/spdm_requester_lib/libspdm_req_psk_exchange.c, library/spdm_responder_lib/libspdm_rsp_psk_exchange.c, unit_test/test_spdm_requester/psk_exchange.c, unit_test/test_spdm_responder/psk_exchange.c
We added unit test cases for the psk_exchange messages, expanding the existing tests for the message.
These tests verify the device behavior when receiving measurement hashes, heartbeat periods, responder context, and opaque data. There is also a test in which a wrong responder verify data is provided to check if the device deals correctly with failures in this validation.
Additionally, we corrected two minor errors in libspdm_req_psk_exchange.c and libspdm_rsp_psk_exchange.c: on line 298 and 169, respectively, the code always considered the presence of the OpaqueData field, when it is optional.
In this push request:
1) Additional unit test cases for psk_exchange requester (13 new tests)
- cases 14 to 19 are related to measurement hashes
- cases 20 to 22 are related to the heartbeat …
=> New unit test cases for the psk_exchange messages

doc/test.md, unit_test/fuzzing/fuzzing_AFLTurbo.sh
Changes:
1. Added guide for building and using AFLturbo for fuzzing.
2. script to run AFLTurbo for each fuzzing test case.
Signed-off-by: Jafar Sarif <jafar.sarif@intel.com>
=> Added start guide and script for fuzzing with AFLTurbo

include/industry_standard/spdm.h, os_stub/spdm_device_secret_lib_sample/lib.c, unit_test/test_spdm_responder/csr.c
Fix: #993 
- Add gen CSR with non-null right and wrong req_info unit test;
- Add gen CSR with non-null opaque_data unit test;
- Add returned CSR not zero check ;
- Add  returned CSR match req_info check;
=> Improve get_csr unit test

library/spdm_requester_lib/libspdm_req_send_receive.c
Cast 2 to type uint64_t
Fix #998
Signed-off-by: Wei Liu <wei3.liu@intel.com>
=> Fix potentially overflowing expression in libspdm_req_send_receive.c

library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c
Removed the unreached "default" case in line 171 and 470
Fix #999 
Fix #1000
Signed-off-by: Wei Liu <wei3.liu@intel.com>
=> Remove dead code in libspdm_secmes_encode_decode.c

os_stub/cryptlib_mbedtls/rand/rand.c
=> Use libspdm_copy_mem instead of integer casting

unit_test/fuzzing/spdm_unit_fuzzing_common/toolchain_harness.h
`toolchain_harness.h` needlessly defines `NULL` when it already comes from `stdlib.h`. This has been causing warnings with CLANG.
=> Remove NULL definition

include/internal/libspdm_common_lib.h, library/spdm_common_lib/libspdm_com_crypto_service.c, library/spdm_requester_lib/libspdm_req_encap_challenge_auth.c, library/spdm_responder_lib/libspdm_rsp_challenge_auth.c, unit_test/test_spdm_responder/challenge_auth.c
Fix: #1013 
Because the populated slot store cert_chain may be not continuous, the get slot number logic is changed.
And the PR has passed unit test and emu test.
=> challenge_auth param2 slot mask should return all populated slots

unit_test/fuzzing/test_requester/test_spdm_requester_encap_request/encap_request.c, unit_test/fuzzing/test_requester/test_spdm_requester_end_session/end_session.c, unit_test/fuzzing/test_requester/test_spdm_requester_get_csr/get_csr.c, unit_test/fuzzing/test_requester/test_spdm_requester_get_digests/get_digests.c, unit_test/fuzzing/test_requester/test_spdm_requester_get_measurements/get_measurements.c, unit_test/fuzzing/test_requester/test_spdm_requester_heartbeat/heartbeat.c, unit_test/fuzzing/test_requester/test_spdm_requester_key_exchange/key_exchange.c, unit_test/fuzzing/test_requester/test_spdm_requester_key_update/key_update.c, unit_test/fuzzing/test_requester/test_spdm_requester_psk_finish/psk_finish.c, unit_test/fuzzing/test_requester/test_spdm_requester_set_certificate/set_certificate.c
Fix : #1084 
limit the encoding buffer to avoid assert.
=> Fix the problem that the test case does not limit the buffer in the security message

os_stub/cryptlib_mbedtls/pk/rsa_basic.c, os_stub/cryptlib_mbedtls/pk/rsa_ext.c
Fix: #1079 
The `mbedtls_rsa_complete` function completes an RSA context from a set of imported core parameters.
To setup an RSA public key, precisely N and E must have been imported.
To setup an RSA private key, sufficient information must be present for the other parameters to be derivable.
=> Change mbedtls_rsa_complete function location to setup RSA key

os_stub/cryptlib_openssl/pk/ec.c
=> Fix ariable ec_key going out of scope leaks the storage it points to.

include/internal/libspdm_common_lib.h, include/internal/libspdm_secured_message_lib.h, include/library/spdm_secured_message_lib.h, library/spdm_common_lib/libspdm_com_context_data.c, library/spdm_common_lib/libspdm_com_context_data_session.c, library/spdm_common_lib/libspdm_com_crypto_service_session.c, library/spdm_secured_message_lib/libspdm_secmes_context_data.c, library/spdm_secured_message_lib/libspdm_secmes_session.c, unit_test/fuzzing/test_requester/test_spdm_requester_finish/finish.c, unit_test/fuzzing/test_requester/test_spdm_requester_psk_finish/psk_finish.c, unit_test/fuzzing/test_responder/test_spdm_responder_finish_rsp/finish_rsp.c, unit_test/fuzzing/test_responder/test_spdm_responder_psk_finish_rsp/psk_finish_rsp.c, unit_test/test_spdm_requester/finish.c, unit_test/test_spdm_requester/key_exchange.c, unit_test/test_spdm_requester/psk_exchange.c, unit_test/test_spdm_requester/psk_finish.c, unit_test/test_spdm_responder/finish.c, unit_test/test_spdm_responder/psk_finish.c, unit_test/test_spdm_responder/respond_if_ready.c
Fix https://github.com/DMTF/libspdm/issues/1136.
=> ResponderVerifyData / RequesterVerifyData should use hash of transcript

os_stub/openssllib/rand_pool.c
Fix: https://github.com/DMTF/libspdm/issues/195
copy_mem is used here to align solution between mbedtls and openssl.
we may change to other solution later and together.
=> Fix potential unaligned access for rand.

include/library/spdm_common_lib.h, library/spdm_common_lib/libspdm_com_support.c, library/spdm_requester_lib/libspdm_req_encap_challenge_auth.c, library/spdm_responder_lib/libspdm_rsp_challenge_auth.c
Fix: https://github.com/DMTF/libspdm/issues/1160
Add libspdm_{read|write}_uint{16|32|64}
It can be used for unaligned access or big endian later.
=> Fix potential unaligned access in challenge_auth.

.gitmodules, os_stub/cryptlib_openssl3/pem/pem.c, os_stub/cryptlib_openssl3/pk/ec.c, os_stub/cryptlib_openssl3/pk/x509.c
REF: https://github.com/DMTF/libspdm/issues/1094
Patch1:
Patch2:
Add 3.0.2 openssl as submodule
Patch3:
Replace EC_KEY* with EVP_PKEY*
=> Openssl 3 work: Replace EC_KEY* with EVP_PKEY*

library/spdm_responder_lib/libspdm_rsp_algorithms.c, unit_test/test_spdm_responder/algorithms.c, unit_test/test_spdm_responder/chunk_send_ack.c
The base hash algorithm selected is incorrectly mandated to be non-zero, given the case that the responder only supports unsigned measurements. The base asymmetric algorithm selected should also check for this case, however only the challenge capability is checked.
Fix by checking for capabilities which require these algorithms:
- CERT_CAP, CHAL_CAP, MEAS_CAP_SIG, KEY_EX_CAP, PSK_CAP, PUB_KEY_ID_CAP
This fixes issue #1189
=> Fix Condition for Base Hash and Base Asym Algorithm Selection

unit_test/fuzzing/test_requester/test_spdm_requester_key_exchange/key_exchange.c, unit_test/fuzzing/test_requester/test_spdm_requester_psk_exchange/psk_exchange.c, unit_test/fuzzing/test_responder/test_spdm_responder_finish_rsp/finish_rsp.c, unit_test/fuzzing/test_responder/test_spdm_responder_heartbeat_ack/heartbeat_ack.c, unit_test/fuzzing/test_responder/test_spdm_responder_key_update/key_update.c, unit_test/fuzzing/test_responder/test_spdm_responder_psk_finish_rsp/psk_finish_rsp.c
Fix: #1215 
Improve the reduced coverage to more than 75%.
libspdm_req_finish.c : 79.2 %
libspdm_req_key_exchange.c :80. 9%
libspdm_req_psk_exchange.c : 79.6 %
libspdm_req_psk_finish.c : 83.2 %
libspdm_rsp_finish.c : 83.3 %
libspdm_rsp_psk_finish.c : 80.4 %
=> Fix and add fuzzy test cases to improve code coverage

library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c
Commit 1310cd74d7cf400aa39b3951f28f9c534908334f fixed these expectations for the Responder, however, this was not fixed for the requester.
Fix by aligning capability checks with the responder implementation:
- Check CERT_CAP, CHAL_CAP, MEAS_CAP_SIG, KEY_EX_CAP, PSK_CAP for Base Hash
- Check CERT_CAP, CHAL_CAP, MEAS_CAP_SIG, KEY_EX_CAP for Base Asym
Signed-off-by: Matthew Thomas <matthew.thomas@intel.com>
=> Fix Requester Base Hash and Asym Algo Negotiation Expectation

include/hal/library/cryptlib/cryptlib_cert.h, include/library/spdm_crypt_lib.h, os_stub/cryptlib_mbedtls/pk/x509.c, os_stub/cryptlib_null/pk/x509.c, os_stub/cryptlib_openssl/pk/x509.c
This fixes some minor compilation warnings.
=> Fix minor compilation warnings

VERSION.md
Fixes #1060.
Note that updating this document will be the last commit before creating a release tag. When that occurs `pending and unreleased` becomes `released`.
=> Add VERSION.md

os_stub/cryptlib_mbedtls/pem/pem.c, os_stub/cryptlib_mbedtls/pk/rsa_basic.c, os_stub/cryptlib_mbedtls/pk/rsa_ext.c, os_stub/cryptlib_mbedtls/pk/x509.c, os_stub/cryptlib_null/pem/pem.c, os_stub/cryptlib_null/pk/rsa_basic.c, os_stub/cryptlib_null/pk/rsa_ext.c, os_stub/cryptlib_null/pk/x509.c, os_stub/cryptlib_openssl/pem/pem.c, os_stub/cryptlib_openssl/pk/rsa_basic.c, os_stub/cryptlib_openssl/pk/rsa_ext.c, os_stub/cryptlib_openssl/pk/x509.c
With both LIBSPDM_RSA_SSA_SUPPORT and LIBSPDM_RSA_PSS_SUPPORT switched off, any file which references the cryptlib_rsa.h header file will have an undefined reference.
Fix by switching out all functions which depend on RSA support
=> Fix Building with no RSA Support

library/spdm_requester_lib/libspdm_req_send_receive.c
Fix: https://github.com/DMTF/libspdm/issues/1237
When req trans size is 4096 and rsp trans size is 42, req fails.
The root cause is that send_info->large_message_size is override by response in chunk_send_ack. It is invalid to use send_info->chunk_bytes_transferred to check.
=> Fix the chunk issue.

os_stub/cryptlib_openssl/sys_call/crt_wrapper_host.c, os_stub/openssllib/include/crt_support.h, os_stub/openssllib/include/errno.h
Fix: #1193 
And the spdm-emu test  for win/linux openssl build has passed too.
=> Fix errno issue

include/internal/libspdm_secured_message_lib.h, include/library/spdm_secured_message_lib.h, library/spdm_secured_message_lib/libspdm_secmes_context_data.c, library/spdm_secured_message_lib/libspdm_secmes_session.c
And allow integrator to erase it from the context. It looks like `spdm_secured_message_lib` needs its own unit testing framework to test this. I'll file a separate issue for that.
Fixes #1259.
=> Don't erase export master secret

include/internal/libspdm_common_lib.h, include/library/spdm_common_lib.h
The functions that have been moved should not be visible to the integrator.
Fixes #1292.
=> Move functions from public common_lib to internal

unit_test/test_spdm_responder/version.c
Reset the connection state if the GET_VERSION request is valid. 
Not reset the connection state if the GET_VERSION request is invalid.
=> Update the unit tests of spdm_responder_version.

include/internal/libspdm_requester_lib.h, include/internal/libspdm_responder_lib.h, library/spdm_requester_lib/libspdm_req_finish.c, library/spdm_requester_lib/libspdm_req_key_exchange.c, library/spdm_responder_lib/libspdm_rsp_finish.c
That can save ~5K space for the device, to remove X.509 process.
Size before: (X64, VS2019, release, mbedtls, 
cap: disable CHAL_CAP/PSK_EX_CAP/GET_CSR_CAP/SET_CERTIFICATE_CAP/CHUNK_CAP/MUT_AUTH_CAP/ENCAP_CAP,
algo: only enable SHA384/ECDSA/ECDH/AES-GCM
```
10/30/2022  10:44 AM            94,208 test_size_of_spdm_requester.exe
10/30/2022  10:44 AM            65,536 test_size_of_spdm_responder.exe
```
After fix mut_auth
```
10/30/2022  11:23 AM            94,208 test_size_of_spdm_requester.exe
10/30/2022  11:23 AM            59,392 test_size_of_spdm_responder.exe
```
=> Add LIBSPDM_ENABLE_CAPABILITY_MUT_AUTH_CAP check for FINISH

include/hal/library/cryptlib.h, include/internal/libspdm_lib_config.h, include/library/spdm_common_lib.h, include/library/spdm_crypt_lib.h, include/library/spdm_device_secret_lib.h
Move the `LIBSPDM_CONFIG` logic to a common internal header. This has the benefit that if `LIBSPDM_CONFIG` is defined then it's always within #include guards.
=> Move the LIBSPDM_CONFIG logic

include/library/spdm_common_lib.h, include/library/spdm_return_status.h, library/spdm_common_lib/libspdm_com_context_data.c, library/spdm_requester_lib/libspdm_req_encap_request.c, library/spdm_responder_lib/libspdm_rsp_receive_send.c, unit_test/spdm_unit_test_common/common.c, unit_test/spdm_unit_test_common/spdm_unit_test.h, unit_test/test_spdm_requester/CMakeLists.txt, unit_test/test_spdm_requester/error_test/get_version_err.c, unit_test/test_spdm_requester/get_version.c, unit_test/test_spdm_requester/test_spdm_requester.c
This pull request adds the new `libspdm_force_error` and `libspdm_release_error` functions through which unit tests can manipulate errors to improve code coverage. It also begins to split the error / negative tests from the functional / positive tests.
=> Begin to add error injection to unit tests

library/spdm_responder_lib/libspdm_rsp_version.c, unit_test/test_spdm_responder/version.c
Fixes #1310.
Note that Test 7 was deleted as it is effectively a repeat of Test 6 and does not do what it says it does.
=> Change error code in response to GET_VERSION

.github/workflows/code_coverage.yml
Fixes #1296.
This will run code coverage every night or on-demand, and store the results in the `github_pages` branch. Once Github Pages is enabled the code coverage results will be easily accessible via http.
=> Enable code coverage generation in CI/CD

include/internal/libspdm_common_lib.h, library/spdm_requester_lib/libspdm_req_heartbeat.c, library/spdm_requester_lib/libspdm_req_key_exchange.c, library/spdm_requester_lib/libspdm_req_psk_exchange.c, library/spdm_responder_lib/libspdm_rsp_finish.c, library/spdm_responder_lib/libspdm_rsp_heartbeat.c, library/spdm_responder_lib/libspdm_rsp_key_exchange.c, library/spdm_responder_lib/libspdm_rsp_psk_exchange.c, unit_test/test_spdm_requester/heartbeat.c, unit_test/test_spdm_responder/heartbeat.c
Fixes #549.
Fixes #1333.
This also saves the `HeartbeatPeriod` value to the `session_info` rather than the SPDM context.
=> Make unwanted HEARTBEAT request an error

.github/workflows/code_coverage.yml
Currently the `make all` build fails when GCOV is on. This works around it by only building the targets that are needed for code coverage. When #1334 is fixed this can go back to `make all`.
=> Work around build failure when GCOV is on

library/spdm_requester_lib/libspdm_req_get_capabilities.c, unit_test/test_spdm_requester/CMakeLists.txt, unit_test/test_spdm_requester/error_test/get_capabilities_err.c, unit_test/test_spdm_requester/error_test/get_version_err.c, unit_test/test_spdm_requester/get_capabilities.c, unit_test/test_spdm_requester/test_spdm_requester.c
Increase `GET_VERSION` code coverage. Put `GET_CAPABILITIES` error tests in its own file. Expand and refactor capability flag checking. Will complete 100 % code coverage of `GET_CAPABILITIES` in a subsequent pull request.
Fixes https://github.com/DMTF/libspdm/issues/1343.
=> Code coverage 2

os_stub/mbedtlslib/include/mbedtls/config.h
This was added to enable ARM_DS2022 build, but in wrong way.
The entropy is not related to compiler, but related to platform.
=> Fix mbedtls entropy configuration.

.github/workflows/build.yml
This will allow developers to manually trigger the build and test process in their forked repositories.
=> Enable manual trigger for build

include/internal/libspdm_common_lib.h, library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c, unit_test/test_spdm_requester/CMakeLists.txt, unit_test/test_spdm_requester/error_test/negotiate_algorithms_err.c, unit_test/test_spdm_requester/negotiate_algorithms.c, unit_test/test_spdm_requester/test_spdm_requester.c
This pull request moves `NEGOTIATE_ALGORITHM` error testing to its own file, and expands test coverage. This pull request also adds a new function, `libspdm_onehot0`, that checks that bitmasks have at most one bit set.
=> NEGOTIATE_ALGORITHM Coverage

.github/workflows/codeql-analysis.yml
Or it can be manually triggered. This will remove the running of CodeQL with each pull request, which did not seem to have much value, and there was considerable overlap with certain GCC and CLANG warnings.
=> Run CodeQL daily

os_stub/cryptlib_mbedtls/internal_crypt_lib.h
Stdio.h is not required for compilation of the mbedtls hooks - the stdio.h might cause issues for build environments which don't have access to the headers.
Signed-off-by: Timothy Prinz <tandrewprinz@nvidia.com>
=> Removing extraneous <stdio.h> in crypto

library/spdm_requester_lib/libspdm_req_get_digests.c, unit_test/test_spdm_requester/CMakeLists.txt, unit_test/test_spdm_requester/error_test/get_digests_err.c, unit_test/test_spdm_requester/get_digests.c, unit_test/test_spdm_requester/test_spdm_requester.c
Move error tests to their own file. This brings line coverage up to 90.1 %.
=> Get digest coverage

CMakeLists.txt, unit_test/test_size/malloclib_simple/CMakeLists.txt, unit_test/test_size/malloclib_simple/malloclib.c
Fix: #1366 
Test for the patch:
1. Use `malloc_null` lib for `test_crypt` in unit_test to ensure all enable memory feature is right;
2. Use `malloc_null` lib for `spdm-emu` to ensure feature right again and test the malloc used size is 46KB;
=> Implement simple memory allocation

unit_test/fuzzing/test_requester/test_spdm_requester_heartbeat/heartbeat.c, unit_test/fuzzing/test_responder/test_spdm_responder_heartbeat_ack/heartbeat_ack.c
Fix : #1420 
The coverage after improvement is:
AFL Every fuzzing test case run about 30 minutes.
libspdm_rsp_heartbeat.c 94.9 %
libspdm_req_heartbeat.c 90.0 %
=> Improve fuzzy test coverage

library/spdm_requester_lib/libspdm_req_key_exchange.c, unit_test/test_spdm_requester/CMakeLists.txt, unit_test/test_spdm_requester/error_test/key_exchange_err.c, unit_test/test_spdm_requester/key_exchange.c, unit_test/test_spdm_requester/test_spdm_requester.c
And move error tests to its own file. There will be a follow-up pull request to expand the code coverage even more, and include error injection into the cryptography library.
=> Improve code coverage for KEY_EXCHANGE

doc/user_guide.md, include/library/spdm_common_lib.h, include/library/spdm_secured_message_lib.h, library/spdm_common_lib/libspdm_com_context_data.c, library/spdm_secured_message_lib/libspdm_secmes_context_data.c, unit_test/test_spdm_common/context_data.c
Implements #1311. The motivation behind this is that the secured message context(s) hold key and key-related material, which some integrators may want to store separately in sensitive data storage. A split is desired, since this storage is often limited - we would like to avoid having to support the entire libspdm_context_t struct which can be quite large.
To do this, introduces new APIs which allows the user to allocated SPDM context and secured message contexts separately. Decided to add new APIs, rather than update the existing ones, to avoid extensive breaking change both internally and externally.
Existing APIs are now wrappers around the new APIs.
Updated documentation to alert users of this API.
Adds test as well, just to double check this code does what it says it does. …
=> Allow user to specify the location of secured message context

library/spdm_common_lib/libspdm_com_crypto_service.c
=> Remove dead code when LIBSPDM_MAX_ROOT_CERT_SUPPORT is 1

include/industry_standard/spdm.h, library/spdm_secured_message_lib/libspdm_secmes_session.c
and add SPDM_VERSION_1_2_BIN_CONCAT_LABEL.
Fixes #1379.
=> Make BIN_CONCAT_LABEL generic

.github/workflows/build.yml, unit_test/test_spdm_requester/get_measurements.c
and re-enable CLANG in CI/CD. The `temp_buf` array was being modified at an out-of-bounds index. GCC and Visual Studio didn't mind but CLANG 14, with -O1 or higher optimizations, did. 
Note that Valgrind is picking up additional issues in `test_spdm_requester`. I'll file a separate issue for those.
Fixes #1467.
=> Fix undefined behavior in GET_MEASUREMENTS unit test

library/spdm_requester_lib/libspdm_req_send_receive.c, library/spdm_responder_lib/libspdm_rsp_receive_send.c
Fixes #1489.
Although `temp_session_context` must necessarily be set when `reset_key_update` is true, the compiler does not catch this dependency, and we therefore get potentially uninitialized warnings in the code scanner.
Fixing this by ensuring `temp_session_context` is at least set to NULL - we check for this after `reset_key_update` to ensure we do not dereference a NULL pointer.
Signed-off-by: Timothy Prinz <tandrewprinz@nvidia.com>
=> Fixing potentially uninitialized warning in KEY_UPDATE callbacks.

library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c, library/spdm_responder_lib/libspdm_rsp_algorithms.c, unit_test/test_spdm_requester/error_test/negotiate_algorithms_err.c, unit_test/test_spdm_responder/algorithms.c, unit_test/test_spdm_responder/chunk_send_ack.c
Fix the issue: #928
add a conditional to check if the AlgType monotonically incerease for subsequent entries or not.
Signed-off-by: Sungho Yoon <sungho.yoon@samsung.com>
=> Add AlgType checker

include/library/spdm_lib_config.h, library/spdm_requester_lib/libspdm_req_get_measurements.c, library/spdm_responder_lib/libspdm_rsp_measurements.c, os_stub/spdm_device_secret_lib_sample/lib.c
Fix: https://github.com/DMTF/libspdm/issues/1491
Since SPDM supports RAW data based measurement, having such MAX_BLOCK_COUNT is useless for size constrain.
=> remove LIBSPDM_MAX_MEASUREMENT_BLOCK_COUNT.

include/hal/library/cryptlib/cryptlib_dh.h, include/hal/library/cryptlib/cryptlib_ec.h, include/hal/library/cryptlib/cryptlib_ecd.h, include/hal/library/cryptlib/cryptlib_sm2.h, os_stub/spdm_crypt_ext_lib/cryptlib_ext.h, os_stub/spdm_device_secret_lib_sample/spdm_device_secret_lib_internal.h, unit_test/test_crypt/ec_verify.c, unit_test/test_crypt/sm2_verify.c, unit_test/test_crypt/test_crypt.c
and move unused functions to `os_stub`.
Fixes #1535.
=> Add macro checks to cryptlib

library/spdm_common_lib/libspdm_com_context_data.c
=> Add 1.1 as secured_message_version by default.

library/spdm_crypt_lib/libspdm_crypt_aead.c, library/spdm_crypt_lib/libspdm_crypt_hash.c, library/spdm_crypt_lib/libspdm_crypt_hkdf.c, library/spdm_crypt_lib/libspdm_crypt_hmac.c, unit_test/test_crypt/rsa_verify.c
Function pointers for asymmetric cryptography functions will be removed in a subsequent pull request.
=> Remove function pointers from symmetric cryptography functions in spdm_crypt_lib

include/hal/library/platform_lib.h, library/spdm_requester_lib/libspdm_req_handle_error_response.c, os_stub/platform_lib/time_linux.c, os_stub/platform_lib/time_sample.c, os_stub/platform_lib/time_win.c, os_stub/platform_lib_null/time_linux.c, os_stub/platform_lib_null/time_win.c
Deprecate libspdm_sleep which sleeps milliseconds.
Fix: https://github.com/DMTF/libspdm/issues/1555
=> define libspdm_sleep_in_us to sleep microseconds.

os_stub/cryptlib_mbedtls/pk/x509.c
`mbedtls_x509write_csr_der` return type is `int` not `size_t`.
=> Make the mbedtls gen csr return right

include/internal/libspdm_common_lib.h, library/spdm_requester_lib/libspdm_req_encap_request.c, library/spdm_responder_lib/libspdm_rsp_receive_send.c
Fixes #1411.
These function pointers are declared as `void *` in the internal header, rather than declared as the function pointer typedef, because the function pointers are used by a Requester ^ Responder and we don't want to include the Requester / Responder's public headers.
=> Change function pointer type from size_t to void *

library/spdm_crypt_lib/libspdm_crypt_cert.c
Fixes #1592
extended_key_usage was required in spec 1.1 but has been fixed in 1.1.1. It appears more like an 'errta' fix. This commit removes such checking to be compatible with all the different versions.
=> Remove the checking of extended_key_usage

doc/programming_environment.md
Note that assumptions about endianness and alignment have been omitted. If libspdm can support arbitrary endianness and alignment then we can leave that out of this document, else we'll have to document it. Also, I'll be adding more to this document. When I am done we can close the issue.
=> Initial draft for programming environment document

VERSION.md, library/spdm_responder_lib/libspdm_rsp_capabilities.c, unit_test/test_spdm_responder/capabilities.c
Increment patch number and delete a unit test that used a "random" capabilities flags. The test needs to be replaced with individual and targeted tests.
=> Fix bug when checking Requester's capabilities

library/spdm_requester_lib/libspdm_req_key_exchange.c
=> libspdm_try_send_receive_key_exchange function should call libspdm_release_receiver_buffer function before return error

library/spdm_requester_lib/libspdm_req_get_measurements.c
Fix: #1621
Correct slot_id check in libspdm_verify_measurement_signature()
to prevent asym context memory leaking.
=> Correct slot_id check

library/spdm_crypt_lib/libspdm_crypt_aead.c
Fix: #1626
AES-128-GCM and AES-256-GCM have same encode/decode process routine
thus remove the duplicated code.
=> Remove duplicated code from AEAD process

include/library/spdm_common_lib.h, include/library/spdm_lib_config.h, library/spdm_common_lib/libspdm_com_context_data.c, unit_test/test_spdm_requester/challenge.c, unit_test/test_spdm_requester/end_session.c, unit_test/test_spdm_requester/finish.c, unit_test/test_spdm_requester/get_capabilities.c, unit_test/test_spdm_requester/get_certificate.c, unit_test/test_spdm_requester/get_measurements.c, unit_test/test_spdm_requester/get_version.c, unit_test/test_spdm_requester/heartbeat.c, unit_test/test_spdm_requester/key_exchange.c, unit_test/test_spdm_requester/key_update.c, unit_test/test_spdm_requester/negotiate_algorithms.c, unit_test/test_spdm_requester/psk_exchange.c, unit_test/test_spdm_requester/psk_finish.c
Fix: #1588
Remove the macro `LIBSPDM_MAX_REQUEST_RETRY_TIMES` and expose it via `libspdm_set_data()`.
Default value is 0 (no retry).
=> Change request retry times to a runtime parameter

doc/user_guide.md, include/library/spdm_requester_lib.h, library/spdm_requester_lib/libspdm_req_get_certificate.c, library/spdm_requester_lib/libspdm_req_get_digests.c, unit_test/fuzzing/test_requester/test_spdm_requester_get_certificate/get_certificate.c, unit_test/fuzzing/test_requester/test_spdm_requester_get_digests/get_digests.c, unit_test/test_size/test_size_of_spdm_requester/spdm_requester_authentication.c, unit_test/test_spdm_requester/chunk_get.c, unit_test/test_spdm_requester/error_test/get_digests_err.c, unit_test/test_spdm_requester/get_certificate.c, unit_test/test_spdm_requester/get_digests.c
Fix: #1580
Remove all `*_in_session()` functions
and add `session_id` parameter to the appropriate functions.
=> Remove *_in_session() public functions

include/library/spdm_common_lib.h, library/spdm_common_lib/libspdm_com_support.c
=> Add fips_module_id api

library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c, library/spdm_secured_message_lib/libspdm_secmes_session.c, unit_test/fuzzing/test_requester/test_spdm_requester_encap_request/encap_request.c, unit_test/fuzzing/test_requester/test_spdm_requester_end_session/end_session.c, unit_test/fuzzing/test_requester/test_spdm_requester_get_csr/get_csr.c, unit_test/fuzzing/test_requester/test_spdm_requester_get_digests/get_digests.c, unit_test/fuzzing/test_requester/test_spdm_requester_get_measurements/get_measurements.c, unit_test/fuzzing/test_requester/test_spdm_requester_heartbeat/heartbeat.c, unit_test/fuzzing/test_requester/test_spdm_requester_key_update/key_update.c, unit_test/fuzzing/test_requester/test_spdm_requester_psk_finish/psk_finish.c, unit_test/fuzzing/test_requester/test_spdm_requester_set_certificate/set_certificate.c, unit_test/test_spdm_requester/end_session.c, unit_test/test_spdm_requester/get_certificate.c, unit_test/test_spdm_requester/heartbeat.c, unit_test/test_spdm_requester/key_update.c, unit_test/test_spdm_requester/psk_finish.c, unit_test/test_spdm_requester/set_certificate.c
**2023/1/7**  Commit 1: Zero key for FIPS when encode and decode.
**2023/1/13**  Commit 2: Fix unit test because of the salt change.
**2023/1/9**   Commit 3: Zero salt1 in `libspdm_generate_session_data_key`.
=> Zero key for FIPS

doc/user_guide.md, include/library/spdm_requester_lib.h, library/spdm_requester_lib/libspdm_req_challenge.c, unit_test/fuzzing/test_requester/test_spdm_requester_challenge/challenge.c, unit_test/test_size/test_size_of_spdm_requester/spdm_requester_authentication.c, unit_test/test_spdm_requester/challenge.c, unit_test/test_spdm_requester/chunk_get.c, unit_test/test_spdm_requester/get_certificate.c
Fix: #1642
add `void *reserved` parameter for session_id to libspdm_challenge function.
=> Add reserved parameter to libspdm_challenge function

include/library/spdm_requester_lib.h, library/spdm_requester_lib/libspdm_req_get_csr.c, library/spdm_requester_lib/libspdm_req_set_certificate.c, unit_test/fuzzing/test_requester/test_spdm_requester_get_csr/get_csr.c, unit_test/fuzzing/test_requester/test_spdm_requester_set_certificate/set_certificate.c, unit_test/test_spdm_requester/get_csr.c, unit_test/test_spdm_requester/set_certificate.c
Fix: #1640
Move `session_id` to the 2nd parameter of
`libspdm_get_csr()` and `libspdm_set_certificate()` to make it consistent with other APIs.
=> Change parameter order

library/spdm_requester_lib/libspdm_req_end_session.c, library/spdm_requester_lib/libspdm_req_finish.c, library/spdm_requester_lib/libspdm_req_get_certificate.c, library/spdm_requester_lib/libspdm_req_get_digests.c, library/spdm_requester_lib/libspdm_req_heartbeat.c, library/spdm_requester_lib/libspdm_req_key_exchange.c, library/spdm_requester_lib/libspdm_req_key_update.c, library/spdm_requester_lib/libspdm_req_psk_exchange.c, library/spdm_requester_lib/libspdm_req_psk_finish.c, library/spdm_requester_lib/libspdm_req_set_certificate.c
Does not include the encapsulated messages. Those will be included in a follow-up commit.
=> Add message logging to more messages

library/spdm_common_lib/libspdm_com_context_data.c
=> free all allocated memory tied to the spdm_context.

os_stub/mbedtlslib/CMakeLists.txt
Resolves #1670
Signed-off-by: Ray Wang <ray.wang1@broadcom.com>
=> set LIB_INSTALL_DIR to build mbedtls with cmake

library/spdm_common_lib/libspdm_com_context_data.c, library/spdm_requester_lib/libspdm_req_challenge.c, library/spdm_requester_lib/libspdm_req_get_measurements.c, library/spdm_requester_lib/libspdm_req_key_exchange.c, library/spdm_responder_lib/libspdm_rsp_key_exchange.c, library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c, library/spdm_transport_mctp_lib/libspdm_mctp_mctp.c, library/spdm_transport_pcidoe_lib/libspdm_doe_pcidoe.c
Direct usage of '*(uint32_t *)' or '*(uint16_t *)' could cause potential alignment issue, or byte-ordering issue if the data buffer is transmitted from another host with different endiness. This commit converts them into libspdm_read_uintxx()/libspdm_write_uintxx().
Code in os_stub and unit_test are not covered in this commit for now.
Resolves #1669
=> Fix potential alignment and byte-order issue

include/internal/libspdm_fips_lib.h, library/spdm_crypt_lib/CMakeLists.txt, library/spdm_crypt_lib/fips/libspdm_get_selftest_result.c, library/spdm_crypt_lib/fips/libspdm_selftest_sha3.c
For openssl, sha3 self_test is passed.
For mbedtls, sha3 self_test just return ture: because mbedtsl doesn't support sha3 in libspdm now.
=> Add sha3 self_test

unit_test/test_spdm_requester/error_test/negotiate_algorithms_err.c, unit_test/test_spdm_requester/get_certificate.c, unit_test/test_spdm_responder/algorithms.c, unit_test/test_spdm_responder/certificate.c
Fix: #1673
The patch is tested to be working with all libspdm supported base asymmetric algorithms:
SPDM_ALGORITHMS_BASE_ASYM_ALGO_TPM_ALG_RSASSA_2048
SPDM_ALGORITHMS_BASE_ASYM_ALGO_TPM_ALG_RSAPSS_2048
SPDM_ALGORITHMS_BASE_ASYM_ALGO_TPM_ALG_RSASSA_3072
SPDM_ALGORITHMS_BASE_ASYM_ALGO_TPM_ALG_RSAPSS_3072
SPDM_ALGORITHMS_BASE_ASYM_ALGO_TPM_ALG_ECDSA_ECC_NIST_P256
SPDM_ALGORITHMS_BASE_ASYM_ALGO_TPM_ALG_RSASSA_4096
SPDM_ALGORITHMS_BASE_ASYM_ALGO_TPM_ALG_RSAPSS_4096
SPDM_ALGORITHMS_BASE_ASYM_ALGO_TPM_ALG_ECDSA_ECC_NIST_P384
SPDM_ALGORITHMS_BASE_ASYM_ALGO_TPM_ALG_ECDSA_ECC_NIST_P521
=> Make unit test code work for all asymmetric algorithms

os_stub/openssllib/CMakeLists.txt, os_stub/spdm_device_secret_lib_sample/CMakeLists.txt
=> Add LIBSPDM_CPU_ARM to fix armclang build error

include/internal/libspdm_common_lib.h, include/internal/libspdm_requester_lib.h, include/library/spdm_common_lib.h, library/spdm_common_lib/libspdm_com_context_data.c, library/spdm_requester_lib/libspdm_req_challenge.c, library/spdm_requester_lib/libspdm_req_end_session.c, library/spdm_requester_lib/libspdm_req_finish.c, library/spdm_requester_lib/libspdm_req_get_capabilities.c, library/spdm_requester_lib/libspdm_req_get_certificate.c, library/spdm_requester_lib/libspdm_req_get_csr.c, library/spdm_requester_lib/libspdm_req_get_digests.c, library/spdm_requester_lib/libspdm_req_get_measurements.c, library/spdm_requester_lib/libspdm_req_get_version.c, library/spdm_requester_lib/libspdm_req_heartbeat.c, library/spdm_requester_lib/libspdm_req_key_exchange.c, library/spdm_requester_lib/libspdm_req_key_update.c, library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c, library/spdm_requester_lib/libspdm_req_psk_exchange.c, library/spdm_requester_lib/libspdm_req_psk_finish.c, library/spdm_requester_lib/libspdm_req_set_certificate.c, os_stub/platform_lib/time_win.c
Fix: #717
This patch adds integrator configurable
delay time in microseconds between retry requests.
=> Add delay time between retry requests

doc/programming_environment.md
Fixes #115.
Note that if libspdm ever support big-endian architectures then we can remove the first bullet point.
=> Document target architecture

library/spdm_requester_lib/libspdm_req_challenge.c, library/spdm_requester_lib/libspdm_req_end_session.c, library/spdm_requester_lib/libspdm_req_finish.c, library/spdm_requester_lib/libspdm_req_get_capabilities.c, library/spdm_requester_lib/libspdm_req_get_certificate.c, library/spdm_requester_lib/libspdm_req_get_csr.c, library/spdm_requester_lib/libspdm_req_get_digests.c, library/spdm_requester_lib/libspdm_req_get_measurements.c, library/spdm_requester_lib/libspdm_req_get_version.c, library/spdm_requester_lib/libspdm_req_heartbeat.c, library/spdm_requester_lib/libspdm_req_key_exchange.c, library/spdm_requester_lib/libspdm_req_key_update.c, library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c, library/spdm_requester_lib/libspdm_req_psk_exchange.c, library/spdm_requester_lib/libspdm_req_psk_finish.c, library/spdm_requester_lib/libspdm_req_set_certificate.c
Fix: #1746
When there is no more retry (`retry` value is 0),
no sleep should be introduced.
=> Prevent extra sleep in busy-retry process

include/internal/libspdm_common_lib.h, include/library/spdm_return_status.h, library/spdm_common_lib/libspdm_com_crypto_service.c, library/spdm_requester_lib/libspdm_req_get_certificate.c, library/spdm_responder_lib/libspdm_rsp_encap_get_certificate.c, unit_test/test_spdm_common/context_data.c, unit_test/test_spdm_requester/get_certificate.c
Fix: #1718
Commit 1： Add new status to distinguish verify cert chain status.
- When verify cert chain integrity failed, the status is VERIF_FAIL.
- When verify cert chain authority failed, the status is NO_AUTHORITY.
Commit 2： Fix the unit_test for adding new verify status
=> Add new cert verify status

include/hal/library/platform_lib.h, library/spdm_requester_lib/libspdm_req_challenge.c, library/spdm_requester_lib/libspdm_req_end_session.c, library/spdm_requester_lib/libspdm_req_finish.c, library/spdm_requester_lib/libspdm_req_get_capabilities.c, library/spdm_requester_lib/libspdm_req_get_certificate.c, library/spdm_requester_lib/libspdm_req_get_csr.c, library/spdm_requester_lib/libspdm_req_get_digests.c, library/spdm_requester_lib/libspdm_req_get_measurements.c, library/spdm_requester_lib/libspdm_req_get_version.c, library/spdm_requester_lib/libspdm_req_handle_error_response.c, library/spdm_requester_lib/libspdm_req_heartbeat.c, library/spdm_requester_lib/libspdm_req_key_exchange.c, library/spdm_requester_lib/libspdm_req_key_update.c, library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c, library/spdm_requester_lib/libspdm_req_psk_exchange.c, library/spdm_requester_lib/libspdm_req_psk_finish.c, library/spdm_requester_lib/libspdm_req_set_certificate.c, os_stub/platform_lib/time_linux.c, os_stub/platform_lib/time_sample.c, os_stub/platform_lib/time_win.c, os_stub/platform_lib_null/time_linux.c, os_stub/platform_lib_null/time_win.c
Fix: #1723
Replace old `libspdm_sleep()`, which is deprecated
and has no implementation, with `libspdm_sleep_in_us()`.
=> Rename libspdm_sleep_in_us to libspdm_sleep

include/hal/library/cryptlib/cryptlib_ec.h
Fix: #1758
`ec_get_public_key_from_der` was introduced to handle
authentication (signature generation and verification)
using provisioned public key, thus it should be
surrounded by `LIBSPDM_ECDSA_SUPPORT` macro.
=> Move ec_get_public_key_from_der into appropriate config

os_stub/cryptlib_mbedtls/rand/rand.c
=> Adjust the dst_size in libspdm_random_bytes().

include/internal/libspdm_common_lib.h, library/spdm_common_lib/libspdm_com_support.c, library/spdm_requester_lib/libspdm_req_send_receive.c, library/spdm_responder_lib/libspdm_rsp_receive_send.c
This patch extend the request (and response) msg with command name.
check reference below using spdm-emu
Before:
SpdmReceiveRequest[.] ...
SpdmReceiveRequest[0] (0x14):
0000: 12 e1 00 00 00 00 00 00 c6 f7 02 00 00 12 00 00 00 12 00 00
SpdmSendResponse[0] ...
SpdmSendResponse[0] (0x14):
0000: 12 61 00 00 00 00 00 00 f7 fb 1a 00 00 12 00 00 00 12 00 00
After:
SpdmReceiveRequest[.] ...
SpdmReceiveRequest[0] **msg SPDM_GET_CAPABILITIES(0xe1)**, size (0x14):
0000: 12 e1 00 00 00 00 00 00 c6 f7 02 00 00 12 00 00 00 12 00 00
SpdmSendResponse[0] ...
SpdmSendResponse[0]: **msg SPDM_CAPABILITIES(0x61)**, size (0x14):
0000: 12 61 00 00 00 00 00 00 f7 fb 1a 00 00 12 00 00 00 12 00 00
=> spdm_responder_lib: add code name to response dump

library/spdm_transport_mctp_lib/libspdm_mctp_mctp.c
This reverts commit 03c9cb91495fc05d8353ee9413cdee775372f832.
REF: #1818
=> Revert "Check transport length in libspdm_mctp_encode_message()"

include/internal/libspdm_secured_message_lib.h, include/library/spdm_responder_lib.h, include/library/spdm_secured_message_lib.h, library/spdm_common_lib/libspdm_com_context_data_session.c, library/spdm_common_lib/libspdm_com_crypto_service_session.c, library/spdm_requester_lib/libspdm_req_encap_key_update.c, library/spdm_requester_lib/libspdm_req_end_session.c, library/spdm_requester_lib/libspdm_req_finish.c, library/spdm_requester_lib/libspdm_req_key_exchange.c, library/spdm_requester_lib/libspdm_req_key_update.c, library/spdm_requester_lib/libspdm_req_psk_exchange.c, library/spdm_requester_lib/libspdm_req_psk_finish.c, library/spdm_requester_lib/libspdm_req_send_receive.c, library/spdm_responder_lib/libspdm_rsp_encap_key_update.c, library/spdm_responder_lib/libspdm_rsp_finish.c, library/spdm_responder_lib/libspdm_rsp_key_exchange.c, library/spdm_responder_lib/libspdm_rsp_key_update.c, library/spdm_responder_lib/libspdm_rsp_psk_exchange.c, library/spdm_responder_lib/libspdm_rsp_psk_finish.c, library/spdm_responder_lib/libspdm_rsp_receive_send.c, unit_test/spdm_unit_test_common/spdm_unit_test.h
Move appropriate secured message functions from the public header to the internal header.
=> Move secured message functions

library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
The maximum length of the PSK hint is referenced by the LIBSPDM_PSK_MAX_HINT_LENGTH macro (16). We need to ensure that the length is less then equal to the length of LIBSPDM_PSK_MAX_HINT_LENGTH, not less then.
This patch ensures that the psk hint is less then or equal to LIBSPDM_PSK_MAX_HINT_LENGTH which also matches the check when setting the psk_hint buffer for the local context.
=> libspdm_rsp_psk_exchange: Fixup PSK Hint Length comparison

include/hal/library/cryptlib/cryptlib_cert.h, include/library/spdm_crypt_lib.h, include/library/spdm_lib_config.h, library/spdm_common_lib/libspdm_com_context_data.c, library/spdm_common_lib/libspdm_com_crypto_service.c, library/spdm_crypt_lib/libspdm_crypt_cert.c, os_stub/cryptlib_mbedtls/pk/x509.c, os_stub/cryptlib_openssl/pk/x509.c
Fix https://github.com/DMTF/libspdm/issues/1761
=> Add LIBSPDM_CERT_PARSE_SUPPORT for device image size reduction.

library/spdm_transport_mctp_lib/libspdm_mctp_common.c, library/spdm_transport_mctp_lib/libspdm_mctp_mctp.c
Fix: #796
Fix: #1824
Ref: #1715, #1818, #1823
Ref: DMTF/spdm-emu#225
Fix `app_message` not initialized issue
and add transport buffer size check in `libspdm_mctp_encode_message()`.
=> Check MCTP transport buffer size

include/library/spdm_return_status.h, library/spdm_requester_lib/libspdm_req_handle_error_response.c, unit_test/test_spdm_requester/get_csr.c, unit_test/test_spdm_requester/set_certificate.c
If a device provides a ResetRequired error message we want to report that up the stack so that applications can reset the device. This patch exposes that reset error information to users.
=> library: spdm_requester: Pass along reset required error messages

unit_test/test_spdm_common/context_data.c
=> Change assertion from `int` to `ptr`

unit_test/fuzzing/test_requester/test_spdm_requester_challenge/challenge.c, unit_test/fuzzing/test_requester/test_spdm_requester_chunk_get/chunk_get.c, unit_test/fuzzing/test_requester/test_spdm_requester_chunk_send/chunk_send.c, unit_test/fuzzing/test_requester/test_spdm_requester_finish/finish.c, unit_test/fuzzing/test_requester/test_spdm_requester_get_capabilities/get_capabilities.c, unit_test/fuzzing/test_requester/test_spdm_requester_get_certificate/get_certificate.c, unit_test/fuzzing/test_requester/test_spdm_requester_get_csr/get_csr.c, unit_test/fuzzing/test_requester/test_spdm_requester_get_digests/get_digests.c, unit_test/fuzzing/test_requester/test_spdm_requester_get_measurements/get_measurements.c, unit_test/fuzzing/test_requester/test_spdm_requester_get_version/get_version.c, unit_test/fuzzing/test_requester/test_spdm_requester_key_exchange/key_exchange.c, unit_test/fuzzing/test_requester/test_spdm_requester_negotiate_algorithms/negotiate_algorithms.c, unit_test/fuzzing/test_requester/test_spdm_requester_psk_exchange/psk_exchange.c, unit_test/fuzzing/test_requester/test_spdm_requester_set_certificate/set_certificate.c
Otherwise, the response buffer will be overridden by other program.
Fix: https://github.com/DMTF/libspdm/issues/1925
=> fix test to not put response buffer in local stack.

include/internal/libspdm_common_lib.h, include/internal/libspdm_macro_check.h, include/library/spdm_common_lib.h, include/library/spdm_lib_config.h, library/spdm_common_lib/libspdm_com_context_data.c, library/spdm_requester_lib/libspdm_req_encap_request.c, library/spdm_requester_lib/libspdm_req_handle_error_response.c, library/spdm_requester_lib/libspdm_req_send_receive.c, library/spdm_responder_lib/libspdm_rsp_chunk_send_ack.c, library/spdm_responder_lib/libspdm_rsp_handle_response_state.c, library/spdm_responder_lib/libspdm_rsp_receive_send.c, unit_test/fuzzing/spdm_unit_fuzzing_common/common.c, unit_test/fuzzing/spdm_unit_fuzzing_common/spdm_unit_fuzzing.h, unit_test/fuzzing/test_responder/test_spdm_responder_chunk_get/chunk_get.c, unit_test/fuzzing/test_responder/test_spdm_responder_if_ready/respond_if_ready.c, unit_test/spdm_unit_test_common/common.c, unit_test/spdm_unit_test_common/spdm_unit_test.h, unit_test/test_size/test_size_of_spdm_requester/spdm_requester_init.c, unit_test/test_size/test_size_of_spdm_responder/spdm_responder_init.c, unit_test/test_spdm_responder/chunk_get.c, unit_test/test_spdm_responder/receive_send.c, unit_test/test_spdm_responder/respond_if_ready.c
Fix https://github.com/DMTF/libspdm/issues/1909
The main idea is as follows. The integrator input `max_spdm_msg_size` and `libspdm_get_sizeof_required_scratch_buffer`.
```
size_t libspdm_get_sizeof_required_scratch_buffer (
void *spdm_context, uint32_t max_spdm_msg_size)
{
libspdm_context_t *context;
size_t scratch_buffer_size;
context = spdm_context;
context->local_context.capability.max_spdm_msg_size = max_spdm_msg_size;
scratch_buffer_size = libspdm_get_scratch_buffer_capacity(context);
return scratch_buffer_size;
}
```
Or the integrator can pre-calculate the size based upon `libspdm_get_scratch_buffer_capacity`, then set `LIBSPDM_DATA_CAPABILITY_MAX_SPDM_MSG_SIZE`.
=> Support runtime scratch buffer size based upon max_spdm_msg_size

library/spdm_crypt_lib/fips/libspdm_selftest_ecdsa.c, library/spdm_crypt_lib/fips/libspdm_selftest_hkdf.c
=> Remove libspdm_hkdf_sha256_extract_and_expand and extend crypto header from FIPS

doc/api/common_api.md, library/spdm_common_lib/libspdm_com_context_data.c
This also adds a warning print to `LIBSPDM_DATA_BASIC_MUT_AUTH_REQUESTED` if set, since basic mutual authentication has been deprecated.
=> Add additional API documentation

include/internal/libspdm_macro_check.h
=> Delete LIBSPDM_MAX_SPDM_MSG_SIZE in macro check

include/library/spdm_crypt_lib.h, library/spdm_crypt_lib/libspdm_crypt_cert.c
Fix parameter order for IDE tooltip in function description of libspdm_verify_cert_chain_data.
It could lead to pass wrong arguments in while users use some IDE which only shows function description from comments.
For example: Eclipse.
=> Fix paramter order for IDE tooltip

unit_test/fuzzing/test_requester/test_spdm_requester_encap_certificate/encap_certificate.c, unit_test/fuzzing/test_requester/test_spdm_requester_get_certificate/get_certificate.c, unit_test/fuzzing/test_requester/test_spdm_requester_key_exchange/key_exchange.c, unit_test/fuzzing/test_requester/test_spdm_requester_psk_exchange/psk_exchange.c, unit_test/fuzzing/test_responder/test_spdm_responder_if_ready/respond_if_ready.c, unit_test/fuzzing/test_responder/test_spdm_responder_key_exchange/key_exchange.c, unit_test/fuzzing/test_responder/test_spdm_responder_psk_exchange_rsp/psk_exchange_rsp.c, unit_test/fuzzing/test_responder/test_spdm_responder_psk_finish_rsp/psk_finish_rsp.c
Fix : #1994 
Increase object code coverage to 75%
libspdm_req_get_certificate.c	79.9 %
libspdm_req_key_exchange.c	78.9 %
libspdm_req_psk_exchange.c	76.2 %	
libspdm_rsp_key_exchange.c	83.0%
libspdm_rsp_psk_exchange.c	83.1 %
libspdm_rsp_psk_finish.c	82.1%
libspdm_rsp_respond_if_ready.c	84.6 %
=> Need enhance the fuzzing test cases to improve the target code coverage

library/spdm_responder_lib/libspdm_rsp_finish.c, library/spdm_responder_lib/libspdm_rsp_psk_finish.c
Reference: DMTF-2023-0001
Fix: https://github.com/DMTF/libspdm/issues/2005
=> Add handshake mode switch check in FINISH and PSK_FINISH.

library/spdm_requester_lib/libspdm_req_get_capabilities.c, library/spdm_responder_lib/libspdm_rsp_capabilities.c
Fix #1986.
Note that this code path is already covered in a unit test that sets `ENC_CAP=0` and `MAC_CAP=0`.
=> Enforce DSP0277 capabilities

library/spdm_responder_lib/libspdm_rsp_receive_send.c, unit_test/test_spdm_responder/receive_send.c
Fix: #1825
commit1:  Add check for `SPDM_ERROR_CODE_RESPONSE_TOO_LARGE`;
commit2:  Fix unit_test when add check for `SPDM_ERROR_CODE_RESPONSE_TOO_LARGE`;
commit3:  Add unit_test case;
=> Handle response too large and add unit_test

os_stub/cryptlib_openssl/CMakeLists.txt
Resolves: https://github.com/DMTF/libspdm/issues/2022
=> os_stub/cryptlib_openssl: Fixup typo

os_stub/debuglib/debuglib.c
=> Remove unneeded static cast

include/hal/library/responder_secretlib.h, library/spdm_responder_lib/libspdm_rsp_csr.c, os_stub/spdm_device_secret_lib_null/lib.c, os_stub/spdm_device_secret_lib_sample/lib.c, unit_test/test_spdm_responder/csr.c
Fix: #2051
**Commit1:**
Cache the last last SPDM CSR request data;
Add `request` and `request_size` as `libspdm_gen_csr` input;
**The old parameters `requester_info `and `opaque_data` are also saved as input. Because the `spdm_get_csr_request` structure 
should not be known in `os_stub`.  The `requester_info `and `opaque_data` are only got in `library`.**
**Commit2:**
clear last SPDM CSR request data in unit_test;
=> Check the whole last SPDM CSR request data

unit_test/test_spdm_responder/key_exchange.c
=> Correct the test case: libspdm_test_responder_key_exchange_case9.

os_stub/cryptlib_mbedtls/pk/x509.c
This commit fixes the checking of libspdm_consttime_is_mem_equal() in this function.
Fixes #2091.
=> Fix a typo in libspdm_x509_compare_date_time()

unit_test/test_spdm_responder/csr.c
The logic is wrong when use `libspdm_consttime_is_mem_equal`.
=> Fix logic error when use libspdm_consttime_is_mem_equal

include/hal/library/responder_secretlib.h, library/spdm_responder_lib/libspdm_rsp_csr.c, os_stub/cryptlib_mbedtls/pk/x509.c, os_stub/cryptlib_null/pk/x509.c, os_stub/cryptlib_openssl/pk/x509.c, os_stub/spdm_crypt_ext_lib/cryptlib_ext.h, os_stub/spdm_device_secret_lib_null/lib.c, os_stub/spdm_device_secret_lib_sample/lib.c, unit_test/test_spdm_responder/csr.c
Fix: #2056
Add `is_device_cert_model` to set different `basicConstraints`;
=> Add alias cert mode support

unit_test/test_spdm_responder/challenge_auth.c
=> Fix incorrect variable names for unit tests

library/spdm_responder_lib/libspdm_rsp_measurements.c
=> `return false;` in `libspdm_rsp_measurements.c` should be changed to `return libspdm_generate_error_response`

include/internal/libspdm_common_lib.h, include/internal/libspdm_secured_message_lib.h, include/library/spdm_common_lib.h, library/spdm_common_lib/libspdm_com_context_data.c, library/spdm_common_lib/libspdm_com_context_data_session.c, library/spdm_secured_message_lib/libspdm_secmes_context_data.c, library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c
Fix: https://github.com/DMTF/libspdm/issues/2101
Tested in spdm-emu. Setting to small number will cause emu stop communicating.
=> Add LIBSPDM_MAX_SPDM_SESSION_SEQUENCE_NUMBER

library/spdm_responder_lib/libspdm_rsp_encap_get_certificate.c
The `spdm_context` was not being updated after a certificate was received from the Requester, so that the Responder continually requested the first 0x400 or so bytes in an infinite loop.
=> Fix encapsulated GET_CERTIFICATE bug

library/spdm_responder_lib/libspdm_rsp_chunk_get.c, library/spdm_responder_lib/libspdm_rsp_chunk_send_ack.c, library/spdm_responder_lib/libspdm_rsp_receive_send.c, unit_test/fuzzing/test_responder/test_spdm_responder_chunk_get/chunk_get.c, unit_test/fuzzing/test_responder/test_spdm_responder_chunk_send_ack/chunk_send_ack.c, unit_test/test_spdm_responder/chunk_get.c, unit_test/test_spdm_responder/chunk_send_ack.c, unit_test/test_spdm_responder/receive_send.c
Currently the responder does not check requester's chunk cap.
This patch adds requester's chunk cap.
=> Fix the responder chunk checking

library/spdm_crypt_lib/libspdm_crypt_hash.c
wrong compile time configuration flag is used for SHA384 hash size due to a typo.
Fix #2164
=> fix typo in libspdm_get_hash_size

include/hal/library/responder_secretlib.h, library/spdm_responder_lib/libspdm_rsp_set_certificate.c, os_stub/spdm_device_secret_lib_null/lib.c, os_stub/spdm_device_secret_lib_sample/lib.c
If the implementor wants to update the certificate without rebooting the device they will need to know the base_hash_algo and base_asym_algo in order to verify and hash the new certificate. Let's pass that information to the libspdm_write_certificate_to_nvm() function so that it can use it.
=> library: Include base_*_algo to libspdm_write_certificate_to_nvm()

os_stub/spdm_device_secret_lib_sample/lib.c
Refer to the commit: https://github.com/DMTF/libspdm/commit/00885640d5dec19fcaa0051a3e6add56ccf363ee,
there is a check:
https://github.com/DMTF/libspdm/blob/9e4843cf29f164278ddaf4625097414c2c416783/os_stub/spdm_device_secret_lib_sample/lib.c#L1619-L1623
The data type need be changed.
=> Fix wrong data type

library/spdm_requester_lib/libspdm_req_get_version.c, unit_test/test_spdm_requester/error_test/get_version_err.c
Fix: #2187
If the Responder respond to the GET_VERSION request message with ErrorCode=ResponseNotReady, It is more accurate that the requester return LIBSPDM_STATUS_ERROR_PEER, received an unexpected error message.
due to A Responder shall not respond to the GET_VERSION request message with ErrorCode=ResponseNotReady.
=> Handle GET_VERSION request receive ResponseNotReady response.

CMakeLists.txt, library/spdm_common_lib/libspdm_com_context_data.c, library/spdm_responder_lib/libspdm_rsp_key_exchange.c, library/spdm_transport_mctp_lib/libspdm_mctp_mctp.c, library/spdm_transport_pcidoe_lib/libspdm_doe_pcidoe.c
Unaligned access is not supported on some ARCHs. It will trigger CPU load/store fault. This change fixes unaligned access reported by -Wcast-align
Fix https://github.com/DMTF/libspdm/issues/2188
=> library: fix unaligned type casts

doc/api/common_api.md, include/library/spdm_common_lib.h, library/spdm_common_lib/libspdm_com_context_data.c
=> Allow Integrator to query the AEAD sequence number

unit_test/fuzzing/test_requester/test_spdm_requester_key_exchange/key_exchange.c, unit_test/fuzzing/test_requester/test_spdm_requester_psk_exchange/psk_exchange.c, unit_test/fuzzing/test_spdm_common/test_process_opaque_data/test_process_opaque_data_supported_version_data.c, unit_test/test_spdm_common/context_data.c, unit_test/test_spdm_requester/error_test/key_exchange_err.c, unit_test/test_spdm_requester/key_exchange.c, unit_test/test_spdm_requester/psk_exchange.c
=> Correct the secured message version macros in unit tests.

doc/user_guide.md, os_stub/cryptlib_openssl/pk/x509.c, os_stub/openssllib/include/openssl/configuration.h
Some implementations might not have accurate clocks, so allow disabling time checks.
=> os_stub: Allow disabling time checks

library/spdm_requester_lib/libspdm_req_get_certificate.c, unit_test/test_spdm_requester/chunk_get.c
Fix: #2270
According to spec 1.3, get_cert requester should not assume that it always receives the entire Cert or sets 0xFFFF when enabling the chunk.
And the test pass the emu test.
=> Make get_cert sync the SPDM spec 1.3

os_stub/cryptlib_openssl/pk/ecd.c
The OpenSSL source code describes the crypto include as:
"Internal EC functions for other submodules: not for application use"
- https://github.com/openssl/openssl/blob/master/include/crypto/ec.h
Using the internal APIS makes it difficult to use libspdm as a library
with other packages. So let's remove the uses of the internal API and
instead use the public API.
The current ECD code uses internal APIs, making it unsuitable for use in
production code or libraries.
The supported way to do this is via OSSL params, either with
EVP_PKEY_fromdata() [1] or using EVP_PKEY_set_octet_string_param().
Unfortunately this isn't supported in OpenSSL and ed25519_set_params()
and ed448_set_params() will always return 1, indicating no support.
As there doesn't appear to be a supported method in OpenSSL to …
=> cryptlib_openssl: ecd: Remove internal OpenSSL crypto include

os_stub/cryptlib_openssl/pk/x509.c
The OpenSSL source code describes the crypto include as:
"Internal EC functions for other submodules: not for application use"
- https://github.com/openssl/openssl/blob/master/include/crypto/ec.h
Using the internal APIs makes it difficult to use libspdm as a library
with other packages. So let's remove the uses of the internal API and
instead use the public API.
We can also assume that the internal APIs don't provide backwards
compatible guarantees
=> cryptlib_openssl: x509: Remove internal OpenSSL crypto include

library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c, unit_test/fuzzing/test_requester/test_spdm_requester_encap_request/encap_request.c, unit_test/fuzzing/test_requester/test_spdm_requester_end_session/end_session.c, unit_test/fuzzing/test_requester/test_spdm_requester_get_csr/get_csr.c, unit_test/fuzzing/test_requester/test_spdm_requester_get_digests/get_digests.c, unit_test/fuzzing/test_requester/test_spdm_requester_get_measurements/get_measurements.c, unit_test/fuzzing/test_requester/test_spdm_requester_heartbeat/heartbeat.c, unit_test/fuzzing/test_requester/test_spdm_requester_key_update/key_update.c, unit_test/fuzzing/test_requester/test_spdm_requester_psk_finish/psk_finish.c, unit_test/fuzzing/test_requester/test_spdm_requester_set_certificate/set_certificate.c, unit_test/test_spdm_requester/end_session.c, unit_test/test_spdm_requester/get_certificate.c, unit_test/test_spdm_requester/heartbeat.c, unit_test/test_spdm_requester/key_update.c, unit_test/test_spdm_requester/psk_finish.c, unit_test/test_spdm_requester/set_certificate.c
Fix https://github.com/DMTF/libspdm/issues/2318
=> fix the salt value in export/import function.

os_stub/cryptlib_openssl/pk/x509.c
X509_verify_cert() returns 1 if a complete chain can be built and validated, otherwise 0, and in exceptional circumstances (such as malloc failure and internal errors) it can also return a negative code [1].
By casting an `int` return value to a `bool`, a negative error code can be treated as `true`. This change fixes that.
[1] https://www.openssl.org/docs/man3.0/man3/X509_verify_cert.html
=> cryptlib_openssl: x509: fixup return value usage

.github/workflows/build.yml, CMakeLists.txt, include/library/spdm_common_lib.h, library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c, unit_test/test_spdm_secured_message/CMakeLists.txt, unit_test/test_spdm_secured_message/encode_decode.c, unit_test/test_spdm_secured_message/test_spdm_secured_message.c
This also fixes a bug that was caught by these unit tests.
=> Add unit tests for SPDM secured messages

doc/api/common_api.md, include/library/spdm_common_lib.h, library/spdm_common_lib/libspdm_com_context_data.c
And revert the default value back to little-endian only.
=> Add SESSION_SEQUENCE_NUMBER_ENDIAN

CMakeLists.txt
Fix #2376.
This fix was tested locally.
=> Disable EDDSA when `ENABLE_BINARY_BUILD=1`

library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c, unit_test/test_spdm_secured_message/encode_decode.c
=> Skip AEAD endianness detection

os_stub/cryptlib_mbedtls/pk/x509.c, os_stub/cryptlib_null/pk/x509.c, os_stub/cryptlib_openssl/pk/x509.c, os_stub/spdm_crypt_ext_lib/cryptlib_ext.h, os_stub/spdm_device_secret_lib_sample/lib.c
Section 754 of SPDM 1.3 states that:
```
The CSR shall be populated with a combination of attributes
provided by the Requester via the RequesterInfo field and other
attributes contributed by the Responder itself.
```
libspdm currently supports populating the CSR based on the RequesterInfo, but we don't allow the Responder to add custom attributes.
This patch updates libspdm_gen_x509_csr() to pass in a base certificate that is used to provide CSR attributes. libspdm_gen_x509_csr() will copy the extensions from `base_cert` to the CSR.
This way devices can choose to apply the same extensions from a leaf certificate (or other certificate already on the device) or create a new cert just to pass the extensions in.
By copying the extensions from an existing cert the API should be generic between …
=> os_stub: cryptlib: CSR: Allow copying attributes from an existing cert

CMakeLists.txt, doc/build.md, libspdm.pc.in, os_stub/spdm_device_secret_lib_sample/lib.c
Changes:
- added pkg-config libspdm.pc.in file for cmake to use as template
CMakeLists.txt changes:
- added BUILD_SHARED_LIB cmake parameter (ON/OFF) to enable/disable building of libspdm.so in addition to the static libraries
- added two build paths for libspdm.so that generate distinct pkg-config pc files, for runtime linking with either mbedtls or openssl
=> Added shared library and pkg-config support for libspdm

include/industry_standard/spdm.h, include/library/spdm_requester_lib.h, library/spdm_requester_lib/libspdm_req_challenge.c, library/spdm_responder_lib/libspdm_rsp_challenge_auth.c
Fix https://github.com/DMTF/libspdm/issues/2282
Validated with spdm-emu.
The requester_context can be filled as expected.
=> Add 1.3 support for challenge

include/internal/libspdm_common_lib.h, library/spdm_requester_lib/libspdm_req_encap_challenge_auth.c, library/spdm_responder_lib/libspdm_rsp_encap_challenge.c
This is follow up for https://github.com/DMTF/libspdm/issues/2282 and https://github.com/DMTF/libspdm/pull/2420.
Validated with spdm-emu and spdm-dump https://github.com/DMTF/spdm-dump/pull/90.
=> Add 1.3 encap Challenge for BasicMutAuth

os_stub/cryptlib_mbedtls/pk/x509.c, os_stub/cryptlib_openssl/pk/x509.c
Avoid copying the basic_constraints NID as we already set it ourselves
and also avoid copying the authority_key_identifier as it won't be
correct on the CSR.
This PR also fixes the mbedtls NID copying
=> os_stub/cryptlib_*: x509: Don't copy some NIDs

CMakeLists.txt, os_stub/cryptlib_openssl/CMakeLists.txt, os_stub/openssllib/CMakeLists.txt
There are couple of problems when I try to build libspdm in a Yocto project with ARM architecture.
This pull request fixes the problems which I've met.
I used following cmake command.
```
EXTRA_OECMAKE = "-DARCH=${TUNE_ARCH} -DTOOLCHAIN=NONE -DTARGET=Release -DCRYPTO=openssl -DBUILD_LINUX_SHARED_LIB=ON"
```
1. openssllib and cryptolib_openssl prints "Unknown ARCH" and stop building, because 'os_stub/openssllib/CMakeLists.txt' and 'os_stub/cryptlib_openssl/CMakeLists.txt' has 2 if statement for 'ARCH' cmake parameter and first one prints "Unknown ARCH" with FATAL_ERROR.
2. Warnings and errors from sub-modules related with compile flags.
For ex, following error needs '-include base.h'.
```
| .../libspdm/os_stub/openssllib/include/openssl/configuration.h:55:9: error: unknown type name …
```
=> Fix up for build error in build environment with ARM architecture

library/spdm_responder_lib/libspdm_rsp_algorithms.c
The reason is the bit in req msg is different from the bit in rsp msg.
Fix https://github.com/DMTF/libspdm/issues/2474
Pass test at https://github.com/DMTF/libspdm/pull/2472
=> Mask the multi-key bit in connection_info.

include/library/spdm_transport_pcidoe_lib.h, library/spdm_transport_pcidoe_lib/libspdm_doe_pcidoe.c, unit_test/fuzzing/test_transport/test_spdm_transport_pci_doe_decode_message/spdm_transport_pci_doe_decode_message.c, unit_test/fuzzing/test_transport/test_spdm_transport_pci_doe_encode_message/spdm_transport_pci_doe_encode_message.c
Add helper functions for encoding/decoding the DOE discovery protocol. All DOE requesters and responders must implement this protocol.
There isn't a straight forwrad way to integrate this into libspdm so let's instead implement helper functions that can be used directly by the custom send and receive functions.
=> libspdm_doe_pcidoe: Add DOE discovery encode/decode helpers

CMakeLists.txt, doc/user_guide.md, include/industry_standard/spdm.h, include/internal/libspdm_common_lib.h, include/internal/libspdm_responder_lib.h, include/library/spdm_common_lib.h, include/library/spdm_lib_config.h, include/library/spdm_requester_lib.h, include/library/spdm_responder_lib.h, library/spdm_requester_lib/CMakeLists.txt, library/spdm_requester_lib/libspdm_req_vendor_request.c, library/spdm_responder_lib/CMakeLists.txt, library/spdm_responder_lib/libspdm_rsp_receive_send.c, library/spdm_responder_lib/libspdm_rsp_vendor_response.c, unit_test/test_spdm_responder/receive_send.c, unit_test/test_spdm_vendor_cmds/CMakeLists.txt, unit_test/test_spdm_vendor_cmds/error_test/vendor_cmds_err.c, unit_test/test_spdm_vendor_cmds/test_spdm_vendor_cmds.c, unit_test/test_spdm_vendor_cmds/vendor_cmds.c
Hello,
I have created a new pull request that implements support for Vendor Defined Requests and Responses.
The changes allow responder integrator to register a callback that will process any SPDM Vendor Defined Requests and issue Vendor Defined Responses. It also implements a dedicated method for a Requester to issue a Vendor Defined Request. I added a few tests as well to validate the code.
New public API methods:
Responder:
libspdm_vendor_response_callback_func response_callback;
libspdm_register_vendor_callback_func( ... response_callback);
Requester:
libspdm_vendor_request(... request ... response ...);
Please take a look and let me know any feedback. Thank you.
=> Added full support for Vendor Defined Requests and Responses

include/hal/library/responder/setcertlib.h, include/industry_standard/spdm.h, include/internal/libspdm_responder_lib.h, include/library/spdm_requester_lib.h, library/spdm_requester_lib/libspdm_req_set_certificate.c, library/spdm_responder_lib/libspdm_rsp_set_certificate.c, os_stub/spdm_device_secret_lib_null/lib.c, os_stub/spdm_device_secret_lib_sample/lib.c, unit_test/test_spdm_requester/set_certificate.c, unit_test/test_spdm_responder/set_certificate_rsp.c
Ref: #2292
1. Add new 1.3 erase cert feature for set_certifcate;
2. Add unit_test for erase cert feature;
The code has passed the unit_test.
=> Add 1.3 erase certificate feature for `SET_CERTIFICATE`

os_stub/rnglib/CMakeLists.txt, os_stub/spdm_crypt_ext_lib/cryptlib_ext.h
For nostd/baremetal targets, rnglib cannot currently be used. This change allows the integrator to provide a cryptographically safe implementation for `libspdm_get_random_number_64()`. Such that it is abstracted away from libspdm.
It is the integrators responsibility to provide an implementation that is crypto-graphically safe.
=> rnglib: add support for a nostd target

library/spdm_responder_lib/libspdm_rsp_vendor_response.c, unit_test/test_spdm_responder/receive_send.c
If the new Vendor Defined Responder callback pointers are not assigned and the default get_response_func() pointer is assigned, VENDOR_DEFINED_REQUEST messages will get routed to get_responder_func() instead.
Fixes #2532
=> Fixed compatibility issues with the new Vendor Defined Commands API

os_stub/mbedtlslib/include/mbedtls/config.h
This allows the user to compile libspdm with
`-DCMAKE_C_FLAGS="-DMBEDTLS_SKIP_TIME_CHECK"` for a target that does not support the `time()`/`gmtime()` functions from `time.h`.
Useful for developing/testing on embedded targets without having to create changes locally to comment these macros out.
=> os_stub: mbedtlslib: allow skipping time checks

library/spdm_responder_lib/libspdm_rsp_algorithms.c, unit_test/test_spdm_responder/algorithms.c
=> Fix SPDM 1.3 MEL algorithm negotiate responder

library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c, library/spdm_responder_lib/libspdm_rsp_algorithms.c, unit_test/test_spdm_requester/chunk_get.c, unit_test/test_spdm_requester/chunk_send.c, unit_test/test_spdm_requester/negotiate_algorithms.c, unit_test/test_spdm_responder/algorithms.c
=> Fix MEAS_CAP algorithm negotiate and add unit tests

include/internal/libspdm_common_lib.h
=> Provide rationale for `LIBSPDM_MAX_CT_EXPONENT `

os_stub/debuglib/debuglib.c
=> Enhance `debuglib` checking

CMakeLists.txt
~Similar to [8071c13](https://github.com/DMTF/libspdm/commit/8071c139a89a0b90cb256e787a603c34f028380d), this adds an option to disable flto for the `NONE` toolchain. This is useful when linking against other libraries with foreign FFIs (rust etc...). @alistair23~ 
"The [point](https://github.com/DMTF/libspdm/blob/main/doc/build.md#linux-builds-inside-build-environments) of the "NONE" option though was to provide none of these compiler options and the build project should provide them instead. It seems like https://github.com/DMTF/libspdm/pull/2464 introduced a bug in setting these." As mentioned by Alistair below.
However, the changes introduced
in https://github.com/DMTF/libspdm/commit/811f2b596def04b3a36368cf2098546d7907767f set certain compiler/linker
option that does not comply with …
=> CMakeLists: add disabling flto option for NONE

library/spdm_common_lib/libspdm_com_context_data.c
The compiler believes that the variable secured_context might be used in the switch-case LIBSPDM_DATA_SESSION_SEQUENCE_NUMBER_REQ_DIR without being initialized.  This though does not happen because in that case need_session_info_for_data() will return true and secured_context will be set.
=> Initialize variable to quiet compiler finding

README.md
#2570 updated cmocka to version 1.1.7. This also updates the documentation to 1.1.7.
=> Update cmocka version in documentation

include/hal/library/responder/csrlib.h, library/spdm_responder_lib/libspdm_rsp_csr.c, os_stub/spdm_device_secret_lib_null/lib.c, os_stub/spdm_device_secret_lib_sample/lib.c
=> Add key_pair_id for libspdm_gen_csr_ex

include/library/spdm_crypt_lib.h
generate_iv() iterates over sizeof(uint64_t), accessing an array with LIBSPDM_MAX_AEAD_IV_SIZE number of elements.  With the default build options when no AEAD algorithms are compiled in, this array consists of a single entry.  Gcc 12.2.0 complains about this and aborts the compilation.  Bump the default define to 8 to allow build to succeed.
=> fix default build options for generate_iv()

include/internal/libspdm_macro_check.h, include/library/spdm_lib_config.h, include/library/spdm_requester_lib.h
Fix #2567.
`ENCAP_CAP` is required since libspdm currently does not have a mechanism for a Responder to asynchronously send a message to a Requester.
=> Add Requester header support as an Event Recipient

include/hal/library/memlib.h, library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c
Fix #2601.
This also fixes a bug in the doxygen comments
Signed-off-by: Steven Bellock <sbellock@nvidia.com>.
=> Fix "bad" comparison in libspdm_consttime_is_mem_equal

os_stub/cryptlib_openssl/internal_crypt_lib.h, os_stub/cryptlib_openssl/pk/x509.c, unit_test/test_crypt/x509_verify.c
=> Fix openssl verify cert

include/industry_standard/spdm.h, library/spdm_common_lib/libspdm_com_support.c, library/spdm_requester_lib/CMakeLists.txt, library/spdm_requester_lib/libspdm_req_get_event_types.c, unit_test/test_spdm_requester/CMakeLists.txt, unit_test/test_spdm_requester/error_test/get_event_types_err.c, unit_test/test_spdm_requester/get_event_types.c, unit_test/test_spdm_requester/test_spdm_requester.c
This commit implements the basic functionality for the Requester portion of  `GET_SUPPORTED_EVENT_TYPES` / `SUPPORTED_EVENT_TYPES`. It includes simple unit tests that are to be fleshed out later on.
=> Initial commit for `GET_SUPPORTED_EVENT_TYPES`

doc/api/common_api.md, doc/api/requester_api.md
=> Fix API spelling

library/spdm_requester_lib/libspdm_req_set_certificate.c, library/spdm_responder_lib/libspdm_rsp_set_certificate.c, unit_test/test_spdm_responder/set_certificate_rsp.c
=> Add Set_cert key_pair_id parameter to sync spdm 1.3

unit_test/fuzzing/test_requester/test_spdm_requester_get_capabilities/get_capabilities.c, unit_test/fuzzing/test_requester/test_spdm_requester_negotiate_algorithms/negotiate_algorithms.c, unit_test/fuzzing/test_responder/test_spdm_responder_algorithms/algorithms.c, unit_test/fuzzing/test_responder/test_spdm_responder_challenge_auth/challenge_auth.c
Code coverage has been improved as follows:
```
libspdm_req_negotiate_algorithms.c          81.8% -> 95.3%       
libspdm_req_get_capabilities.c              75.5% -> 94.3%          
libspdm_rsp_algorithms.c                    61.6% -> 74.7%     
libspdm_rsp_challenge_auth.c                81.0% -> 84.1%
```
=> Add new fuzzing test cases for SPDM 1.3.0

unit_test/fuzzing/test_responder/test_spdm_responder_algorithms/algorithms.c, unit_test/fuzzing/test_responder/test_spdm_responder_capabilities/capabilities.c, unit_test/fuzzing/test_responder/test_spdm_responder_certificate/certificate.c, unit_test/fuzzing/test_responder/test_spdm_responder_challenge_auth/challenge_auth.c, unit_test/fuzzing/test_responder/test_spdm_responder_csr/csr.c, unit_test/fuzzing/test_responder/test_spdm_responder_digests/digests.c, unit_test/fuzzing/test_responder/test_spdm_responder_finish_rsp/finish_rsp.c, unit_test/fuzzing/test_responder/test_spdm_responder_heartbeat_ack/heartbeat_ack.c, unit_test/fuzzing/test_responder/test_spdm_responder_key_exchange/key_exchange.c, unit_test/fuzzing/test_responder/test_spdm_responder_key_update/key_update.c, unit_test/fuzzing/test_responder/test_spdm_responder_measurements/measurements.c, unit_test/fuzzing/test_responder/test_spdm_responder_psk_exchange_rsp/psk_exchange_rsp.c, unit_test/fuzzing/test_responder/test_spdm_responder_psk_finish_rsp/psk_finish_rsp.c, unit_test/fuzzing/test_responder/test_spdm_responder_set_certificate/set_certificate_rsp.c, unit_test/fuzzing/test_responder/test_spdm_responder_version/version.c
Code coverage has been improved as follows:
```  
libspdm_rsp_capabilities.c                  91.6% -> 95.4%        
libspdm_rsp_algorithms.c                    61.6% -> 74.7%     
libspdm_rsp_certificate.c                   80.6% -> 82.5%
libspdm_rsp_challenge_auth.c                81.0% -> 84.1%
libspdm_rsp_csr.c                           64.6% -> 71.2%
libspdm_rsp_digests.c                       69.6% -> 77.3%
libspdm_rsp_finish.c                        76.9% -> 81.1%
libspdm_rsp_psk_finish.c                    74.2% -> 80.9%
libspdm_rsp_set_certificate.c               60.6% -> 67.4%
libspdm_rsp_measurements.c                  75.2% -> 78.4%
libspdm_req_psk_exchange.c                  76.6% -> 79.6%	
libspdm_rsp_key_exchange.c	            77.2% -> 80.8%
libspdm_rsp_version.c …
```
=> Do some customized settings to cover more code logical branch

unit_test/fuzzing/test_responder/test_spdm_responder_chunk_send_ack/chunk_send_ack.c
=> Fix fuzzy test case libspdm_test_responder_chunk_send_ack_case1

.github/workflows/cifuzz.yml
=> CI/CD fuzzer should ignore documentation.

library/spdm_requester_lib/libspdm_req_encap_certificate.c, library/spdm_requester_lib/libspdm_req_encap_challenge_auth.c, library/spdm_requester_lib/libspdm_req_encap_digests.c, library/spdm_requester_lib/libspdm_req_encap_key_update.c, library/spdm_responder_lib/libspdm_rsp_chunk_get.c, library/spdm_responder_lib/libspdm_rsp_chunk_send_ack.c, library/spdm_responder_lib/libspdm_rsp_csr.c, library/spdm_responder_lib/libspdm_rsp_encap_response.c, library/spdm_responder_lib/libspdm_rsp_end_session.c, library/spdm_responder_lib/libspdm_rsp_finish.c, library/spdm_responder_lib/libspdm_rsp_heartbeat.c, library/spdm_responder_lib/libspdm_rsp_key_exchange.c, library/spdm_responder_lib/libspdm_rsp_key_update.c, library/spdm_responder_lib/libspdm_rsp_psk_exchange.c, library/spdm_responder_lib/libspdm_rsp_psk_finish.c, library/spdm_responder_lib/libspdm_rsp_set_certificate.c
Fix https://github.com/DMTF/libspdm/issues/2619
=> Fix error code for unsupported_req error.

library/spdm_requester_lib/libspdm_req_handle_error_response.c, library/spdm_responder_lib/libspdm_rsp_chunk_send_ack.c, unit_test/test_spdm_requester/chunk_get.c
Fix https://github.com/DMTF/libspdm/issues/2631
The patch [7dd4c5f](https://github.com/DMTF/libspdm/pull/2640/commits/7dd4c5fd6ed5c05f7de09358fe12a11a349a1ec8) and [3eef8d6](https://github.com/DMTF/libspdm/pull/2640/commits/3eef8d6cdb3ebfe20a069e112964042bcc541fcf) fixed the buffer overflow issue.
The rest is additional enhancement.
=> fix responder_chunk_send buffer overflow

unit_test/test_spdm_requester/get_csr.c, unit_test/test_spdm_responder/csr.c
Fix: #2632 
The successful unit_test will always make cached.csr name unchanged. But a failed unit_test may change cached.csr to cached.staging, which cause the next unit_test still failing even if the issue is fixed.
Add new api to ensure that cached.csr always exists at the beginning.
=> Ensure that cached.csr always exists at the beginning

include/internal/libspdm_requester_lib.h, include/internal/libspdm_responder_lib.h, include/library/spdm_requester_lib.h
=> Make all measurement declaration under the macro

unit_test/fuzzing/test_responder/test_spdm_responder_chunk_send_ack/chunk_send_ack.c
Fix: #2646
Fuzzy test cases should not excessively interfere with the input test_buffer, and these excessive interventions should be eliminated.
Credit to OSS-Fuzz.
=> Fix heap buffer overflow in libspdm_test_responder_chunk_send_ack_case1

library/spdm_responder_lib/libspdm_rsp_vendor_response.c
The pointer of Vendor Defined Request is moved, then the request size should be adjusted accordingly.
=> Fix vendor defined request size

CMakeLists.txt, os_stub/cryptlib_openssl/pk/x509.c
Fix: #2678
The default cert check doesn't have the flag.
The user can use the following build commad to add the flag. 
`cmake -G"NMake Makefiles" -DARCH=x64 -DTOOLCHAIN=VS2019 -DTARGET=Release -DCRYPTO=openssl -DX509_IGNORE_CRITICAL=ON ..`
=> Add ignore unhandle critical extension check flag for Openssl

unit_test/fuzzing/spdm_unit_fuzzing_common/toolchain_harness.c
=> Rectify the four-byte alignment issue in the fuzzy testing.

.gitmodules
Resolves #2707 
The previous host for the cmocka submodule (https://git.cryptomilk.org/projects/cmocka.git) has been unreliable so this switches to the gitlab mirror at https://gitlab.com/cmocka/cmocka.git.
The submodule itself points to the same commit hash in the mirror.
=> Update cmocka submodule to gitlab

include/library/spdm_common_lib.h, include/library/spdm_crypt_lib.h, include/library/spdm_requester_lib.h, include/library/spdm_responder_lib.h, include/library/spdm_return_status.h, include/library/spdm_secured_message_lib.h, include/library/spdm_transport_mctp_lib.h, include/library/spdm_transport_pcidoe_lib.h
Fix #2704.
In order to support linkage to cpp application, I'm adding "extern C" block to the library headers. 
I've built libspdm successfully into an embedded cpp application with this and some other cmake changes.
=> Add "extern C" to library headers 

os_stub/cryptlib_mbedtls/pk/x509.c, os_stub/cryptlib_openssl/pk/x509.c, unit_test/test_crypt/x509_verify.c, unit_test/test_spdm_crypt/test_spdm_crypt.c
=> Add length check during verify cert chain

library/spdm_requester_lib/libspdm_req_vendor_request.c
=> Fix wrong release_receiver_buffer before acquire

include/hal/library/responder/measlib.h, include/industry_standard/spdm.h, include/internal/libspdm_requester_lib.h, include/internal/libspdm_responder_lib.h, include/library/spdm_lib_config.h, include/library/spdm_requester_lib.h, library/spdm_common_lib/libspdm_com_context_data.c, library/spdm_requester_lib/CMakeLists.txt, library/spdm_requester_lib/libspdm_req_get_measurement_extension_log.c, library/spdm_responder_lib/CMakeLists.txt, library/spdm_responder_lib/libspdm_rsp_measurement_extension_log.c, library/spdm_responder_lib/libspdm_rsp_receive_send.c, os_stub/spdm_device_secret_lib_null/lib.c, os_stub/spdm_device_secret_lib_sample/lib.c, os_stub/spdm_device_secret_lib_sample/spdm_device_secret_lib_internal.h, unit_test/spdm_unit_test_common/algo.c, unit_test/spdm_unit_test_common/spdm_unit_test.h, unit_test/test_spdm_requester/CMakeLists.txt, unit_test/test_spdm_requester/get_measurement_extension_log.c, unit_test/test_spdm_requester/test_spdm_requester.c, unit_test/test_spdm_responder/CMakeLists.txt, unit_test/test_spdm_responder/measurement_extension_log.c, unit_test/test_spdm_responder/measurements.c, unit_test/test_spdm_responder/test_spdm_responder.c
=> Add SPDM 1.3 new feature Get_MEL

include/library/spdm_requester_lib.h, library/spdm_requester_lib/libspdm_req_get_csr.c, library/spdm_requester_lib/libspdm_req_set_certificate.c, library/spdm_responder_lib/libspdm_rsp_csr.c, library/spdm_responder_lib/libspdm_rsp_set_certificate.c, unit_test/test_spdm_requester/get_csr.c, unit_test/test_spdm_requester/set_certificate.c, unit_test/test_spdm_responder/csr.c, unit_test/test_spdm_responder/set_certificate_rsp.c
=> Enforce non-zero `CertModel`

include/hal/library/debuglib.h
=> Remove unused variable

unit_test/spdm_unit_test_common/common.c
=> Check state of buffers at end of test

include/internal/libspdm_common_lib.h, include/internal/libspdm_secured_message_lib.h, include/library/spdm_lib_config.h, library/spdm_common_lib/libspdm_com_context_data_session.c, library/spdm_secured_message_lib/libspdm_secmes_context_data.c, unit_test/test_spdm_responder/respond_if_ready.c
If `LIBSPDM_ENABLE_CAPABILITY_PSK_EX_CAP` is not enabled then `LIBSPDM_PSK_CONTEXT_LENGTH` and `LIBSPDM_PSK_MAX_HINT_LENGTH` are still required for a successful build. This pull request fixes that as a subtask of #1211.
=> Don't require PSK macros if PSK is not enabled

doc/design.md, library/spdm_requester_lib/libspdm_req_challenge.c, library/spdm_requester_lib/libspdm_req_encap_request.c, library/spdm_requester_lib/libspdm_req_end_session.c, library/spdm_requester_lib/libspdm_req_finish.c, library/spdm_requester_lib/libspdm_req_get_capabilities.c, library/spdm_requester_lib/libspdm_req_get_certificate.c, library/spdm_requester_lib/libspdm_req_get_csr.c, library/spdm_requester_lib/libspdm_req_get_digests.c, library/spdm_requester_lib/libspdm_req_get_event_types.c, library/spdm_requester_lib/libspdm_req_get_measurement_extension_log.c, library/spdm_requester_lib/libspdm_req_get_measurements.c, library/spdm_requester_lib/libspdm_req_get_version.c, library/spdm_requester_lib/libspdm_req_handle_error_response.c, library/spdm_requester_lib/libspdm_req_heartbeat.c, library/spdm_requester_lib/libspdm_req_key_exchange.c, library/spdm_requester_lib/libspdm_req_key_update.c, library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c, library/spdm_requester_lib/libspdm_req_psk_exchange.c, library/spdm_requester_lib/libspdm_req_psk_finish.c, library/spdm_requester_lib/libspdm_req_set_certificate.c, library/spdm_requester_lib/libspdm_req_vendor_request.c
=> Do not zeroize receive buffer

include/internal/libspdm_common_lib.h
=> Remove unused typedef

library/spdm_responder_lib/libspdm_rsp_measurements.c
=> Enforce non-zero measurement count

include/industry_standard/pcidoe.h, include/library/spdm_transport_pcidoe_lib.h, library/spdm_transport_pcidoe_lib/libspdm_doe_pcidoe.c, unit_test/fuzzing/test_transport/test_spdm_transport_pci_doe_decode_message/spdm_transport_pci_doe_decode_message.c
Fix #2783 
DOE Discovery Version is first introduced in PCIE Spec 6.1 Section 6.30.1.1.
libspdm_pci_doe_decode_discovery_request is unchanged. New API libspdm_pci_doe_decode_discovery_request_version is added to get the version from doe_discovery_request. This is to prevent the building broken for the exsting codes.
=> Add DOE Discovery Version

library/spdm_requester_lib/libspdm_req_get_measurements.c
Ensure that the length of the measurements matches the length the responder reported, otherwise return an error.
=> libspdm_req_get_measurements: Check the length of all measurements

os_stub/spdm_device_secret_lib_null/lib.c
=> Move null implementation of libspdm_event_get_types

include/internal/libspdm_common_lib.h, library/spdm_common_lib/libspdm_com_context_data.c
If pointer arithmetic is needed then they can be cast to the appropriate type.
=> Make buffers void instead of uint8_t

unit_test/test_spdm_secured_message/encode_decode.c, unit_test/test_spdm_secured_message/test_spdm_secured_message.c
In initialize_secured_message_context(), two for-loops access two arrays
with LIBSPDM_MAX_AEAD_KEY_SIZE number of elements and with
LIBSPDM_MAX_AEAD_IV_SIZE number of elements separately. Both iterations
go beyond the size of the arrays when the required macro
LIBSPDM_AEAD_AES_256_GCM_SUPPORT for the test is undefined.
Gcc 11.4.0 reports this and aborts the compilation when -DTARGET=Release
is specified with cmake for the build. Check macro define in the unit
test to avoid compile error.
=> Fix default build options for initialize_secured_message_context()

library/spdm_common_lib/libspdm_com_context_data.c, library/spdm_requester_lib/libspdm_req_handle_error_response.c, library/spdm_requester_lib/libspdm_req_send_receive.c
This commit fixes the following Coverity CIDs:
- 467406
- 467274
- 467469
- 467313
- 467400
They are all of type `unused value`.
=> Fix unused value Coverity types

doc/api/common_api.md, doc/user_guide.md, include/hal/library/responder/key_pair_info.h, include/industry_standard/spdm.h, include/internal/libspdm_common_lib.h, include/internal/libspdm_responder_lib.h, include/library/spdm_common_lib.h, include/library/spdm_lib_config.h, include/library/spdm_requester_lib.h, library/spdm_common_lib/libspdm_com_context_data.c, library/spdm_requester_lib/CMakeLists.txt, library/spdm_requester_lib/libspdm_req_get_key_pair_info.c, library/spdm_responder_lib/CMakeLists.txt, library/spdm_responder_lib/libspdm_rsp_get_key_pair_info.c, library/spdm_responder_lib/libspdm_rsp_receive_send.c, os_stub/spdm_device_secret_lib_null/lib.c, os_stub/spdm_device_secret_lib_sample/lib.c, os_stub/spdm_device_secret_lib_sample/spdm_device_secret_lib_internal.h, unit_test/test_spdm_requester/CMakeLists.txt, unit_test/test_spdm_requester/error_test/get_key_pair_info_err.c, unit_test/test_spdm_requester/get_key_pair_info.c, unit_test/test_spdm_requester/test_spdm_requester.c, unit_test/test_spdm_responder/CMakeLists.txt, unit_test/test_spdm_responder/key_pair_info.c, unit_test/test_spdm_responder/test_spdm_responder.c
=> Add SPDM 1.3 new feature:get_key_pair_info

library/spdm_requester_lib/libspdm_req_challenge.c, library/spdm_requester_lib/libspdm_req_end_session.c, library/spdm_requester_lib/libspdm_req_finish.c, library/spdm_requester_lib/libspdm_req_get_capabilities.c, library/spdm_requester_lib/libspdm_req_get_certificate.c, library/spdm_requester_lib/libspdm_req_get_csr.c, library/spdm_requester_lib/libspdm_req_get_digests.c, library/spdm_requester_lib/libspdm_req_get_event_types.c, library/spdm_requester_lib/libspdm_req_get_measurement_extension_log.c, library/spdm_requester_lib/libspdm_req_get_measurements.c, library/spdm_requester_lib/libspdm_req_get_version.c, library/spdm_requester_lib/libspdm_req_heartbeat.c, library/spdm_requester_lib/libspdm_req_key_exchange.c, library/spdm_requester_lib/libspdm_req_key_update.c, library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c, library/spdm_requester_lib/libspdm_req_psk_exchange.c, library/spdm_requester_lib/libspdm_req_psk_finish.c, library/spdm_requester_lib/libspdm_req_set_certificate.c, library/spdm_requester_lib/libspdm_req_vendor_request.c
Fix https://github.com/DMTF/libspdm/issues/2810
=> remove redundant retry count check found by coverity

unit_test/test_spdm_requester/error_test/vendor_request_err.c, unit_test/test_spdm_requester/vendor_request.c
=> Change spdm_test_context to spdm_context in unit test

include/hal/library/eventlib.h, include/industry_standard/spdm.h, include/internal/libspdm_responder_lib.h, include/library/spdm_requester_lib.h, library/spdm_requester_lib/CMakeLists.txt, library/spdm_requester_lib/libspdm_req_subscribe_event_types.c, library/spdm_responder_lib/CMakeLists.txt, library/spdm_responder_lib/libspdm_rsp_receive_send.c, library/spdm_responder_lib/libspdm_rsp_subscribe_event_types_ack.c, os_stub/spdm_device_secret_lib_null/lib.c, os_stub/spdm_device_secret_lib_sample/lib.c, unit_test/spdm_unit_test_common/event_support.c, unit_test/spdm_unit_test_common/spdm_unit_test.h, unit_test/test_spdm_requester/CMakeLists.txt, unit_test/test_spdm_requester/error_test/get_event_types_err.c, unit_test/test_spdm_requester/error_test/subscribe_event_types_err.c, unit_test/test_spdm_requester/get_event_types.c, unit_test/test_spdm_requester/subscribe_event_types.c, unit_test/test_spdm_requester/test_spdm_requester.c, unit_test/test_spdm_responder/CMakeLists.txt, unit_test/test_spdm_responder/error_test/subscribe_event_types_ack_err.c, unit_test/test_spdm_responder/subscribe_event_types_ack.c, unit_test/test_spdm_responder/test_spdm_responder.c
=> Add support for SUBSCRIBE_EVENT_TYPES

library/spdm_crypt_lib/libspdm_crypt_cert.c
=> Skip certificate algorithm check

include/hal/library/responder/key_pair_info.h, include/industry_standard/spdm.h, include/internal/libspdm_responder_lib.h, include/library/spdm_lib_config.h, include/library/spdm_requester_lib.h, library/spdm_requester_lib/CMakeLists.txt, library/spdm_requester_lib/libspdm_req_get_key_pair_info.c, library/spdm_requester_lib/libspdm_req_set_key_pair_info.c, library/spdm_responder_lib/CMakeLists.txt, library/spdm_responder_lib/libspdm_rsp_receive_send.c, library/spdm_responder_lib/libspdm_rsp_set_key_pair_info_ack.c, os_stub/spdm_device_secret_lib_null/lib.c, os_stub/spdm_device_secret_lib_sample/lib.c, unit_test/test_spdm_requester/CMakeLists.txt, unit_test/test_spdm_requester/error_test/set_key_pair_info_err.c, unit_test/test_spdm_requester/set_key_pair_info.c, unit_test/test_spdm_requester/test_spdm_requester.c, unit_test/test_spdm_responder/CMakeLists.txt, unit_test/test_spdm_responder/set_key_pair_info_ack.c, unit_test/test_spdm_responder/test_spdm_responder.c
The PR is pure set_key_pair_info feature now.
=> Add SPDM 1.3 new feature: Set key pair info

include/industry_standard/pcidoe.h
In particular clarify that the PCIe specification defines the size of a double word as four bytes.
=> Cleanup DOE header

include/industry_standard/cxl_tsp.h
Add CXL 3.1 TEE Security Protocol (TSP) header file.
Only mandatory commands are included in this patch.
The optional commands will be added later.
=> Add TSP header file

.github/workflows/code_coverage.yml
Run code coverage weekly instead of nightly. Once a day is too frequent.
=> Run code coverage weekly

include/hal/library/eventlib.h, library/spdm_responder_lib/libspdm_rsp_supported_event_types.c, os_stub/spdm_device_secret_lib_null/lib.c, os_stub/spdm_device_secret_lib_sample/lib.c
=> Add `session_id` to `libspdm_event_get_types`

os_stub/spdm_device_secret_lib_sample/lib.c
=> Add variable for format specifier

include/library/spdm_crypt_lib.h, library/spdm_crypt_lib/libspdm_crypt_cert.c, library/spdm_responder_lib/libspdm_rsp_set_certificate.c
=> Enforce mandatory CA in SET_CERTIFICATE

CMakeLists.txt
Trying to compile with toolchain AARCH64_GCC generates the following error:
```bash
$WORKSPACE/libspdm/os_stub/openssllib/openssl/crypto/o_str.c: In function ‘openssl_strerror_r’:
$WORKSPACE/libspdm/os_stub/openssllib/openssl/crypto/o_str.c:329:13: error: implicit declaration of function ‘strerror_r’; did you mean ‘strerror’? [-Werror=implicit-function-declaration]
329 |     return !strerror_r(errnum, buf, buflen);
|             ^~~~~~~~~~
```
Fix: just add the flag `-std=c11` in OPENSSL_FLAGS for AARCH64_GCC.
=> Fix openssl build failure for AARCH64_GCC

doc/api/common_api.md, include/library/spdm_common_lib.h, library/spdm_common_lib/libspdm_com_context_data.c
Provide an enum to allow libspdm_get_data to return the current request and its size from the tracking pointer in the context.
=> Add libspdm_get_data enum for accessing the request

include/internal/libspdm_common_lib.h, library/spdm_responder_lib/libspdm_rsp_certificate.c, library/spdm_responder_lib/libspdm_rsp_digests.c, library/spdm_responder_lib/libspdm_rsp_set_certificate.c, unit_test/test_spdm_responder/certificate.c, unit_test/test_spdm_responder/digests.c
If a `SET_CERTIFICATE` request results in `ResetRequired` then subsequent `GET_CERTIFICATE` requests for that slot, and `GET_DIGESTS`, should result in `ResetRequired`.
=> Return `ResetRequired` for certificate retrieval

unit_test/test_spdm_responder/set_key_pair_info_ack.c
=> Fix the failure of test_spdm_responder when it is run multiple times.

library/spdm_common_lib/libspdm_com_crypto_service.c
The issue causes failure if pub_key_id is set for requester only.
=> fix incorrect size check in libspdm_get_local_public_key_buffer.

os_stub/debuglib/debuglib.c
This resolves an issue where setting the assert config to breakpoint on ARM will cause the build to fail with an accurate but unhelpful compiler error.
This restricts the mnemonic to x86-64 architectures, and provides a more explanatory error.
Addresses issue: #2890
=> Restrict x86 mnemonic to x86-64

library/spdm_requester_lib/libspdm_req_encap_request.c, unit_test/test_spdm_requester/encap_request.c
Transport may append more bytes for alignment and cause failure. Also, the smaller header is already checked before. So just remove it here.
=> Remove unnecessary length check for encap message size

library/spdm_responder_lib/libspdm_rsp_csr.c, unit_test/test_spdm_responder/csr.c
=> Update error code for unsupported RequesterInfo in CSR requests

library/spdm_requester_lib/libspdm_req_encap_request.c, library/spdm_responder_lib/libspdm_rsp_encap_response.c
In preparation for encapsulated event messages, this commit cleans up encapsulated send and receive routines for both the Requester and Responder.
=> Clean up encapsulated send and receive

include/library/spdm_lib_config.h, os_stub/spdm_device_secret_lib_sample/set_cert.c, unit_test/test_spdm_responder/set_certificate_rsp.c
Fix issues in #2901.
1. Set LIBSPDM_SET_CERT_CSR_PARAMS to 0 by default.
2. Wrap is_busy parameter in sert_cert.c with LIBSPDM_SET_CERT_CSR_PARAMS.
=> Fix `SET_CERTIFICATE` build break

include/hal/library/responder/csrlib.h, library/spdm_responder_lib/libspdm_rsp_csr.c, os_stub/spdm_device_secret_lib_null/lib.c, os_stub/spdm_device_secret_lib_sample/csr.c, unit_test/test_spdm_responder/csr.c
Fix #2908.
This was tested with all four combination of values for `LIBSPDM_SET_CERT_CSR_PARAMS` and `LIBSPDM_ENABLE_CAPABILITY_CSR_CAP_EX`.
=> Cleanup csrlib

README.md, os_stub/openssllib/openssl_gen/openssl/opensslv.h, os_stub/openssllib/openssl_gen/prov/ciphercommon.h, os_stub/openssllib/openssl_gen/prov/ciphercommon_aead.h, os_stub/openssllib/version.txt
Fix https://github.com/DMTF/libspdm/issues/2820.
=> Update OpenSSL to v3.0.14

.github/workflows/compliance-checks.yml
Fix #2931.
Later on this can be changed back to ubuntu-latest once the configuration file is updated.
=> Use Ubuntu 22.04 for uncrustify

os_stub/cryptlib_mbedtls/pk/x509.c
- Add explicit NULL check.
- Fix typos.
- Make documentation and implementation consistent.
=> Clean up minor x.509 issues

library/spdm_requester_lib/libspdm_req_get_capabilities.c, library/spdm_requester_lib/libspdm_req_key_exchange.c, library/spdm_requester_lib/libspdm_req_psk_exchange.c, library/spdm_responder_lib/libspdm_rsp_capabilities.c, library/spdm_responder_lib/libspdm_rsp_key_exchange.c, library/spdm_responder_lib/libspdm_rsp_psk_exchange.c, unit_test/test_spdm_requester/error_test/get_capabilities_err.c, unit_test/test_spdm_requester/error_test/key_exchange_err.c, unit_test/test_spdm_requester/key_exchange.c, unit_test/test_spdm_requester/psk_exchange.c, unit_test/test_spdm_responder/capabilities.c, unit_test/test_spdm_responder/key_exchange.c, unit_test/test_spdm_responder/psk_exchange.c, unit_test/test_spdm_responder/respond_if_ready.c
=> Check key exchange MAC_CAP when message is sent

include/industry_standard/spdm.h, library/spdm_common_lib/libspdm_com_opaque_data.c, unit_test/test_spdm_common/context_data.c
Fix https://github.com/DMTF/libspdm/issues/2934
=> Allow non-zero vendor_id for libspdm_get_element_from_opaque_data()

library/spdm_requester_lib/libspdm_req_get_capabilities.c, library/spdm_responder_lib/libspdm_rsp_capabilities.c, unit_test/test_spdm_requester/error_test/get_capabilities_err.c, unit_test/test_spdm_responder/capabilities.c
Fix #2944.
This also adds back relevant unit tests that were removed in #2933.
=> Enforce MAC/ENCRYPT capability checks

.github/workflows/cifuzz.yml
See https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/.
=> Update upload-artifact version

README.md, include/industry_standard/cxl_idekm.h, include/library/spdm_transport_pcidoe_lib.h, library/spdm_transport_pcidoe_lib/libspdm_doe_pcidoe.c
PCIe is the capitalization recognized by PCI-SIG.
=> Change PCIE to PCIe

CMakeLists.txt
Yocto/OpenEmbedded usses "x86_64" for the 64-bit x86 architecture, which currently isn't supported by libspdm. As it's a common name for the architecture let's add support for "x86_64" as the ARCH.
=> CMakeLists.txt: Support x86_64 ARCH

library/spdm_requester_lib/libspdm_req_handle_error_response.c, library/spdm_requester_lib/libspdm_req_send_receive.c, library/spdm_responder_lib/libspdm_rsp_chunk_get.c, library/spdm_responder_lib/libspdm_rsp_chunk_send_ack.c, unit_test/test_spdm_requester/chunk_get.c, unit_test/test_spdm_requester/chunk_send.c, unit_test/test_spdm_responder/chunk_get.c, unit_test/test_spdm_responder/chunk_send_ack.c
Fix https://github.com/DMTF/libspdm/issues/2875
=> Fix chunk_seq_no wrap issue.

library/spdm_crypt_lib/libspdm_crypt_cert.c
=> Fix old-style-declaration warning

doc/api/common_api.md, doc/api/secured_message_api.md, doc/fips.md, doc/test.md, os_stub/cryptlib_mbedtls/pk/x509.c, os_stub/cryptlib_null/pk/x509.c, os_stub/cryptlib_openssl/pk/x509.c, os_stub/debuglib/debuglib.c, os_stub/mbedtlslib/include/mbedtls/libspdm_mbedtls_config.h, os_stub/spdm_device_secret_lib_sample/read_special_cert.c, unit_test/fuzzing/test_requester/test_spdm_requester_key_update/key_update.c, unit_test/fuzzing/test_responder/test_spdm_responder_algorithms/algorithms.c, unit_test/fuzzing/test_responder/test_spdm_responder_chunk_get/chunk_get.c, unit_test/test_spdm_common/context_data.c, unit_test/test_spdm_requester/encap_certificate.c, unit_test/test_spdm_requester/encap_key_update.c, unit_test/test_spdm_requester/error_test/get_digests_err.c, unit_test/test_spdm_requester/error_test/get_measurements_err.c, unit_test/test_spdm_requester/error_test/negotiate_algorithms_err.c, unit_test/test_spdm_requester/get_certificate.c, unit_test/test_spdm_requester/get_measurements.c, unit_test/test_spdm_requester/key_update.c, unit_test/test_spdm_responder/certificate.c, unit_test/test_spdm_responder/chunk_get.c, unit_test/test_spdm_responder/chunk_send_ack.c, unit_test/test_spdm_responder/csr.c, unit_test/test_spdm_responder/encap_get_digests.c, unit_test/test_spdm_responder/key_update.c, unit_test/test_spdm_responder/measurements.c, unit_test/test_spdm_responder/set_certificate_rsp.c
Spelling mistakes were identified using the following command:
```
$ codespell -w $(find . -type f \( -iname \*.c -o -iname \*.h -o -iname \*.md \))
```
Wherever possible, codespell automatically fixed the errors. For any issues that could not be automatically corrected, those were addressed manually.
=> Fix spelling mistakes across the repository

include/industry_standard/pci_idekm.h, include/industry_standard/pci_tdisp.h, include/industry_standard/pcidoe.h
In particular DOE/TDISP/IDE are no longer ECNs.
=> Clean up PCIe headers

include/hal/library/endpointinfolib.h, library/spdm_responder_lib/libspdm_rsp_endpoint_info.c, os_stub/spdm_device_secret_lib_sample/endpointinfo.c, unit_test/test_spdm_requester/error_test/get_endpoint_info_err.c, unit_test/test_spdm_requester/get_endpoint_info.c, unit_test/test_spdm_responder/endpoint_info.c
=> libspdm_generate_device_endpoint_info should not be called twice

script/format_nix.sh
It seems that the uncrustify config file that we have does not work with Ubuntu 24.04 which comes with 0.78.
And the current config file with 0.78 seems to complain about deprecated keys and actually did much more changes than what the CI did. Hence added a version check in the format script. We need to ensure that we change the version here as and when we start supporting new versions of uncrustify in CI.
=> format_nix: Add version check for uncrustify

os_stub/openssllib/openssl_gen/openssl/asn1.h
This commit [1] introduced this new API which is used by pem.h from openssl and it should be provided by asn1.h which is vendored here so it goes out of sync and causes build errors e.g
In file included from ./os_stub/cryptlib_openssl/pk/x509.c:18: /usr/include/openssl/pem.h:399:28: error: unknown type name 'OSSL_i2d_of_void_ctx'
399 | int PEM_ASN1_write_bio_ctx(OSSL_i2d_of_void_ctx *i2d, void *vctx,
[1] https://github.com/openssl/openssl/commit/35f6e7ea02b599d5aaf220b4720cbadd946d8023
=> Backport API introduced in openssl 3.5.0

.github/dependabot.yml
Reference: https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions
[Using Dependabot version updates to keep actions up to date](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-dependabot-version-updates-to-keep-actions-up-to-date)
It is also related to https://github.com/DMTF/libspdm/issues/3034
=> Add dependabot file for auto scan and update.

library/spdm_requester_lib/libspdm_req_encap_request.c, unit_test/test_spdm_requester/encap_request.c
=> Handle "error" if no encapsulated request

include/internal/libspdm_common_lib.h, include/internal/libspdm_requester_lib.h, include/internal/libspdm_responder_lib.h, include/library/spdm_common_lib.h, include/library/spdm_lib_config.h, include/library/spdm_responder_lib.h, library/spdm_requester_lib/CMakeLists.txt, library/spdm_requester_lib/libspdm_req_encap_endpoint_info.c, library/spdm_requester_lib/libspdm_req_encap_request.c, library/spdm_responder_lib/CMakeLists.txt, library/spdm_responder_lib/libspdm_rsp_encap_get_endpoint_info.c, library/spdm_responder_lib/libspdm_rsp_encap_response.c, unit_test/test_spdm_requester/CMakeLists.txt, unit_test/test_spdm_requester/encap_endpoint_info.c, unit_test/test_spdm_requester/encap_request.c, unit_test/test_spdm_requester/error_test/encap_endpoint_info_err.c, unit_test/test_spdm_requester/test_spdm_requester.c, unit_test/test_spdm_responder/CMakeLists.txt, unit_test/test_spdm_responder/encap_get_endpoint_info.c, unit_test/test_spdm_responder/encap_response.c, unit_test/test_spdm_responder/error_test/encap_get_endpoint_info_err.c, unit_test/test_spdm_responder/test_spdm_responder.c
Fix the issue: #2294
ENDPOINT_INFO is SPDM spec 1.3 new feature.
Add encapsulate ENDPOINT_INFO for Libspdm.
This PR is dependent on https://github.com/DMTF/libspdm/pull/3000
=> Add SPDM 1.3 feature encapsulate GET_ENDPOINT_INFO

library/spdm_transport_storage_lib/libspdm_storage.c
Clean up dead code as per Coverity 482735. @steven-bellock
Fixes: https://github.com/DMTF/libspdm/issues/3116
=> lib: spdm_transport_storage: cleanup dead code

include/industry_standard/spdm.h, include/internal/libspdm_requester_lib.h, library/spdm_requester_lib/libspdm_req_finish.c, library/spdm_requester_lib/libspdm_req_psk_finish.c, library/spdm_responder_lib/libspdm_rsp_finish.c, library/spdm_responder_lib/libspdm_rsp_psk_finish.c, unit_test/test_spdm_requester/finish.c, unit_test/test_spdm_requester/psk_finish.c, unit_test/test_spdm_responder/finish.c, unit_test/test_spdm_responder/psk_finish.c
Fix https://github.com/DMTF/libspdm/issues/3130
NOTE: This PR is based on https://github.com/DMTF/libspdm/pull/3129.
=> 1.4 Add opaque to FINISH/PSK_FINISH

include/internal/libspdm_common_lib.h, library/spdm_common_lib/libspdm_com_crypto_service_session.c, library/spdm_requester_lib/libspdm_req_key_exchange.c, library/spdm_requester_lib/libspdm_req_psk_exchange.c, library/spdm_responder_lib/libspdm_rsp_key_exchange.c, library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
This reverts commit 8abdda1dda42d2dc7aad37b47409ad9353433ba3 and fixes #3241.
=> Reapply "Remove unused parameter"

os_stub/cryptlib_openssl/der/der.c, os_stub/cryptlib_openssl/pem/pem.c, os_stub/cryptlib_openssl/pk/ec.c, os_stub/cryptlib_openssl/pk/x509.c
This update migrates EC_KEY* usage to EVP_PKEY*, enabling compatibility with the OpenSSL 3.0 Provider API. This change is essential for implementing TPM support in SPDM and ensures future-proofing with newer OpenSSL versions.
Related issue: #2724
=> Refactor: Replace EC_KEY* with EVP_PKEY* for OpenSSL 3.0 Provider API support

include/internal/libspdm_common_lib.h, library/spdm_common_lib/CMakeLists.txt, library/spdm_common_lib/libspdm_com_event.c, library/spdm_requester_lib/libspdm_req_encap_event_ack.c
This commit moves the event handlers from the Requester library to the common library so that the Responder can use them as well.
=> Move event handlers to common library

unit_test/include/library/spdm_transport_test_lib.h, unit_test/spdm_transport_test_lib/common.c, unit_test/spdm_transport_test_lib/test.c, unit_test/test_size/test_size_of_spdm_requester/spdm_requester_authentication.c, unit_test/test_spdm_common/context_data.c, unit_test/test_spdm_requester/challenge.c, unit_test/test_spdm_requester/encap_challenge_auth.c, unit_test/test_spdm_requester/encap_endpoint_info.c, unit_test/test_spdm_requester/error_test/get_endpoint_info_err.c, unit_test/test_spdm_requester/error_test/get_measurements_err.c, unit_test/test_spdm_requester/finish.c, unit_test/test_spdm_requester/get_certificate.c, unit_test/test_spdm_requester/get_csr.c, unit_test/test_spdm_requester/get_digests.c, unit_test/test_spdm_requester/get_endpoint_info.c, unit_test/test_spdm_requester/get_measurements.c, unit_test/test_spdm_requester/get_version.c, unit_test/test_spdm_requester/key_update.c, unit_test/test_spdm_requester/psk_finish.c, unit_test/test_spdm_requester/set_certificate.c, unit_test/test_spdm_requester/set_key_pair_info.c, unit_test/test_spdm_responder/algorithms.c, unit_test/test_spdm_responder/challenge_auth.c, unit_test/test_spdm_responder/encap_challenge.c, unit_test/test_spdm_responder/encap_get_digests.c, unit_test/test_spdm_responder/encap_get_endpoint_info.c, unit_test/test_spdm_responder/encap_key_update.c, unit_test/test_spdm_responder/endpoint_info.c, unit_test/test_spdm_responder/measurements.c, unit_test/test_spdm_responder/set_key_pair_info_ack.c
Rename the non-existent `RETURN_SUCCESS` to `LIBSPDM_STATUS_SUCCESS` in unit test files, or delete it.
=> Rename non-existent `RETURN_SUCCESS` in unit test documentation

library/spdm_responder_lib/libspdm_rsp_event_ack.c, os_stub/spdm_device_secret_lib_sample/event.c, unit_test/test_spdm_responder/error_test/event_ack_err.c, unit_test/test_spdm_responder/error_test/subscribe_event_types_ack_err.c, unit_test/test_spdm_responder/error_test/supported_event_types_err.c
This also fixes #3267, which was discovered in the course of adding these test cases.
These test cases were guided by the following coverage reports:
- https://dmtf.github.io/libspdm/coverage_log/library/spdm_responder_lib/libspdm_rsp_event_ack.c.gcov.html
- https://dmtf.github.io/libspdm/coverage_log/library/spdm_responder_lib/libspdm_rsp_subscribe_event_types_ack.c.gcov.html
- https://dmtf.github.io/libspdm/coverage_log/library/spdm_responder_lib/libspdm_rsp_supported_event_types.c.gcov.html
=> Expand Responder event error testing

unit_test/test_spdm_requester/error_test/encap_subscribe_event_types_ack_err.c, unit_test/test_spdm_requester/error_test/encap_supported_event_types_err.c, unit_test/test_spdm_requester/error_test/send_event_err.c, unit_test/test_spdm_requester/test_spdm_requester.c
This also fixes #3269, which was discovered in the course of adding these test cases.
These test cases were guided by the following coverage reports:
- https://dmtf.github.io/libspdm/coverage_log/library/spdm_requester_lib/libspdm_req_encap_subscribe_event_types_ack.c.gcov.html
- https://dmtf.github.io/libspdm/coverage_log/library/spdm_requester_lib/libspdm_req_encap_supported_event_types.c.gcov.html
- https://dmtf.github.io/libspdm/coverage_log/library/spdm_requester_lib/libspdm_req_send_event.c.gcov.html
=> Expand Requester event error testing
